export type AnthroNote = {
  slug: string;
  title: string;
  paper: 1 | 2;
  section: string;
  topic: number;
  subtopics?: string[];
  description: string;
};

// ── Paper I — Foundations of Anthropology ────────────────────

export const paper1Notes: AnthroNote[] = [
  {
    slug: 'meaning-scope-development-anthropology',
    title: 'Meaning, Scope and Development of Anthropology',
    paper: 1,
    section: 'Foundations of Anthropology',
    topic: 1,
    description: 'Meaning and scope of anthropology, its development as a discipline, relationships with other disciplines — social sciences, behavioral sciences, life sciences, medical sciences, earth sciences',
    subtopics: ['Meaning & Scope', 'Development as a Discipline', 'Relationship with Social Sciences', 'Relationship with Life & Medical Sciences', 'Relationship with Earth Sciences'],
  },
  {
    slug: 'branches-of-anthropology',
    title: 'Main Branches of Anthropology',
    paper: 1,
    section: 'Foundations of Anthropology',
    topic: 2,
    description: 'Physical / Biological Anthropology, Social / Cultural Anthropology, Archaeological Anthropology, and Linguistic Anthropology — scope and interrelations',
    subtopics: ['Physical & Biological Anthropology', 'Social & Cultural Anthropology', 'Archaeological Anthropology', 'Linguistic Anthropology'],
  },
  {
    slug: 'human-evolution',
    title: 'Human Evolution and Emergence of Man',
    paper: 1,
    section: 'Physical Anthropology',
    topic: 3,
    description: 'Organic evolution, theories of evolution — Lamarckism, Darwinism, Synthetic Theory; palaeontological evidence; evolutionary history of primates; Australopithecines; Homo erectus; archaic and anatomically modern Homo sapiens',
    subtopics: ['Organic Evolution — Theories', 'Palaeontological Evidence', 'Order Primates', 'Hominid Evolution', 'Australopithecines', 'Homo Erectus', 'Archaic Homo Sapiens', 'Anatomically Modern Homo Sapiens'],
  },
  {
    slug: 'biological-basis-of-life',
    title: 'Biological Basis of Life',
    paper: 1,
    section: 'Physical Anthropology',
    topic: 4,
    description: 'Cell, DNA, RNA, protein synthesis, genetic code; Mendelian genetics, chromosomal theory of heredity, sex determination, linkage, crossing over, gene mutation',
    subtopics: ['Cell Structure & Function', 'DNA, RNA & Protein Synthesis', 'Genetic Code', 'Mendelian Genetics', 'Chromosomal Theory of Heredity', 'Sex Determination', 'Linkage & Crossing Over', 'Gene Mutation'],
  },
  {
    slug: 'human-genetics',
    title: 'Human Genetics',
    paper: 1,
    section: 'Physical Anthropology',
    topic: 5,
    description: 'Methods of human genetics — pedigree, twin, cytogenetic, biochemical; genetics of ABO, Rh blood groups; HLA system; eugenics and euphenics; population genetics — Hardy-Weinberg equilibrium; consanguinity; genetic disorders — chromosomal and Mendelian',
    subtopics: ['Methods of Study', 'Pedigree & Twin Studies', 'ABO & Rh Blood Groups', 'HLA System', 'Hardy-Weinberg Equilibrium', 'Population Genetics', 'Consanguinity', 'Eugenics & Euphenics', 'Chromosomal Disorders', 'Mendelian Disorders'],
  },
  {
    slug: 'concept-of-race',
    title: 'Concept of Race and Racism',
    paper: 1,
    section: 'Physical Anthropology',
    topic: 6,
    description: 'Biological basis of racial classifications; typological vs population concept of race; racism and its critique; racial elements in Indian population — racial affinities',
    subtopics: ['Race — Biological Basis & Classification', 'Typological vs Population Concept', 'Racism & Scientific Critique', 'Racial Affinities in India'],
  },
  {
    slug: 'human-growth-development',
    title: 'Concept of Human Growth and Development',
    paper: 1,
    section: 'Physical Anthropology',
    topic: 7,
    description: 'Stages of growth — infancy, childhood, adolescence, adulthood; factors influencing growth — genetic, hormonal, environmental, nutritional; concept of secular trend; relevance of menarche, menopause and other bioevents to fertility patterns',
    subtopics: ['Stages of Growth', 'Factors Influencing Growth', 'Secular Trend', 'Menarche, Menopause & Bioevents', 'Fertility Patterns & Differentials'],
  },
  {
    slug: 'applicability-of-biosocial-perspectives',
    title: 'Applicability of Biosocial Perspectives',
    paper: 1,
    section: 'Physical Anthropology',
    topic: 8,
    description: 'Epidemiological anthropology — disease patterns, nutritional anthropology, occupational health and ergonomics, bioarchaeology, forensic anthropology',
    subtopics: ['Epidemiological Anthropology', 'Nutritional Anthropology', 'Forensic Anthropology', 'Bioarchaeology', 'Ergonomics & Occupational Health'],
  },
  {
    slug: 'principles-prehistoric-archaeology',
    title: 'Principles of Prehistoric Archaeology',
    paper: 1,
    section: 'Archaeological Anthropology',
    topic: 9,
    description: 'Objectives and principles of prehistoric archaeology; typology of stone tools; chronology — relative and absolute dating methods; archaeological excavation techniques; cultural stratigraphy',
    subtopics: ['Objectives & Principles', 'Stone Tool Typology', 'Relative Dating Methods', 'Absolute Dating Methods (C-14, K-Ar, TL)', 'Excavation Techniques', 'Cultural Stratigraphy'],
  },
  {
    slug: 'cultural-evolution-prehistoric-cultures',
    title: 'Cultural Evolution and Prehistoric Cultures',
    paper: 1,
    section: 'Archaeological Anthropology',
    topic: 10,
    description: 'Palaeolithic (Lower, Middle, Upper), Mesolithic, Neolithic, Chalcolithic, Bronze Age and Iron Age cultures — subsistence patterns, tools, social organization and emergence of food production',
    subtopics: ['Lower Palaeolithic Culture', 'Middle Palaeolithic Culture', 'Upper Palaeolithic Culture', 'Mesolithic Culture', 'Neolithic Culture', 'Chalcolithic & Bronze Age', 'Iron Age & Emergence of Civilisation'],
  },
  {
    slug: 'nature-of-culture',
    title: 'Nature of Culture',
    paper: 1,
    section: 'Socio-Cultural Anthropology',
    topic: 11,
    description: 'Concept, definitions, characteristics of culture; culture and civilization; material and non-material culture; cultural relativism and ethnocentrism; enculturation and acculturation; nature–culture debate',
    subtopics: ['Concept & Definitions of Culture', 'Culture vs Civilization', 'Material & Non-Material Culture', 'Cultural Relativism & Ethnocentrism', 'Enculturation & Acculturation', 'Nature–Culture Debate'],
  },
  {
    slug: 'nature-of-society',
    title: 'Nature of Society',
    paper: 1,
    section: 'Socio-Cultural Anthropology',
    topic: 12,
    description: 'Concept of society and social structure; community and association; norms and institutions; concepts of role, status and social group; types of societies — band, tribe, chiefdom, state',
    subtopics: ['Society & Social Structure', 'Community & Association', 'Norms & Institutions', 'Role, Status & Social Groups', 'Band, Tribe, Chiefdom & State'],
  },
  {
    slug: 'marriage-family-kinship',
    title: 'Marriage, Family and Kinship',
    paper: 1,
    section: 'Socio-Cultural Anthropology',
    topic: 13,
    description: 'Definitions and functions of marriage; rules of marriage — endogamy, exogamy, preferential mating; forms of marriage; family — types, functions, evolution; household; kinship — consanguinity and affinity, descent theories, kinship terminology',
    subtopics: ['Marriage — Definition & Functions', 'Rules & Forms of Marriage', 'Family — Types & Functions', 'Evolution of Family', 'Kinship — Consanguinity & Affinity', 'Descent Theories', 'Kinship Terminology Systems', 'Joking & Avoidance Relationships'],
  },
  {
    slug: 'economic-organization',
    title: 'Economic Organization',
    paper: 1,
    section: 'Socio-Cultural Anthropology',
    topic: 14,
    description: 'Meaning of economic anthropology; subsistence economies; production, distribution and exchange — reciprocity, redistribution, market; formalism and substantivism debate; gift economy; food foraging to food production',
    subtopics: ['Meaning of Economic Anthropology', 'Subsistence Economies', 'Production, Distribution & Exchange', 'Reciprocity, Redistribution & Market', 'Formalism vs Substantivism', 'Gift Economy'],
  },
  {
    slug: 'political-organization-social-control',
    title: 'Political Organization and Social Control',
    paper: 1,
    section: 'Socio-Cultural Anthropology',
    topic: 15,
    description: 'Concepts of power, authority and legitimacy; band, tribal, chiefdom and state level organizations; political anthropology; social control — formal and informal; law and legal anthropology; conflict resolution',
    subtopics: ['Power, Authority & Legitimacy', 'Band & Tribal Political Organization', 'Chiefdom & State Level Organization', 'Political Anthropology', 'Social Control — Formal & Informal', 'Law & Legal Anthropology', 'Conflict Resolution'],
  },
  {
    slug: 'religion',
    title: 'Religion',
    paper: 1,
    section: 'Socio-Cultural Anthropology',
    topic: 16,
    description: 'Anthropological approaches to religion — animism, animatism, totemism; myth and ritual; magic, religion and science; shamanism; ancestors and spirit worship; world religions and local traditions; sacred and profane',
    subtopics: ['Animism, Animatism & Totemism', 'Myth & Ritual', 'Magic, Religion & Science', 'Shamanism & Spirit Possession', 'Ancestor Worship', 'Sacred & Profane', 'Anthropological Theories of Religion'],
  },
  {
    slug: 'anthropological-theories',
    title: 'Anthropological Theories',
    paper: 1,
    section: 'Socio-Cultural Anthropology',
    topic: 17,
    description: 'Classical evolutionism — Tylor, Morgan; diffusionism — British, German; historical particularism — Boas; functionalism — Malinowski; structural-functionalism — Radcliffe-Brown; culture and personality school; neo-evolutionism; structuralism — Lévi-Strauss; symbolic and interpretive anthropology; post-modernism in anthropology',
    subtopics: ['Classical Evolutionism (Tylor, Morgan)', 'Diffusionism', 'Historical Particularism (Boas)', 'Functionalism (Malinowski)', 'Structural-Functionalism (Radcliffe-Brown)', 'Culture & Personality School', 'Neo-Evolutionism', 'Structuralism (Lévi-Strauss)', 'Symbolic & Interpretive Anthropology', 'Post-Modernism in Anthropology'],
  },
  {
    slug: 'culture-language-communication',
    title: 'Culture, Language and Communication',
    paper: 1,
    section: 'Socio-Cultural Anthropology',
    topic: 18,
    description: 'Language and culture — Sapir-Whorf hypothesis; origins of language; linguistic anthropology; non-verbal communication; ethnolinguistics; sociolinguistics; language and cognition',
    subtopics: ['Language & Culture', 'Sapir-Whorf Hypothesis', 'Origins of Language', 'Non-Verbal Communication', 'Ethnolinguistics & Sociolinguistics', 'Language & Cognition'],
  },
  {
    slug: 'research-methods-anthropology',
    title: 'Research Methods in Anthropology',
    paper: 1,
    section: 'Methods',
    topic: 19,
    description: 'Fieldwork tradition; participant observation; ethnographic methods; qualitative vs quantitative methods; genealogical method; interview techniques; case study; PRA; reflexivity and ethics in fieldwork',
    subtopics: ['Fieldwork Tradition in Anthropology', 'Participant Observation', 'Ethnographic Methods', 'Genealogical Method', 'Interview & Case Study Methods', 'PRA & Rapid Assessment', 'Reflexivity & Ethics in Fieldwork'],
  },
  {
    slug: 'applications-of-anthropology',
    title: 'Applications of Anthropology',
    paper: 1,
    section: 'Methods',
    topic: 20,
    description: 'Applied anthropology — scope and relevance; development anthropology; medical anthropology; nutritional anthropology; forensic anthropology; urban anthropology; disaster anthropology; advocacy and action anthropology',
    subtopics: ['Applied Anthropology — Scope & History', 'Development Anthropology', 'Medical Anthropology', 'Nutritional Anthropology', 'Forensic Anthropology', 'Urban Anthropology', 'Disaster & Action Anthropology'],
  },
];

// ── Paper II — Indian Anthropology ───────────────────────────

export const paper2Notes: AnthroNote[] = [
  {
    slug: 'evolution-indian-culture-civilization',
    title: 'Evolution of Indian Culture and Civilization',
    paper: 2,
    section: 'Indian Prehistory & Archaeology',
    topic: 1,
    description: 'Prehistoric periods — Palaeolithic, Mesolithic, Neolithic, Neolithic-Chalcolithic; Protohistoric: pre-Harappan, Harappan and post-Harappan cultures; contributions of tribal cultures to Indian civilization',
    subtopics: ['Palaeolithic India', 'Mesolithic India', 'Neolithic & Neolithic-Chalcolithic', 'Pre-Harappan Cultures', 'Harappan Civilization', 'Post-Harappan Cultures', 'Tribal Contributions to Indian Civilization'],
  },
  {
    slug: 'palaeo-anthropological-evidence-india',
    title: 'Palaeo-Anthropological Evidence in India',
    paper: 2,
    section: 'Indian Prehistory & Archaeology',
    topic: 2,
    description: 'Fossil evidence from India — Siwaliks and Narmada basin; Ramapithecus, Sivapithecus and Narmada Man; significance of Indian fossil record in hominid evolution',
    subtopics: ['Siwalik Fossil Record', 'Ramapithecus & Sivapithecus', 'Narmada Man (Homo narmadensis)', 'Significance for Hominid Evolution'],
  },
  {
    slug: 'ethnoarchaeology-india',
    title: 'Ethno-Archaeology in India',
    paper: 2,
    section: 'Indian Prehistory & Archaeology',
    topic: 3,
    description: 'Concept of ethnoarchaeology; survivals and parallels among hunting, foraging, fishing, pastoral and peasant communities; arts and crafts producing communities; living cultures as analogues for archaeological interpretation',
    subtopics: ['Concept of Ethnoarchaeology', 'Hunter-Gatherer Survivals', 'Pastoral & Peasant Communities', 'Arts & Crafts Communities', 'Living Analogy in Archaeology'],
  },
  {
    slug: 'demographic-profile-india',
    title: 'Demographic Profile of India',
    paper: 2,
    section: 'Indian Society & Social Structure',
    topic: 4,
    description: 'Ethnic and linguistic elements of Indian population and their distribution; factors influencing structure and growth of Indian population; census data and demographic trends',
    subtopics: ['Ethnic Elements & Distribution', 'Linguistic Elements & Distribution', 'Factors Influencing Population Structure', 'Population Growth Trends', 'Census Data & Demography'],
  },
  {
    slug: 'traditional-indian-social-system',
    title: 'Traditional Indian Social System',
    paper: 2,
    section: 'Indian Society & Social Structure',
    topic: 5,
    description: 'Varnashrama, purushartha, karma, rina and rebirth; ideology and structure of the traditional social system; inter-relationship among varna, ashrama and purushartha',
    subtopics: ['Varna & Ashrama System', 'Purushartha — Four Aims of Life', 'Karma, Rina & Rebirth', 'Ideology of Traditional Social Order'],
  },
  {
    slug: 'caste-system-india',
    title: 'Caste System in India',
    paper: 2,
    section: 'Indian Society & Social Structure',
    topic: 6,
    description: 'Structure and characteristics of caste; varna and caste; theories of origin of caste; dominant caste; caste mobility; future of caste; jajmani system; tribe-caste continuum',
    subtopics: ['Structure & Characteristics of Caste', 'Varna & Caste', 'Theories of Origin of Caste', 'Dominant Caste', 'Caste Mobility', 'Future of Caste System', 'Jajmani System', 'Tribe-Caste Continuum'],
  },
  {
    slug: 'sacred-complex-nature-man-spirit',
    title: 'Sacred Complex, Nature-Man-Spirit Complex',
    paper: 2,
    section: 'Indian Society & Social Structure',
    topic: 7,
    description: 'Sacred complex in India; nature-man-spirit complex; impact of Buddhism, Jainism, Islam and Christianity on Indian society; little and great traditions; religious syncretism',
    subtopics: ['Sacred Complex in India', 'Nature-Man-Spirit Complex', 'Impact of Buddhism & Jainism', 'Impact of Islam & Christianity', 'Little & Great Traditions', 'Religious Syncretism'],
  },
  {
    slug: 'emergence-growth-anthropology-india',
    title: 'Emergence and Growth of Anthropology in India',
    paper: 2,
    section: 'Indian Society & Social Structure',
    topic: 8,
    description: 'Contributions of 18th, 19th and early 20th century scholar-administrators; contributions of Indian anthropologists to tribal and caste studies; development of anthropology as an academic discipline in India',
    subtopics: ['18th–19th Century Scholar-Administrators', 'Early 20th Century Contributions', 'Indian Anthropologists & Tribal Studies', 'Indian Anthropologists & Caste Studies', 'Anthropology as Academic Discipline in India'],
  },
  {
    slug: 'indian-village',
    title: 'Indian Village',
    paper: 2,
    section: 'Indian Society & Social Structure',
    topic: 9,
    description: 'Significance of village study in India; Indian village as a social system; traditional and changing patterns of settlement and inter-caste relations; agrarian relations; impact of globalization on Indian villages',
    subtopics: ['Significance of Village Study', 'Indian Village as Social System', 'Settlement & Inter-Caste Relations', 'Agrarian Relations in Villages', 'Globalization & Indian Villages'],
  },
  {
    slug: 'linguistic-religious-minorities',
    title: 'Linguistic and Religious Minorities',
    paper: 2,
    section: 'Indian Society & Social Structure',
    topic: 10,
    description: 'Linguistic and religious minorities in India — their social, political and economic status; constitutional provisions; minority rights and issues',
    subtopics: ['Linguistic Minorities in India', 'Religious Minorities in India', 'Social & Economic Status of Minorities', 'Constitutional Provisions for Minorities', 'Minority Rights & Issues'],
  },
  {
    slug: 'socio-cultural-change-india',
    title: 'Indigenous and Exogenous Processes of Socio-Cultural Change',
    paper: 2,
    section: 'Indian Society & Social Structure',
    topic: 11,
    description: 'Sanskritization, Westernization and Modernization; inter-play of little and great traditions; Panchayati Raj and social change; media and social change',
    subtopics: ['Sanskritization', 'Westernization & Modernization', 'Little & Great Traditions Interplay', 'Panchayati Raj & Social Change', 'Media & Social Change'],
  },
  {
    slug: 'tribal-situation-india',
    title: 'The Tribal Situation in India',
    paper: 2,
    section: 'Tribal India',
    topic: 12,
    description: 'Bio-genetic variability; linguistic and socio-economic characteristics of tribal populations and their distribution; scheduled tribes — geographical spread and demographic profile',
    subtopics: ['Bio-Genetic Variability of Tribes', 'Linguistic Characteristics', 'Socio-Economic Characteristics', 'Tribal Distribution in India', 'Demographic Profile of Scheduled Tribes'],
  },
  {
    slug: 'problems-tribal-communities',
    title: 'Problems of Tribal Communities',
    paper: 2,
    section: 'Tribal India',
    topic: 13,
    description: 'Land alienation, poverty, indebtedness, low literacy, poor educational facilities, unemployment and underemployment, health and nutrition issues facing tribal communities',
    subtopics: ['Land Alienation', 'Poverty & Indebtedness', 'Literacy & Education Deficits', 'Unemployment & Underemployment', 'Health & Nutritional Problems'],
  },
  {
    slug: 'developmental-projects-tribal-displacement',
    title: 'Developmental Projects and Tribal Displacement',
    paper: 2,
    section: 'Tribal India',
    topic: 14,
    description: 'Impact of developmental projects on tribal displacement; problems of rehabilitation; forest policy and tribals; impact of urbanization and industrialization on tribal populations',
    subtopics: ['Impact of Development Projects', 'Tribal Displacement & Rehabilitation', 'Forest Policy & Tribal Rights', 'Urbanization & Industrialization Effects'],
  },
  {
    slug: 'scheduled-castes-tribes-obcs',
    title: 'Problems of SC, ST and OBC',
    paper: 2,
    section: 'Tribal India',
    topic: 15,
    description: 'Exploitation and deprivation of Scheduled Castes, Scheduled Tribes and Other Backward Classes; constitutional safeguards; affirmative action and reservations; social justice framework',
    subtopics: ['Exploitation of Scheduled Castes', 'Exploitation of Scheduled Tribes', 'OBC Issues & Challenges', 'Constitutional Safeguards for SC & ST', 'Affirmative Action & Reservations'],
  },
  {
    slug: 'social-change-tribal-societies',
    title: 'Social Change and Contemporary Tribal Societies',
    paper: 2,
    section: 'Tribal India',
    topic: 16,
    description: 'Impact of modern democratic institutions, development programs and welfare measures on tribals and weaker sections; continuity and change in tribal societies',
    subtopics: ['Impact of Democratic Institutions', 'Development Programs & Welfare Measures', 'Continuity & Change in Tribal Societies', 'Tribal Identity in Contemporary India'],
  },
  {
    slug: 'ethnicity-ethnic-conflicts',
    title: 'Concept of Ethnicity and Ethnic Conflicts',
    paper: 2,
    section: 'Tribal India',
    topic: 17,
    description: 'Concept of ethnicity; ethnic conflicts and political developments; unrest among tribal communities; regionalism and demand for autonomy; pseudo-tribalism; social change among tribes during colonial and post-independent India',
    subtopics: ['Concept of Ethnicity', 'Ethnic Conflicts & Political Developments', 'Tribal Unrest & Regionalism', 'Demand for Autonomy', 'Pseudo-Tribalism', 'Colonial & Post-Independent Tribal Change'],
  },
  {
    slug: 'religion-tribal-societies',
    title: 'Impact of World Religions on Tribal Societies',
    paper: 2,
    section: 'Tribal India',
    topic: 18,
    description: 'Impact of Hinduism, Buddhism, Christianity, Islam and other religions on tribal societies; religious change and tribal identity; syncretic traditions',
    subtopics: ['Impact of Hinduism on Tribals', 'Impact of Christianity on Tribals', 'Impact of Islam & Buddhism', 'Religious Change & Tribal Identity', 'Syncretic Traditions'],
  },
  {
    slug: 'tribe-and-nation-state',
    title: 'Tribe and Nation-State',
    paper: 2,
    section: 'Tribal India',
    topic: 19,
    description: 'Comparative study of tribal communities in India and other countries; tribal integration and assimilation vs autonomy; Fourth World movements; indigenous rights globally',
    subtopics: ['Tribes in India — Integration vs Autonomy', 'Comparative Tribal Studies (World)', 'Fourth World Movements', 'Indigenous Rights Globally'],
  },
  {
    slug: 'administration-tribal-areas',
    title: 'Administration of Tribal Areas and Tribal Policies',
    paper: 2,
    section: 'Tribal India',
    topic: 20,
    description: 'History of administration of tribal areas; tribal policies and development plans; concept of PTGs (Particularly Vulnerable Tribal Groups) — distribution and special programs; role of NGOs in tribal development',
    subtopics: ['History of Tribal Administration', 'Tribal Policies & Development Plans', 'PTGs — Concept, Distribution & Programs', 'Role of NGOs in Tribal Development', 'Fifth & Sixth Schedules'],
  },
  {
    slug: 'role-of-anthropology-development',
    title: 'Role of Anthropology in Tribal and Rural Development',
    paper: 2,
    section: 'Tribal India',
    topic: 21,
    description: 'Applied anthropology in tribal and rural development; contributions of anthropology to understanding regionalism, communalism, ethnic and political movements; anthropology and policy-making',
    subtopics: ['Applied Anthropology in Tribal Development', 'Applied Anthropology in Rural Development', 'Anthropology & Regionalism', 'Anthropology & Communalism', 'Anthropology & Ethnic Movements', 'Anthropology & Policy-Making'],
  },
];

export const allAnthroNotes: AnthroNote[] = [...paper1Notes, ...paper2Notes];

export function getAnthroNoteBySlug(slug: string): AnthroNote | undefined {
  return allAnthroNotes.find((n) => n.slug === slug);
}

export const paper1Sections = [
  'Foundations of Anthropology',
  'Physical Anthropology',
  'Archaeological Anthropology',
  'Socio-Cultural Anthropology',
  'Methods',
];

export const paper2Sections = [
  'Indian Prehistory & Archaeology',
  'Indian Society & Social Structure',
  'Tribal India',
];
