export type PolsciNote = {
  slug: string;
  title: string;
  paper: 1 | 2;
  section: string;
  topic: number;
  subtopics?: string[];
  description: string;
};

// ── Paper I — Political Theory & Indian Government ───────────

export const paper1Notes: PolsciNote[] = [
  // Section A: Political Theory
  {
    slug: 'political-theory-meaning-approaches',
    title: 'Political Theory: Meaning and Approaches',
    paper: 1,
    section: 'Political Theory',
    topic: 1,
    description: 'Nature and scope of political theory, traditional vs modern approaches, normative and empirical traditions',
    subtopics: ['Nature & Scope', 'Traditional Approach', 'Behavioural Approach', 'Post-Behavioural Approach', 'Normative vs Empirical'],
  },
  {
    slug: 'theories-of-state',
    title: 'Theories of the State',
    paper: 1,
    section: 'Political Theory',
    topic: 2,
    description: 'Liberal, Neo-liberal, Marxist, Pluralist, Post-colonial and Feminist theories of the state',
    subtopics: ['Liberal State', 'Neo-liberal State', 'Marxist Theory', 'Pluralist State', 'Post-colonial Critique', 'Feminist Theory of State'],
  },
  {
    slug: 'justice',
    title: 'Justice',
    paper: 1,
    section: 'Political Theory',
    topic: 3,
    description: 'Conceptions of justice — Rawls\' theory of justice as fairness, veil of ignorance, difference principle, communitarian critiques',
    subtopics: ['Conceptions of Justice', 'Rawls — Theory of Justice', 'Veil of Ignorance & Original Position', 'Difference Principle', 'Communitarian Critiques (Sandel, Walzer, MacIntyre)'],
  },
  {
    slug: 'equality',
    title: 'Equality',
    paper: 1,
    section: 'Political Theory',
    topic: 4,
    description: 'Social, political and economic equality; relationship between equality and freedom; affirmative action',
    subtopics: ['Social Equality', 'Political Equality', 'Economic Equality', 'Equality vs Freedom', 'Affirmative Action'],
  },
  {
    slug: 'rights',
    title: 'Rights',
    paper: 1,
    section: 'Political Theory',
    topic: 5,
    description: 'Meaning and theories of rights, natural rights, legal rights, moral rights, concept of human rights',
    subtopics: ['Meaning & Theories of Rights', 'Natural Rights', 'Legal & Moral Rights', 'Human Rights', 'Rights vs Duties'],
  },
  {
    slug: 'democracy',
    title: 'Democracy',
    paper: 1,
    section: 'Political Theory',
    topic: 6,
    description: 'Classical and contemporary theories of democracy; models — representative, participatory and deliberative democracy',
    subtopics: ['Classical Theory', 'Elitist Theory', 'Pluralist Theory', 'Representative Democracy', 'Participatory Democracy', 'Deliberative Democracy'],
  },
  {
    slug: 'power-hegemony-ideology',
    title: 'Power, Hegemony and Ideology',
    paper: 1,
    section: 'Political Theory',
    topic: 7,
    description: 'Concept of power, Dahl vs Lukes, Gramsci\'s hegemony, ideology as legitimation, false consciousness',
    subtopics: ['Concept of Power', 'Dahl — Pluralist Power', 'Lukes — Three Faces of Power', 'Gramsci\'s Hegemony', 'Ideology & Legitimacy'],
  },
  {
    slug: 'political-ideologies',
    title: 'Political Ideologies',
    paper: 1,
    section: 'Political Theory',
    topic: 8,
    description: 'Liberalism, Socialism, Marxism, Fascism, Gandhism and Feminism as political ideologies',
    subtopics: ['Liberalism & Neo-liberalism', 'Socialism & Social Democracy', 'Marxism', 'Fascism', 'Gandhism', 'Feminism'],
  },
  {
    slug: 'indian-political-thought',
    title: 'Indian Political Thought',
    paper: 1,
    section: 'Political Theory',
    topic: 9,
    description: 'Dharmashastra, Arthashastra, Buddhist traditions; Sir Syed Ahmed Khan, Sri Aurobindo, Gandhi, Ambedkar, M.N. Roy',
    subtopics: ['Dharmashastra & Arthashastra', 'Buddhist Political Thought', 'Sir Syed Ahmed Khan', 'Sri Aurobindo', 'M.K. Gandhi', 'B.R. Ambedkar', 'M.N. Roy'],
  },
  {
    slug: 'western-political-thought',
    title: 'Western Political Thought',
    paper: 1,
    section: 'Political Theory',
    topic: 10,
    description: 'Plato, Aristotle, Machiavelli, Hobbes, Locke, J.S. Mill, Marx, Gramsci, Hannah Arendt',
    subtopics: ['Plato', 'Aristotle', 'Machiavelli', 'Hobbes', 'Locke', 'J.S. Mill', 'Karl Marx', 'Gramsci', 'Hannah Arendt'],
  },
  // Section B: Indian Government and Politics
  {
    slug: 'indian-nationalism',
    title: 'Indian Nationalism',
    paper: 1,
    section: 'Indian Government and Politics',
    topic: 11,
    description: 'Political strategies of India\'s freedom struggle: constitutionalism, mass satyagraha, non-cooperation, civil disobedience, militant movements; liberal, socialist, Marxist, Dalit perspectives',
    subtopics: ['Constitutionalism to Mass Satyagraha', 'Non-Cooperation Movement', 'Civil Disobedience', 'Militant & Revolutionary Movements', 'Peasant & Workers Movements', 'Liberal / Socialist / Dalit Perspectives'],
  },
  {
    slug: 'making-of-indian-constitution',
    title: 'Making of the Indian Constitution',
    paper: 1,
    section: 'Indian Government and Politics',
    topic: 12,
    description: 'Legacies of British rule, Constituent Assembly debates, different social and political perspectives in constitution-making',
    subtopics: ['British Colonial Legacy', 'Constituent Assembly', 'Key Debates & Compromises', 'Social & Political Perspectives'],
  },
  {
    slug: 'salient-features-indian-constitution',
    title: 'Salient Features of the Indian Constitution',
    paper: 1,
    section: 'Indian Government and Politics',
    topic: 13,
    description: 'Preamble, Fundamental Rights and Duties, Directive Principles, parliamentary system, amendment procedures, judicial review, basic structure doctrine',
    subtopics: ['Preamble', 'Fundamental Rights & Duties', 'Directive Principles', 'Parliamentary System', 'Amendment Procedures', 'Judicial Review & Basic Structure'],
  },
  {
    slug: 'principal-organs-union-state',
    title: 'Principal Organs of Union & State Governments',
    paper: 1,
    section: 'Indian Government and Politics',
    topic: 14,
    description: 'Envisaged role and actual working of the Executive, Legislature, Supreme Court; and State-level Executive, Legislature, High Courts',
    subtopics: ['Union Executive', 'Parliament', 'Supreme Court', 'State Executive', 'State Legislature', 'High Courts'],
  },
  {
    slug: 'grassroots-democracy',
    title: 'Grassroots Democracy',
    paper: 1,
    section: 'Indian Government and Politics',
    topic: 15,
    description: 'Panchayati Raj and Municipal Government, significance of 73rd and 74th Amendments, grassroots movements',
    subtopics: ['Panchayati Raj', 'Municipal Governance', '73rd & 74th Amendments', 'Grassroots Movements', 'Women\'s Reservation in Local Bodies'],
  },
  {
    slug: 'statutory-commissions',
    title: 'Statutory Institutions and Commissions',
    paper: 1,
    section: 'Indian Government and Politics',
    topic: 16,
    description: 'Election Commission, CAG, Finance Commission, UPSC, NCSC, NCST, NCW, NHRC, NCM, NCBC',
    subtopics: ['Election Commission', 'CAG', 'Finance Commission', 'UPSC', 'NCSC & NCST', 'NCW & NHRC', 'NCM & NCBC'],
  },
  {
    slug: 'federalism',
    title: 'Federalism',
    paper: 1,
    section: 'Indian Government and Politics',
    topic: 17,
    description: 'Constitutional provisions, changing nature of centre-state relations, integrationist tendencies, regional aspirations, inter-state disputes',
    subtopics: ['Constitutional Provisions', 'Centre-State Relations', 'Cooperative vs Competitive Federalism', 'Regional Aspirations', 'Inter-state Disputes'],
  },
  {
    slug: 'planning-economic-development',
    title: 'Planning and Economic Development',
    paper: 1,
    section: 'Indian Government and Politics',
    topic: 18,
    description: 'Nehruvian and Gandhian perspectives, role of planning and public sector, green revolution, land reforms, liberalisation and economic reforms',
    subtopics: ['Nehruvian Socialism', 'Gandhian Economic Thought', 'Five-Year Plans', 'Green Revolution & Land Reforms', 'LPG Reforms 1991'],
  },
  {
    slug: 'caste-religion-ethnicity',
    title: 'Caste, Religion and Ethnicity in Indian Politics',
    paper: 1,
    section: 'Indian Government and Politics',
    topic: 19,
    description: 'Role of caste, religion and ethnicity as political identities, communalism, reservations policy, minority rights',
    subtopics: ['Caste as Political Identity', 'Religion & Communalism', 'Ethnicity & Regional Identity', 'Reservations Policy', 'Minority Rights'],
  },
  {
    slug: 'party-system',
    title: 'Party System',
    paper: 1,
    section: 'Indian Government and Politics',
    topic: 20,
    description: 'National and regional parties, ideological and social bases, coalition politics, pressure groups, electoral behaviour, changing profile of legislators',
    subtopics: ['National Political Parties', 'Regional Parties', 'Coalition Politics', 'Pressure Groups', 'Electoral Behaviour', 'Profile of Legislators'],
  },
  {
    slug: 'social-movements',
    title: 'Social Movements',
    paper: 1,
    section: 'Indian Government and Politics',
    topic: 21,
    description: 'Civil liberties and human rights movements, women\'s movements, environmentalist movements in India',
    subtopics: ['Civil Liberties Movements', 'Human Rights Movements', 'Women\'s Movements', 'Environmentalist Movements', 'Tribal & Dalit Movements'],
  },
];

// ── Paper II — Comparative Politics & International Relations ─

export const paper2Notes: PolsciNote[] = [
  // Section A: Comparative Political Analysis and International Politics
  {
    slug: 'comparative-politics',
    title: 'Comparative Politics',
    paper: 2,
    section: 'Comparative Political Analysis and International Politics',
    topic: 1,
    description: 'Nature and major approaches to comparative politics, political economy and political sociology perspectives, limitations of comparative method',
    subtopics: ['Nature of Comparative Politics', 'Traditional & Modern Approaches', 'Political Economy Perspective', 'Political Sociology Perspective', 'Limitations of Comparative Method'],
  },
  {
    slug: 'state-in-comparative-perspective',
    title: 'State in Comparative Perspective',
    paper: 2,
    section: 'Comparative Political Analysis and International Politics',
    topic: 2,
    description: 'Characteristics and changing nature of the state in capitalist and socialist economies; advanced industrial and developing societies',
    subtopics: ['State in Capitalist Economies', 'State in Socialist Economies', 'Welfare State', 'State in Developing Societies', 'Changing Nature of the State'],
  },
  {
    slug: 'politics-of-representation',
    title: 'Politics of Representation and Participation',
    paper: 2,
    section: 'Comparative Political Analysis and International Politics',
    topic: 3,
    description: 'Political parties, pressure groups and social movements in advanced industrial and developing societies',
    subtopics: ['Political Parties (Comparative)', 'Pressure Groups', 'Social Movements', 'Advanced Industrial vs Developing Societies'],
  },
  {
    slug: 'globalisation-responses',
    title: 'Globalisation',
    paper: 2,
    section: 'Comparative Political Analysis and International Politics',
    topic: 4,
    description: 'Globalisation and its political dimensions; responses from developed and developing societies',
    subtopics: ['Nature of Globalisation', 'Economic Globalisation', 'Political Dimensions', 'Responses of Developed Nations', 'Responses of Developing Nations', 'Anti-Globalisation Movements'],
  },
  {
    slug: 'approaches-to-ir',
    title: 'Approaches to International Relations',
    paper: 2,
    section: 'Comparative Political Analysis and International Politics',
    topic: 5,
    description: 'Idealist, Realist, Marxist, Functionalist and Systems theory approaches to the study of International Relations',
    subtopics: ['Idealism / Liberalism', 'Realism (Classical & Neo)', 'Marxist Approach', 'Functionalism & Neo-functionalism', 'Systems Theory'],
  },
  {
    slug: 'key-concepts-ir',
    title: 'Key Concepts in International Relations',
    paper: 2,
    section: 'Comparative Political Analysis and International Politics',
    topic: 6,
    description: 'National interest, security, power, balance of power, deterrence, transnational actors, collective security, world capitalist economy, globalisation',
    subtopics: ['National Interest', 'Power in IR', 'Balance of Power', 'Deterrence & Nuclear Strategy', 'Transnational Actors', 'Collective Security', 'World Capitalist Economy'],
  },
  {
    slug: 'changing-international-political-order',
    title: 'Changing International Political Order',
    paper: 2,
    section: 'Comparative Political Analysis and International Politics',
    topic: 7,
    description: 'Rise of superpowers, Cold War bipolarity, Non-Aligned Movement, collapse of USSR, American unipolarity, post-cold war world order',
    subtopics: ['Rise of Superpowers', 'Cold War & Bipolarity', 'Arms Race & Nuclear Threat', 'Non-Aligned Movement', 'Collapse of USSR', 'American Unipolarity', 'Post-Unipolar World'],
  },
  {
    slug: 'international-economic-system',
    title: 'Evolution of the International Economic System',
    paper: 2,
    section: 'Comparative Political Analysis and International Politics',
    topic: 8,
    description: 'Bretton Woods to WTO, socialist economies and CMEA, Third World demand for NIEO, globalisation of world economy',
    subtopics: ['Bretton Woods System', 'GATT to WTO', 'Socialist Economies & CMEA', 'NIEO Demand', 'Globalisation of World Economy'],
  },
  {
    slug: 'united-nations',
    title: 'United Nations',
    paper: 2,
    section: 'Comparative Political Analysis and International Politics',
    topic: 9,
    description: 'Envisaged role and actual record of the UN, specialized agencies, need for UN reforms, Security Council expansion',
    subtopics: ['UN Charter & Structure', 'Security Council', 'General Assembly', 'Specialized Agencies', 'UN Peace-keeping', 'Need for UN Reforms'],
  },
  {
    slug: 'regionalisation-world-politics',
    title: 'Regionalisation of World Politics',
    paper: 2,
    section: 'Comparative Political Analysis and International Politics',
    topic: 10,
    description: 'EU, ASEAN, APEC, SAARC, NAFTA — regional organisations and their role in international politics',
    subtopics: ['European Union', 'ASEAN', 'APEC', 'SAARC', 'NAFTA / USMCA', 'Regionalism vs Globalisation'],
  },
  {
    slug: 'contemporary-global-concerns',
    title: 'Contemporary Global Concerns',
    paper: 2,
    section: 'Comparative Political Analysis and International Politics',
    topic: 11,
    description: 'Democracy, human rights, environment, gender justice, terrorism, nuclear proliferation as global concerns',
    subtopics: ['Democracy Promotion', 'Human Rights', 'Environment & Climate Change', 'Gender Justice', 'Terrorism & Counter-terrorism', 'Nuclear Proliferation'],
  },
  // Section B: India and the World
  {
    slug: 'indian-foreign-policy',
    title: 'Indian Foreign Policy',
    paper: 2,
    section: 'India and the World',
    topic: 12,
    description: 'Determinants of Indian foreign policy, institutions of policy-making, continuity and change in India\'s foreign policy',
    subtopics: ['Determinants of Foreign Policy', 'Ministry of External Affairs', 'Role of Parliament & PM', 'Continuity & Change', 'Panchsheel & Non-Alignment'],
  },
  {
    slug: 'india-and-nam',
    title: 'India and the Non-Alignment Movement',
    paper: 2,
    section: 'India and the World',
    topic: 13,
    description: 'India\'s contribution to NAM, different phases, Nehru\'s role, current relevance of non-alignment',
    subtopics: ['Origins of NAM', 'Nehru\'s Role', 'Phases of India\'s Non-Alignment', 'NAM in Cold War', 'Relevance of NAM Today'],
  },
  {
    slug: 'india-and-south-asia',
    title: 'India and South Asia',
    paper: 2,
    section: 'India and the World',
    topic: 14,
    description: 'SAARC — performance and prospects, South Asia as free trade area, Look East policy, impediments to regional co-operation',
    subtopics: ['SAARC — Past & Future', 'South Asia Free Trade Area', 'Look East / Act East Policy', 'River Water Disputes', 'Cross-border Migration', 'Ethnic Conflicts & Border Disputes'],
  },
  {
    slug: 'india-and-global-south',
    title: 'India and the Global South',
    paper: 2,
    section: 'India and the World',
    topic: 15,
    description: 'India\'s relations with Africa and Latin America, leadership in NIEO demand, WTO negotiations and developing nations',
    subtopics: ['India-Africa Relations', 'India-Latin America', 'NIEO & India\'s Role', 'WTO & Developing Countries', 'South-South Cooperation'],
  },
  {
    slug: 'india-and-global-centres-of-power',
    title: 'India and the Global Centres of Power',
    paper: 2,
    section: 'India and the World',
    topic: 16,
    description: 'India\'s relations with USA, EU, Japan, China and Russia — bilateral and multilateral dimensions',
    subtopics: ['India-USA Relations', 'India-EU Relations', 'India-Japan Strategic Partnership', 'India-China Relations', 'India-Russia Relations', 'Multilateral Forums (QUAD, BRICS, SCO)'],
  },
  {
    slug: 'india-and-un-system',
    title: 'India and the UN System',
    paper: 2,
    section: 'India and the World',
    topic: 17,
    description: 'India\'s role in UN peace-keeping, demand for permanent seat in Security Council, India and UN agencies',
    subtopics: ['India in UN Peace-keeping', 'India & UNSC Permanent Seat', 'India & UN Agencies', 'India\'s UN Voting Record'],
  },
  {
    slug: 'india-nuclear-question',
    title: 'India and the Nuclear Question',
    paper: 2,
    section: 'India and the World',
    topic: 18,
    description: 'India\'s changing nuclear perceptions and policy, Pokhran tests, Indo-US nuclear deal, no-first-use doctrine',
    subtopics: ['Nuclear Policy Evolution', 'Pokhran I & II', 'No-First-Use Doctrine', 'Indo-US Nuclear Deal', 'Nuclear Non-Proliferation & India'],
  },
  {
    slug: 'recent-developments-indian-foreign-policy',
    title: 'Recent Developments in Indian Foreign Policy',
    paper: 2,
    section: 'India and the World',
    topic: 19,
    description: 'India\'s positions on Afghanistan, Iraq, West Asia; growing India-US and India-Israel relations; vision of a new world order',
    subtopics: ['India & Afghanistan', 'India\'s West Asia Policy', 'India-Israel Relations', 'New World Order & India', 'Neighbourhood First Policy'],
  },
];

export const allNotes: PolsciNote[] = [...paper1Notes, ...paper2Notes];

export const getNoteBySlug = (slug: string): PolsciNote | undefined =>
  allNotes.find(n => n.slug === slug);

export const paper1Sections = [
  'Political Theory',
  'Indian Government and Politics',
];

export const paper2Sections = [
  'Comparative Political Analysis and International Politics',
  'India and the World',
];
