// Geography Optional: UPSC PYQ map questions, 2013 to 2026
// Paper II, Q1(a): 10 places a year x 14 years = 140 entries, in the order the
// paper lists them. The places are checked against the official papers in
// public/data/geography-pyqs.json, and each pin against Wikipedia or Wikidata.
// A river, canal or highway is shown at one named point on it, given in its note.

export type GeoCategory =
  | 'Rivers & Water Bodies'
  | 'Mountains, Passes & Plateaus'
  | 'Wildlife & Biosphere'
  | 'Dams & Hydropower'
  | 'Defence & Strategic'
  | 'Ports & Coastal'
  | 'Nuclear & Space'
  | 'Islands & Union Territories'
  | 'Minerals & Industry'
  | 'Cultural & Heritage'
  | 'International & Border'
  | 'Transport & Connectivity';

export const GEO_CATEGORIES: GeoCategory[] = [
  'Rivers & Water Bodies',
  'Mountains, Passes & Plateaus',
  'Wildlife & Biosphere',
  'Dams & Hydropower',
  'Defence & Strategic',
  'Ports & Coastal',
  'Nuclear & Space',
  'Islands & Union Territories',
  'Minerals & Industry',
  'Cultural & Heritage',
  'International & Border',
  'Transport & Connectivity',
];

export interface GeoMapEntry {
  year: number;
  number: number;
  name: string;
  lat: number;
  lng: number;
  significance: string;
  category: GeoCategory;
}

export const geoMapData: GeoMapEntry[] = [
  // ── 2013 ──
  { year: 2013, number: 1,  name: "Mishmi Hills",                  lat: 28.7981,  lng: 95.9036,   category: "Mountains, Passes & Plateaus",  significance: "Hills at the north-eastern tip of Arunachal Pradesh, bordering Tibet. Drained by the Dibang and Lohit, they are a biodiversity hotspot and home of the Idu Mishmi people. Shown at Anini." },
  { year: 2013, number: 2,  name: "Lipulekh Pass",                 lat: 30.2329,  lng: 81.0285,   category: "International & Border",        significance: "Himalayan pass in Pithoragarh, Uttarakhand, on the India-China border near the tri-junction with Nepal. A route of the Kailash Mansarovar Yatra and of border trade with Tibet." },
  { year: 2013, number: 3,  name: "Beas River",                    lat: 31.7069,  lng: 76.9317,   category: "Rivers & Water Bodies",         significance: "Rises near the Rohtang Pass, flows through Kullu and Mandi and joins the Sutlej at Harike in Punjab. An Indus tributary dammed at Pandoh and Pong. Shown at Mandi." },
  { year: 2013, number: 4,  name: "Rihand Dam",                    lat: 24.2025,  lng: 83.0081,   category: "Dams & Hydropower",             significance: "Dam on the Rihand at Pipri in Sonbhadra, Uttar Pradesh. Its reservoir, Govind Ballabh Pant Sagar, is India's second largest by storage and feeds the Singrauli power belt." },
  { year: 2013, number: 5,  name: "Amarnath",                      lat: 34.2149,  lng: 75.5008,   category: "Cultural & Heritage",           significance: "Cave shrine at about 3,888 m in Anantnag district, Kashmir, with an ice lingam. The annual Amarnath Yatra reaches it from Pahalgam and Baltal." },
  { year: 2013, number: 6,  name: "Rajgir",                        lat: 25.0300,  lng: 85.4200,   category: "Cultural & Heritage",           significance: "Ancient Rajagriha, first capital of Magadha, in Nalanda district, Bihar. Ringed by five hills, linked with the Buddha and Mahavira, and host of the first Buddhist council." },
  { year: 2013, number: 7,  name: "Sindri",                        lat: 23.6805,  lng: 86.4874,   category: "Minerals & Industry",           significance: "Town in Dhanbad district, Jharkhand, in the Damodar coalfields. India's first large fertiliser plant opened here in 1951, and a new urea plant has replaced it." },
  { year: 2013, number: 8,  name: "National Highway No. 24",       lat: 28.3667,  lng: 79.4306,   category: "Transport & Connectivity",      significance: "Under the old numbering, NH 24 joined Delhi and Lucknow through Moradabad and Bareilly, crossing the upper Ganga plain. The route now carries new numbers. Shown at Bareilly." },
  { year: 2013, number: 9,  name: "Churk",                         lat: 24.6500,  lng: 83.1000,   category: "Minerals & Industry",           significance: "Town in Sonbhadra district, Uttar Pradesh, known for its cement factory on local limestone. Part of the Sonbhadra industrial belt with Rihand and Obra." },
  { year: 2013, number: 10, name: "Indira Gandhi Canal",           lat: 31.1500,  lng: 74.9700,   category: "Rivers & Water Bodies",         significance: "India's longest canal, about 837 km. It begins at Harike Barrage at the Sutlej-Beas confluence in Punjab and carries water into the Thar of western Rajasthan. Shown at its head." },
  // ── 2014 ──
  { year: 2014, number: 1,  name: "Guru Shikhar",                  lat: 24.6499,  lng: 72.7763,   category: "Mountains, Passes & Plateaus",  significance: "Highest peak of the Aravalli Range, about 1,722 m, near Mount Abu in Sirohi district, Rajasthan. PRL's Mount Abu infrared observatory stands near it." },
  { year: 2014, number: 2,  name: "Bhor Ghat",                     lat: 18.7667,  lng: 73.3667,   category: "Mountains, Passes & Plateaus",  significance: "Pass on the crest of the Western Ghats between Khopoli and Khandala, Maharashtra. Carries the Mumbai-Pune railway and expressway from the Konkan up to the Deccan." },
  { year: 2014, number: 3,  name: "Shravanabelagola",              lat: 12.8590,  lng: 76.4890,   category: "Cultural & Heritage",           significance: "Jain pilgrim town in Hassan district, Karnataka, with the 57 ft monolith of Gommateshwara (Bahubali) on Vindhyagiri hill. The Mahamastakabhisheka is held every 12 years." },
  { year: 2014, number: 4,  name: "Kalibangan",                    lat: 29.4742,  lng: 74.1303,   category: "Cultural & Heritage",           significance: "Harappan site on the Ghaggar in Hanumangarh district, Rajasthan. Known for the earliest ploughed field, fire altars and a pre-Harappan settlement." },
  { year: 2014, number: 5,  name: "Ganga Sagar",                   lat: 21.6528,  lng: 88.0753,   category: "Islands & Union Territories",   significance: "Sagar Island, where the Hooghly meets the Bay of Bengal, about 100 km south of Kolkata. Hosts the Gangasagar Mela at Makar Sankranti and is exposed to erosion and cyclones." },
  { year: 2014, number: 6,  name: "Mundra Port",                   lat: 22.7460,  lng: 69.7000,   category: "Ports & Coastal",               significance: "India's largest commercial port, on the Gulf of Kutch in Kutch district, Gujarat. A private port with an SEZ, handling containers, coal and crude oil." },
  { year: 2014, number: 7,  name: "Chandipur",                     lat: 21.4700,  lng: 87.0200,   category: "Defence & Strategic",           significance: "Coastal village in Balasore district, Odisha, with DRDO's Integrated Test Range for missiles. Its beach recedes up to about 5 km at low tide." },
  { year: 2014, number: 8,  name: "Mahendragiri",                  lat: 18.9744,  lng: 84.3681,   category: "Mountains, Passes & Plateaus",  significance: "Eastern Ghats peak of about 1,500 m in Gajapati district, Odisha, rich in medicinal plants and declared a biosphere reserve. Also the name of ISRO's propulsion complex in Tirunelveli, Tamil Nadu." },
  { year: 2014, number: 9,  name: "Hazira",                        lat: 21.1610,  lng: 72.6640,   category: "Ports & Coastal",               significance: "Port and industrial hub at the mouth of the Tapi near Surat, Gujarat. Has an LNG terminal, gas processing, steel, fertiliser and petrochemical plants." },
  { year: 2014, number: 10, name: "Vembanad Lake",                 lat: 9.8500,   lng: 76.3500,   category: "Rivers & Water Bodies",         significance: "India's longest lake and Kerala's largest, across Alappuzha, Kottayam and Ernakulam. A Ramsar site, it hosts the Nehru Trophy boat race, and the Thanneermukkom barrier keeps out salt water." },
  // ── 2015 ──
  { year: 2015, number: 1,  name: "Tharangambadi",                 lat: 11.0325,  lng: 79.8531,   category: "Cultural & Heritage",           significance: "Coastal town in Mayiladuthurai district, Tamil Nadu, formerly Tranquebar. A Danish trading post from 1620 with Dansborg Fort, where Ziegenbalg started a Protestant mission and printing press." },
  { year: 2015, number: 2,  name: "Namcha Barwa",                  lat: 29.6292,  lng: 95.0558,   category: "Mountains, Passes & Plateaus",  significance: "Peak of about 7,782 m in Tibet at the eastern end of the Himalaya. The Yarlung Tsangpo bends round it through a deep gorge before entering Arunachal as the Siang." },
  { year: 2015, number: 3,  name: "Narcodam",                      lat: 13.4500,  lng: 94.2700,   category: "Islands & Union Territories",   significance: "Narcondam, a small volcanic island in the Andaman Sea and India's easternmost island. Home of the endemic Narcondam hornbill. Its volcano is dormant." },
  { year: 2015, number: 4,  name: "Khajjiar",                      lat: 32.5462,  lng: 76.0581,   category: "Mountains, Passes & Plateaus",  significance: "Saucer-shaped meadow and hill station near Dalhousie in Chamba district, Himachal Pradesh, ringed by deodar forest round a small lake. Called the mini Switzerland of India." },
  { year: 2015, number: 5,  name: "Chunchanakatte",                lat: 12.5066,  lng: 76.2907,   category: "Rivers & Water Bodies",         significance: "Waterfall on the Kaveri near Saligrama in Mysuru district, Karnataka, where the river drops about 20 m in two cascades before joining again." },
  { year: 2015, number: 6,  name: "Nokrek",                        lat: 25.5333,  lng: 90.1167,   category: "Wildlife & Biosphere",          significance: "National park at the core of the Nokrek Biosphere Reserve in the West Garo Hills, Meghalaya, a UNESCO biosphere reserve since 2009. Known for wild citrus (Citrus indica) and red pandas." },
  { year: 2015, number: 7,  name: "Gorakhnath Peak",               lat: 21.4947,  lng: 70.5056,   category: "Mountains, Passes & Plateaus",  significance: "Highest summit of Girnar near Junagadh and the highest point in Gujarat. An igneous hill sacred to Jains and Hindus, with Gorakhnath's shrine at the top." },
  { year: 2015, number: 8,  name: "Indrakiladri Peak",             lat: 16.5190,  lng: 80.6215,   category: "Cultural & Heritage",           significance: "Hill on the Krishna at Vijayawada, Andhra Pradesh, crowned by the Kanaka Durga temple. Overlooks the Prakasam Barrage." },
  { year: 2015, number: 9,  name: "Polavaram",                     lat: 17.2892,  lng: 81.6514,   category: "Dams & Hydropower",             significance: "Multipurpose national project under construction on the Godavari in Andhra Pradesh. Meant for irrigation, power and diverting Godavari water to the Krishna, it submerges tribal villages." },
  { year: 2015, number: 10, name: "Anaimudi",                      lat: 10.1692,  lng: 77.0607,   category: "Mountains, Passes & Plateaus",  significance: "Highest peak of the Western Ghats and of south India, about 2,695 m, in Eravikulam National Park, Idukki, Kerala. A stronghold of the Nilgiri tahr." },
  // ── 2016 ──
  { year: 2016, number: 1,  name: "Pir Panjal Range",              lat: 33.8933,  lng: 74.4886,   category: "Mountains, Passes & Plateaus",  significance: "Lesser Himalayan range between the Jammu plains and the Kashmir Valley. Crossed by the Banihal pass, the Jawahar road tunnel and the Pir Panjal rail tunnel." },
  { year: 2016, number: 2,  name: "River Indravati",               lat: 19.1800,  lng: 81.9200,   category: "Rivers & Water Bodies",         significance: "Godavari tributary rising in Kalahandi, Odisha, and flowing west through Bastar, Chhattisgarh. Forms Chitrakote Falls and names the Indravati Tiger Reserve. Shown at Jagdalpur." },
  { year: 2016, number: 3,  name: "Nathu La Pass",                 lat: 27.3868,  lng: 88.8310,   category: "International & Border",        significance: "Pass at about 4,310 m in East Sikkim on the India-China border, on an old branch of the Silk Road. Reopened for border trade in 2006 and a route of the Kailash Mansarovar Yatra." },
  { year: 2016, number: 4,  name: "Jog Falls",                     lat: 14.2300,  lng: 74.8128,   category: "Rivers & Water Bodies",         significance: "Plunge falls of about 253 m on the Sharavati in Shivamogga district, Karnataka, among India's highest. The Linganamakki dam upstream regulates its flow for hydropower." },
  { year: 2016, number: 5,  name: "Pulicat Lake",                  lat: 13.5658,  lng: 80.1747,   category: "Rivers & Water Bodies",         significance: "India's second largest brackish lagoon, on the Andhra Pradesh-Tamil Nadu border. Separated from the sea by Sriharikota island, it is a bird sanctuary known for flamingos." },
  { year: 2016, number: 6,  name: "Kudankulam",                    lat: 8.1689,   lng: 77.7125,   category: "Nuclear & Space",               significance: "India's largest nuclear power station, in Tirunelveli district, Tamil Nadu, built with Russian VVER reactors. Its first unit started in 2013." },
  { year: 2016, number: 7,  name: "Nalanda",                       lat: 25.1368,  lng: 85.4438,   category: "Cultural & Heritage",           significance: "Ruins of the Nalanda mahavihara in Bihar, a Buddhist centre of learning from the 5th to the 12th century. A UNESCO World Heritage Site since 2016." },
  { year: 2016, number: 8,  name: "Kudremukh",                     lat: 13.1295,  lng: 75.2686,   category: "Minerals & Industry",           significance: "Peak and national park in the Western Ghats, Chikkamagaluru district, Karnataka. Its iron ore mine, run by KIOCL, was shut in the mid-2000s by the Supreme Court to protect the forest." },
  { year: 2016, number: 9,  name: "Headquarters of N-E Railways",  lat: 26.7637,  lng: 83.4039,   category: "Transport & Connectivity",      significance: "Gorakhpur, Uttar Pradesh, headquarters of the North Eastern Railway zone. Its station has one of the longest railway platforms in the world." },
  { year: 2016, number: 10, name: "Farakka Barrage",               lat: 24.8044,  lng: 87.9331,   category: "Dams & Hydropower",             significance: "Barrage on the Ganga in Murshidabad district, West Bengal, completed in 1975. Its feeder canal diverts water to the Hooghly for Kolkata port, under the 1996 Ganga water treaty with Bangladesh." },
  // ── 2017 ──
  { year: 2017, number: 1,  name: "Thumba",                        lat: 8.5428,   lng: 76.8589,   category: "Nuclear & Space",               significance: "India's first rocket launching station (1963), near Thiruvananthapuram, Kerala, chosen for its closeness to the magnetic equator. Now part of the Vikram Sarabhai Space Centre." },
  { year: 2017, number: 2,  name: "Nayachar Island",               lat: 22.0300,  lng: 88.0600,   category: "Islands & Union Territories",   significance: "Island in the Hooghly estuary off Haldia, West Bengal, inhabited by a few fishermen. A chemical hub planned here around 2007 was dropped." },
  { year: 2017, number: 3,  name: "Doddabetta",                    lat: 11.4024,  lng: 76.7367,   category: "Mountains, Passes & Plateaus",  significance: "Highest peak of the Nilgiris, about 2,637 m, near Ooty, Tamil Nadu, where the Western and Eastern Ghats meet." },
  { year: 2017, number: 4,  name: "Devasthal",                     lat: 29.3617,  lng: 79.6850,   category: "Nuclear & Space",               significance: "ARIES observatory in Nainital district, Uttarakhand. Hosts the 3.6 m Devasthal Optical Telescope, India's largest optical telescope, opened in 2016 with Belgium." },
  { year: 2017, number: 5,  name: "Pangong Lake",                  lat: 33.7179,  lng: 78.8968,   category: "International & Border",        significance: "Endorheic lake at about 4,300 m in eastern Ladakh, most of it in Tibet. The Line of Actual Control crosses it, and its banks saw the 2020 India-China standoff." },
  { year: 2017, number: 6,  name: "Hampi",                         lat: 15.3344,  lng: 76.4622,   category: "Cultural & Heritage",           significance: "Ruins of Vijayanagara, capital of the Vijayanagara empire, on the Tungabhadra in Karnataka. A UNESCO World Heritage Site with the Virupaksha and Vitthala temples." },
  { year: 2017, number: 7,  name: "Havelock Island",               lat: 11.9600,  lng: 93.0000,   category: "Islands & Union Territories",   significance: "Largest island of Ritchie's Archipelago, east of South Andaman, renamed Swaraj Dweep in 2018. Known for Radhanagar beach and coral reefs." },
  { year: 2017, number: 8,  name: "Luni River",                    lat: 25.8300,  lng: 72.2300,   category: "Rivers & Water Bodies",         significance: "Largest river of the Thar, rising near Ajmer in the Aravallis and ending in the Rann of Kutch. Seasonal and saline in its lower course. Shown at Balotra." },
  { year: 2017, number: 9,  name: "Daringbadi",                    lat: 19.9072,  lng: 84.1228,   category: "Mountains, Passes & Plateaus",  significance: "Hill station at about 915 m in Kandhamal district, Odisha, called the Kashmir of Odisha. Known for pine forests, coffee and frost, near the source of the Rushikulya." },
  { year: 2017, number: 10, name: "Dudhsagar Waterfalls",          lat: 15.3128,  lng: 74.3142,   category: "Rivers & Water Bodies",         significance: "Four-tiered waterfall on the Mandovi (Mahadayi) in Goa, inside Bhagwan Mahaveer Sanctuary near the Karnataka border. The Goa-Londa railway passes in front of it." },
  // ── 2018 ──
  { year: 2018, number: 1,  name: "Shyok River",                   lat: 34.5512,  lng: 77.5485,   category: "Rivers & Water Bodies",         significance: "Indus tributary rising at the Rimo Glacier in the Karakoram. Flows through northern Ladakh, joined by the Galwan and the Nubra, into Gilgit-Baltistan. Shown at Diskit." },
  { year: 2018, number: 2,  name: "Mawlynnong",                    lat: 25.1997,  lng: 91.9317,   category: "Cultural & Heritage",           significance: "Village in East Khasi Hills, Meghalaya, near the Bangladesh border, called Asia's cleanest village. Known for its living root bridge and community-run tourism." },
  { year: 2018, number: 3,  name: "Shravasti",                     lat: 27.5171,  lng: 82.0506,   category: "Cultural & Heritage",           significance: "Ancient capital of Kosala in Uttar Pradesh, near the Rapti. The Buddha spent many rainy seasons at its Jetavana monastery, and Jains revere it as Sambhavanatha's birthplace." },
  { year: 2018, number: 4,  name: "Kori Creek",                    lat: 23.5833,  lng: 68.3667,   category: "International & Border",        significance: "Tidal creek in Kutch, Gujarat, west of the Great Rann near the Pakistan border. Mangrove-fringed and strategic, it is guarded by the BSF." },
  { year: 2018, number: 5,  name: "Amarkantak",                    lat: 22.6733,  lng: 81.7595,   category: "Rivers & Water Bodies",         significance: "Pilgrim town on the Maikal hills in Anuppur district, Madhya Pradesh, where the Vindhyas meet the Satpuras. Source of the Narmada and the Son, in a biosphere reserve." },
  { year: 2018, number: 6,  name: "Ghatshila",                     lat: 22.5801,  lng: 86.4543,   category: "Minerals & Industry",           significance: "Town on the Subarnarekha in East Singhbhum, Jharkhand. Hindustan Copper's Indian Copper Complex at Moubhandar smelts ore from the Singhbhum copper belt." },
  { year: 2018, number: 7,  name: "Tawang",                        lat: 27.5883,  lng: 91.8653,   category: "Cultural & Heritage",           significance: "Town at about 3,000 m in western Arunachal Pradesh near the Bhutan and China borders. Its 17th century monastery is India's largest. Reached over the Sela pass." },
  { year: 2018, number: 8,  name: "Neyyar",                        lat: 8.4000,   lng: 77.1600,   category: "Wildlife & Biosphere",          significance: "Wildlife sanctuary around the Neyyar dam in Thiruvananthapuram district, Kerala, at the southern end of the Western Ghats. Part of the Agasthyamala Biosphere Reserve." },
  { year: 2018, number: 9,  name: "Dandeli",                       lat: 15.2523,  lng: 74.6222,   category: "Wildlife & Biosphere",          significance: "Town on the Kali river in Uttara Kannada, Karnataka, with a paper mill. Part of the Kali Tiger Reserve and known for hornbills and white-water rafting." },
  { year: 2018, number: 10, name: "Mulshi Lake",                   lat: 18.5441,  lng: 73.4650,   category: "Dams & Hydropower",             significance: "Reservoir of the Mulshi dam on the Mula river, Pune district, Maharashtra. Built by Tata in the 1920s to feed the Bhira hydro station in the Konkan." },
  // ── 2019 ──
  { year: 2019, number: 1,  name: "Lothal",                        lat: 22.5214,  lng: 72.2494,   category: "Cultural & Heritage",           significance: "Harappan port town in Ahmedabad district, Gujarat, near the Gulf of Khambhat. Has the earliest known dockyard and a bead-making factory." },
  { year: 2019, number: 2,  name: "River Beas",                    lat: 31.7069,  lng: 76.9317,   category: "Rivers & Water Bodies",         significance: "Rises near the Rohtang Pass, flows through Kullu and Mandi and joins the Sutlej at Harike in Punjab. An Indus tributary dammed at Pandoh and Pong. Shown at Mandi." },
  { year: 2019, number: 3,  name: "Chikhaldara",                   lat: 21.2100,  lng: 77.7200,   category: "Mountains, Passes & Plateaus",  significance: "The only hill station of Vidarbha, over 1,000 m up in the Satpura range in Amravati district, Maharashtra. Next to the Melghat Tiger Reserve and known for coffee." },
  { year: 2019, number: 4,  name: "Narora",                        lat: 28.1581,  lng: 78.4094,   category: "Nuclear & Space",               significance: "Nuclear power station on the Ganga in Bulandshahr district, Uttar Pradesh, with two 220 MW reactors. A barrage here feeds the Lower Ganga Canal." },
  { year: 2019, number: 5,  name: "Lengpui",                       lat: 23.8384,  lng: 92.6204,   category: "Transport & Connectivity",      significance: "Airport serving Aizawl, in Mamit district, Mizoram. Built on a ridge by the state and opened in 1998, it is Mizoram's only airport." },
  { year: 2019, number: 6,  name: "Kuldiha Wildlife Sanctuary",    lat: 21.3333,  lng: 86.5000,   category: "Wildlife & Biosphere",          significance: "Sanctuary in Balasore district, Odisha, joined to Simlipal National Park by the Sukhupada and Nato hills. Sal forests with elephants and leopards." },
  { year: 2019, number: 7,  name: "Thenmala",                      lat: 8.9500,   lng: 77.0667,   category: "Wildlife & Biosphere",          significance: "Site of India's first planned ecotourism project, in Kollam district, Kerala. The Parappar dam on the Kallada is here, beside the Shendurney sanctuary." },
  { year: 2019, number: 8,  name: "Anamudi",                       lat: 10.1692,  lng: 77.0607,   category: "Mountains, Passes & Plateaus",  significance: "Highest peak of the Western Ghats and of south India, about 2,695 m, in Eravikulam National Park, Idukki, Kerala. A stronghold of the Nilgiri tahr." },
  { year: 2019, number: 9,  name: "Barren Island",                 lat: 12.2800,  lng: 93.8600,   category: "Islands & Union Territories",   significance: "Uninhabited island in the Andaman Sea, east of Port Blair. India's only confirmed active volcano, erupting repeatedly since 1991." },
  { year: 2019, number: 10, name: "Durgaduani creek",              lat: 22.1652,  lng: 88.8079,   category: "Rivers & Water Bodies",         significance: "Tidal creek in the Sundarbans near Gosaba, South 24 Parganas, West Bengal. Chosen for India's first tidal power plant, 3.75 MW, later shelved as too costly. Shown at Gosaba." },
  // ── 2020 ──
  { year: 2020, number: 1,  name: "Vadhawan",                      lat: 19.9300,  lng: 72.6600,   category: "Ports & Coastal",               significance: "Site of a deep-water port being built at Vadhavan near Dahanu, Palghar district, Maharashtra. Planned as one of India's largest container ports, begun in 2024." },
  { year: 2020, number: 2,  name: "Salkhan",                       lat: 24.5884,  lng: 83.0408,   category: "Cultural & Heritage",           significance: "Salkhan (Sonbhadra) Fossils Park near Robertsganj, Uttar Pradesh. Preserves stromatolites about 1.4 billion years old, among the oldest fossils in India." },
  { year: 2020, number: 3,  name: "Coorg",                         lat: 12.4208,  lng: 75.7397,   category: "Cultural & Heritage",           significance: "Kodagu district in the Western Ghats of Karnataka, home of the Kodava people. India's leading coffee district and the source region of the Kaveri at Talakaveri." },
  { year: 2020, number: 4,  name: "Mhow",                          lat: 22.5500,  lng: 75.7600,   category: "Defence & Strategic",           significance: "Cantonment town near Indore, Madhya Pradesh, renamed Dr. Ambedkar Nagar after its most famous son. Hosts the Army War College and the Infantry School." },
  { year: 2020, number: 5,  name: "Umroi",                         lat: 25.7472,  lng: 91.8717,   category: "Defence & Strategic",           significance: "Army cantonment in Ri-Bhoi district, Meghalaya, near Shillong's airport. Its Joint Military Training Node hosts India's exercises with friendly armies." },
  { year: 2020, number: 6,  name: "Thoothukudi",                   lat: 8.8056,   lng: 78.1450,   category: "Ports & Coastal",               significance: "Port city on the Gulf of Mannar, Tamil Nadu, with the V.O. Chidambaranar major port. Known for pearl fishing, salt pans and a thermal power station." },
  { year: 2020, number: 7,  name: "Bargarh",                       lat: 21.3333,  lng: 83.6167,   category: "Cultural & Heritage",           significance: "Town in western Odisha, the state's rice bowl, watered by the Hirakud canals. Known for Sambalpuri handloom and Dhanu Yatra, a vast open-air theatre festival." },
  { year: 2020, number: 8,  name: "Atal Tunnel",                   lat: 32.4013,  lng: 77.1483,   category: "Transport & Connectivity",      significance: "9.02 km road tunnel under the Rohtang Pass in Himachal Pradesh, opened in 2020. Links Manali with Lahaul-Spiti all year, the longest highway tunnel above 10,000 ft." },
  { year: 2020, number: 9,  name: "Gurushikhar",                   lat: 24.6499,  lng: 72.7763,   category: "Mountains, Passes & Plateaus",  significance: "Highest peak of the Aravalli Range, about 1,722 m, near Mount Abu in Sirohi district, Rajasthan. PRL's Mount Abu infrared observatory stands near it." },
  { year: 2020, number: 10, name: "Bum La",                        lat: 27.7237,  lng: 91.8916,   category: "International & Border",        significance: "Pass on the India-China border in Tawang district, Arunachal Pradesh, about 37 km from Tawang. A border personnel meeting point and a 1962 war site." },
  // ── 2021 ──
  { year: 2021, number: 1,  name: "Ziro Valley",                   lat: 27.5664,  lng: 93.8314,   category: "Cultural & Heritage",           significance: "Valley at about 1,500 m in Lower Subansiri, Arunachal Pradesh, home of the Apatani people, whose rice-fish farming is on UNESCO's tentative list. Hosts a music festival." },
  { year: 2021, number: 2,  name: "Khecheopalri Lake",             lat: 27.3500,  lng: 88.1886,   category: "Rivers & Water Bodies",         significance: "Sacred lake near Pelling in West Sikkim, revered by Buddhists and Hindus. Part of the pilgrim circuit with Yuksom and Pemayangtse." },
  { year: 2021, number: 3,  name: "Toranmal",                      lat: 21.8800,  lng: 74.4600,   category: "Mountains, Passes & Plateaus",  significance: "Hill station on a plateau of the Satpura range in Nandurbar district, Maharashtra. Known for Yashwant lake, forests and the Gorakhnath temple fair." },
  { year: 2021, number: 4,  name: "Subarnarekha River",            lat: 23.4500,  lng: 85.6500,   category: "Rivers & Water Bodies",         significance: "Rises near Ranchi and flows through Jharkhand, West Bengal and Odisha to the Bay of Bengal, past Jamshedpur. Named for the gold in its sands. Shown at Hundru Falls." },
  { year: 2021, number: 5,  name: "Koderma",                       lat: 24.4700,  lng: 85.6000,   category: "Minerals & Industry",           significance: "Town on the Koderma plateau, Jharkhand, once called the mica capital of India. The Tilaiya dam on the Barakar is nearby." },
  { year: 2021, number: 6,  name: "Sir Creek",                     lat: 23.9667,  lng: 68.8000,   category: "International & Border",        significance: "96 km tidal estuary in the Rann of Kutch between Gujarat and Sindh. Its boundary is disputed between India and Pakistan, affecting maritime zones and fishing." },
  { year: 2021, number: 7,  name: "Periyar Wildlife Sanctuary",    lat: 9.5775,   lng: 77.1800,   category: "Wildlife & Biosphere",          significance: "Tiger reserve round the Periyar lake in Idukki and Pathanamthitta, Kerala, formed by the Mullaperiyar dam. Known for elephants and boat-borne wildlife viewing." },
  { year: 2021, number: 8,  name: "Peechi Dam",                    lat: 10.5300,  lng: 76.3700,   category: "Dams & Hydropower",             significance: "Dam on the Manali river 22 km from Thrissur, Kerala, built for irrigation and Thrissur's drinking water. Inside the Peechi-Vazhani Wildlife Sanctuary." },
  { year: 2021, number: 9,  name: "Digha Beach",                   lat: 21.6384,  lng: 87.5096,   category: "Ports & Coastal",               significance: "West Bengal's most visited seaside resort, in Purba Medinipur near the Odisha border. Its flat beach faces erosion and is protected by a sea wall." },
  { year: 2021, number: 10, name: "Pamban Island",                 lat: 9.2500,   lng: 79.3000,   category: "Islands & Union Territories",   significance: "Island in the Gulf of Mannar with Rameswaram and Dhanushkodi, between India and Sri Lanka. Joined to the mainland by the Pamban rail bridge, rebuilt as a vertical-lift bridge." },
  // ── 2022 ──
  { year: 2022, number: 1,  name: "Tarangambadi",                  lat: 11.0325,  lng: 79.8531,   category: "Cultural & Heritage",           significance: "Coastal town in Mayiladuthurai district, Tamil Nadu, formerly Tranquebar. A Danish trading post from 1620 with Dansborg Fort, where Ziegenbalg started a Protestant mission and printing press." },
  { year: 2022, number: 2,  name: "Mahe",                          lat: 11.7011,  lng: 75.5367,   category: "Islands & Union Territories",   significance: "Enclave of Puducherry at the mouth of the Mahe river on the Kerala coast, surrounded by Kannur and Kozhikode districts. A French possession until 1954." },
  { year: 2022, number: 3,  name: "Bomdila",                       lat: 27.2650,  lng: 92.4200,   category: "Cultural & Heritage",           significance: "Headquarters of West Kameng, Arunachal Pradesh, at about 2,400 m on the road to Tawang. Has a Gelugpa monastery and saw fighting in the 1962 war." },
  { year: 2022, number: 4,  name: "Dhola Sadiya Bridge",           lat: 27.7986,  lng: 95.6761,   category: "Transport & Connectivity",      significance: "Bhupen Hazarika Setu, a 9.15 km bridge over the Lohit in Tinsukia, Assam, opened in 2017. Links Assam with eastern Arunachal and can carry tanks." },
  { year: 2022, number: 5,  name: "Talakaveri",                    lat: 12.3855,  lng: 75.4914,   category: "Rivers & Water Bodies",         significance: "Source of the Kaveri on the Brahmagiri hills in Kodagu, Karnataka. A pilgrimage site, busiest at Tula Sankramana in October." },
  { year: 2022, number: 6,  name: "Satkosia",                      lat: 20.5401,  lng: 84.8316,   category: "Wildlife & Biosphere",          significance: "Tiger reserve along the Mahanadi gorge in Angul and Nayagarh, Odisha. Home of gharials and of India's first inter-state tiger translocation in 2018." },
  { year: 2022, number: 7,  name: "Dholavira",                     lat: 23.8886,  lng: 70.2136,   category: "Cultural & Heritage",           significance: "Harappan city on Khadir island in Kutch, Gujarat, a UNESCO World Heritage Site since 2021. Known for its water reservoirs and a large inscribed signboard." },
  { year: 2022, number: 8,  name: "Sonamarg",                      lat: 34.3015,  lng: 75.2925,   category: "Mountains, Passes & Plateaus",  significance: "Hill station on the Sindh river in Ganderbal, Kashmir, the gateway to the Zoji La and the Baltal route to Amarnath. The Z-Morh tunnel gives it all-weather access." },
  { year: 2022, number: 9,  name: "Maliku Atoll",                  lat: 8.2750,   lng: 73.0528,   category: "Islands & Union Territories",   significance: "Minicoy, Lakshadweep's southernmost atoll, near the Nine Degree Channel and the Maldives. Its people speak Mahl, close to Dhivehi." },
  { year: 2022, number: 10, name: "Gangasagar",                    lat: 21.6528,  lng: 88.0753,   category: "Islands & Union Territories",   significance: "Sagar Island, where the Hooghly meets the Bay of Bengal, about 100 km south of Kolkata. Hosts the Gangasagar Mela at Makar Sankranti and is exposed to erosion and cyclones." },
  // ── 2023 ──
  { year: 2023, number: 1,  name: "Nathula",                       lat: 27.3868,  lng: 88.8310,   category: "International & Border",        significance: "Pass at about 4,310 m in East Sikkim on the India-China border, on an old branch of the Silk Road. Reopened for border trade in 2006 and a route of the Kailash Mansarovar Yatra." },
  { year: 2023, number: 2,  name: "Hutti",                         lat: 16.1970,  lng: 76.6600,   category: "Minerals & Industry",           significance: "Gold mine in Raichur district, Karnataka, run by Hutti Gold Mines Ltd. India's main source of mined gold since the Kolar fields closed." },
  { year: 2023, number: 3,  name: "Ross Island",                   lat: 11.6750,  lng: 92.7630,   category: "Islands & Union Territories",   significance: "Island 3 km east of Port Blair, the British administrative headquarters of the Andamans. Renamed Netaji Subhash Chandra Bose Island in 2018." },
  { year: 2023, number: 4,  name: "Moreh",                         lat: 24.2477,  lng: 94.3031,   category: "International & Border",        significance: "Border town in Tengnoupal, Manipur, opposite Tamu in Myanmar. India's main land crossing to Myanmar, on the India-Myanmar-Thailand trilateral highway." },
  { year: 2023, number: 5,  name: "Ramappa",                       lat: 18.2594,  lng: 79.9425,   category: "Cultural & Heritage",           significance: "13th century Kakatiya temple at Palampet, Mulugu district, Telangana, named after its sculptor. A UNESCO World Heritage Site since 2021, roofed with light floating bricks." },
  { year: 2023, number: 6,  name: "Namdapha National Park",        lat: 27.4833,  lng: 96.3833,   category: "Wildlife & Biosphere",          significance: "National park in Changlang, Arunachal Pradesh, on the Myanmar border. The only park with four big cats: tiger, leopard, clouded leopard and snow leopard." },
  { year: 2023, number: 7,  name: "Sela Tunnel",                   lat: 27.5073,  lng: 92.0827,   category: "Transport & Connectivity",      significance: "Road tunnels at about 13,000 ft below the Sela pass in West Kameng, Arunachal Pradesh, opened in 2024. Give all-weather access to Tawang." },
  { year: 2023, number: 8,  name: "Ennore Port",                   lat: 13.2516,  lng: 80.3268,   category: "Ports & Coastal",               significance: "Kamarajar Port, about 18 km north of Chennai Port, Tamil Nadu. India's first corporatised major port, handling coal, LNG and cars." },
  { year: 2023, number: 9,  name: "Ramagundam",                    lat: 18.7639,  lng: 79.4750,   category: "Minerals & Industry",           significance: "Industrial city on the Godavari in Peddapalli district, Telangana. Has an NTPC super thermal power station, Singareni coal mines and a revived urea plant." },
  { year: 2023, number: 10, name: "Betwa River",                   lat: 25.3500,  lng: 78.6400,   category: "Rivers & Water Bodies",         significance: "Yamuna tributary rising in the Vindhyas near Bhopal and flowing through Bundelkhand. One end of the Ken-Betwa river link. Shown at Orchha." },
  // ── 2024 ──
  { year: 2024, number: 1,  name: "Lunkaransar",                   lat: 28.4950,  lng: 73.7484,   category: "Rivers & Water Bodies",         significance: "Town in Bikaner district, Rajasthan, beside a saline playa lake in the Thar. The lake's sediments are studied for the past climate of the desert." },
  { year: 2024, number: 2,  name: "Gua",                           lat: 22.2000,  lng: 85.3800,   category: "Minerals & Industry",           significance: "Iron ore mining town in West Singhbhum, Jharkhand, in the Noamundi-Barajamda belt. SAIL's Gua mines feed its steel plants." },
  { year: 2024, number: 3,  name: "Raidak River",                  lat: 26.3345,  lng: 89.6699,   category: "Rivers & Water Bodies",         significance: "Trans-boundary river, the Wang Chhu of Bhutan, which flows through Alipurduar and Cooch Behar to the Brahmaputra. Bhutan's Chukha and Tala hydro projects are on it. Shown near Tufanganj." },
  { year: 2024, number: 4,  name: "Ekta Nagar",                    lat: 21.8380,  lng: 73.7191,   category: "Cultural & Heritage",           significance: "Formerly Kevadia, in Narmada district, Gujarat, beside the Sardar Sarovar dam. Site of the Statue of Unity, the world's tallest statue at 182 m." },
  { year: 2024, number: 5,  name: "Chandanwari",                   lat: 34.0803,  lng: 75.4178,   category: "Cultural & Heritage",           significance: "Starting point of the Amarnath Yatra from Pahalgam, about 16 km away, on the Lidder in Anantnag district, Kashmir." },
  { year: 2024, number: 6,  name: "Babina",                        lat: 25.2500,  lng: 78.4700,   category: "Defence & Strategic",           significance: "Cantonment near Jhansi, Uttar Pradesh, with armoured formations and field firing ranges in Bundelkhand." },
  { year: 2024, number: 7,  name: "Tatipaka",                      lat: 16.5036,  lng: 81.8756,   category: "Minerals & Industry",           significance: "Village in Konaseema district, Andhra Pradesh, in the Krishna-Godavari basin. ONGC runs a small refinery here on local crude." },
  { year: 2024, number: 8,  name: "Along Airport",                 lat: 28.1753,  lng: 94.8019,   category: "Transport & Connectivity",      significance: "Advanced landing ground at Aalo (Along), West Siang, Arunachal Pradesh, upgraded for military and civil flights. Serves the Siang valley near the China border." },
  { year: 2024, number: 9,  name: "Karaikal",                      lat: 10.9327,  lng: 79.8319,   category: "Islands & Union Territories",   significance: "Coastal enclave of Puducherry in the Kaveri delta, surrounded by Tamil Nadu. A former French settlement, with a port and the Thirunallar temple." },
  { year: 2024, number: 10, name: "Panna",                         lat: 24.7304,  lng: 80.0102,   category: "Wildlife & Biosphere",          significance: "Tiger reserve on the Ken river in Madhya Pradesh that lost all its tigers by 2009 and was restocked. Panna district is also India's diamond-mining centre." },
  // ── 2025 ──
  { year: 2025, number: 1,  name: "Rushikulya River",              lat: 19.3800,  lng: 85.0700,   category: "Rivers & Water Bodies",         significance: "Rises in the Daringbadi hills of Kandhamal and flows through Ganjam, Odisha, to the sea. Its mouth is a mass nesting site of olive ridley turtles. Shown near Ganjam." },
  { year: 2025, number: 2,  name: "Datar Hill",                    lat: 21.5046,  lng: 70.4809,   category: "Cultural & Heritage",           significance: "Hill east of Junagadh, Gujarat, beside Willingdon Dam and near Girnar. Topped by the shrine of Jamiyal Shah Datar, revered by Hindus and Muslims, about 2,500 steps up." },
  { year: 2025, number: 3,  name: "Kikruma",                       lat: 25.5791,  lng: 94.2113,   category: "Cultural & Heritage",           significance: "Chakhesang village in Phek district, Nagaland. In 1851 its warriors fought British forces in the Battle of Kikruma, one of the bloodiest in the north-eastern hills." },
  { year: 2025, number: 4,  name: "Choritand Tillaya",             lat: 23.7800,  lng: 85.6400,   category: "Minerals & Industry",           significance: "Coal block at Tilaiya village in Gumia block, Bokaro district, Jharkhand, in the Damodar valley coalfields. Listed by the Coal Ministry for open-cast mining." },
  { year: 2025, number: 5,  name: "Byalalu",                       lat: 12.8999,  lng: 77.3738,   category: "Nuclear & Space",               significance: "Village near Bengaluru, Karnataka, home of ISRO's Indian Deep Space Network. Its antennas tracked Chandrayaan and Mangalyaan." },
  { year: 2025, number: 6,  name: "Neyyar",                        lat: 8.4000,   lng: 77.1600,   category: "Wildlife & Biosphere",          significance: "Wildlife sanctuary around the Neyyar dam in Thiruvananthapuram district, Kerala, at the southern end of the Western Ghats. Part of the Agasthyamala Biosphere Reserve." },
  { year: 2025, number: 7,  name: "Uttarlai",                      lat: 25.8130,  lng: 71.4823,   category: "Defence & Strategic",           significance: "Air Force station near Barmer in the Thar, Rajasthan, close to the Pakistan border. A frontline base since the 1971 war, also used for civil flights." },
  { year: 2025, number: 8,  name: "Sri Vijayapuram",               lat: 11.6683,  lng: 92.7378,   category: "Islands & Union Territories",   significance: "Capital of the Andaman and Nicobar Islands, renamed from Port Blair in 2024. Home of the Cellular Jail and India's tri-service Andaman and Nicobar Command." },
  { year: 2025, number: 9,  name: "Dharwas",                       lat: 33.1333,  lng: 76.3500,   category: "Mountains, Passes & Plateaus",  significance: "Northernmost town of Himachal Pradesh, at about 2,400 m in the Pangi valley of Chamba district. Known for the Tilmili mineral spring." },
  { year: 2025, number: 10, name: "Gitabitan",                     lat: 23.6800,  lng: 87.6800,   category: "Cultural & Heritage",           significance: "Township planned by West Bengal near Santiniketan, Birbhum, on about 100 acres for culture and tourism. Named after Tagore's collection of songs. Shown at Santiniketan." },
  // ── 2026 ──
  { year: 2026, number: 1,  name: "Bitra Island",                  lat: 11.5500,  lng: 72.1500,   category: "Islands & Union Territories",   significance: "Smallest inhabited island of Lakshadweep. In 2025 the administration proposed taking it over for defence use, which its residents opposed." },
  { year: 2026, number: 2,  name: "Lohit River",                   lat: 27.8000,  lng: 95.4667,   category: "Rivers & Water Bodies",         significance: "Rises in Tibet as the Zayul Chu and flows through Arunachal past Parshuram Kund into Assam, joining the Brahmaputra near Sadiya. Crossed by the Dhola-Sadiya bridge." },
  { year: 2026, number: 3,  name: "Dras",                          lat: 34.4303,  lng: 75.7531,   category: "Defence & Strategic",           significance: "Town in Kargil district, Ladakh, on the Srinagar-Leh road beyond the Zoji La. Among the coldest inhabited places in India and a key sector of the 1999 Kargil war." },
  { year: 2026, number: 4,  name: "Kuno National Park",            lat: 25.6667,  lng: 77.1667,   category: "Wildlife & Biosphere",          significance: "Park on the Kuno river in Sheopur, Madhya Pradesh, chosen for Project Cheetah. Cheetahs from Namibia and South Africa have been released here since 2022." },
  { year: 2026, number: 5,  name: "Yadadri",                       lat: 17.5892,  lng: 78.9446,   category: "Cultural & Heritage",           significance: "Yadagirigutta in Yadadri Bhuvanagiri district, Telangana, with the Lakshmi Narasimha temple on a hill, rebuilt in black granite and reopened in 2022." },
  { year: 2026, number: 6,  name: "Mahi Basin",                    lat: 23.6270,  lng: 74.5442,   category: "Rivers & Water Bodies",         significance: "Basin of the west-flowing Mahi, which rises in Madhya Pradesh, crosses the Vagad region of Rajasthan and enters the Gulf of Khambhat in Gujarat. Shown at the Mahi Bajaj Sagar dam." },
  { year: 2026, number: 7,  name: "Tamralipta",                    lat: 22.3000,  lng: 87.9200,   category: "Ports & Coastal",               significance: "Ancient port of Bengal at present Tamluk, Purba Medinipur, West Bengal. It linked Bengal with Sri Lanka and Southeast Asia, and Faxian sailed from here." },
  { year: 2026, number: 8,  name: "Toranmal",                      lat: 21.8800,  lng: 74.4600,   category: "Mountains, Passes & Plateaus",  significance: "Hill station on a plateau of the Satpura range in Nandurbar district, Maharashtra. Known for Yashwant lake, forests and the Gorakhnath temple fair." },
  { year: 2026, number: 9,  name: "Raya Heritage City",            lat: 27.5667,  lng: 77.7833,   category: "Cultural & Heritage",           significance: "Heritage township planned by YEIDA at Raya near Mathura, Uttar Pradesh, on the Yamuna. Themed on Krishna and the Braj region, for pilgrims and tourists." },
  { year: 2026, number: 10, name: "Varkala",                       lat: 8.7433,   lng: 76.6968,   category: "Ports & Coastal",               significance: "Coastal town in Thiruvananthapuram district, Kerala, known for its laterite cliffs, a national geo-heritage site, and the Janardhana Swamy temple." },
];

export const geoMapYears = [...new Set(geoMapData.map(e => e.year))].sort((a, b) => b - a);
