// Geography Optional — UPSC PYQ Map Questions 2013–2025
// Paper II, Q1(a): 10 locations per year × 13 years = 130 entries

export type GeoCategory =
  | 'Rivers & Water Bodies'
  | 'Mountains, Passes & Plateaus'
  | 'Wildlife & Biosphere'
  | 'Dams & Hydropower'
  | 'Defence & Strategic'
  | 'Ports & Coastal'
  | 'Nuclear & Space'
  | 'Islands & Union Territories'
  | 'Minerals & Industry'
  | 'Cultural & Heritage'
  | 'International & Border';

export const GEO_CATEGORIES: GeoCategory[] = [
  'Rivers & Water Bodies',
  'Mountains, Passes & Plateaus',
  'Wildlife & Biosphere',
  'Dams & Hydropower',
  'Defence & Strategic',
  'Ports & Coastal',
  'Nuclear & Space',
  'Islands & Union Territories',
  'Minerals & Industry',
  'Cultural & Heritage',
  'International & Border',
];

export interface GeoMapEntry {
  year: number;
  number: number;
  name: string;
  lat: number;
  lng: number;
  significance: string;
  category: GeoCategory;
}

export const geoMapData: GeoMapEntry[] = [
  // ── 2013 ──
  { year: 2013, number: 1,  name: "Rushikulya River",      lat: 19.4,  lng: 84.8,  category: "Rivers & Water Bodies",       significance: "River in Odisha draining into Bay of Bengal. Important for Olive Ridley sea turtle nesting. Its estuary is an ecologically sensitive zone and supports local fishing communities." },
  { year: 2013, number: 2,  name: "Datar Hill",            lat: 22.3,  lng: 70.4,  category: "Mountains, Passes & Plateaus", significance: "Isolated hill near Junagadh, Gujarat. Part of Kathiawar peninsula. Significant for local pilgrimage and mineral deposits in the surrounding Deccan trap region." },
  { year: 2013, number: 3,  name: "Kikruma",               lat: 25.9,  lng: 94.3,  category: "Cultural & Heritage",          significance: "Village in Nagaland. Located in the hills of northeast India. Culturally significant as a traditional Naga settlement in the biodiversity-rich eastern Himalayan region." },
  { year: 2013, number: 4,  name: "Choritand Tillaya",     lat: 24.0,  lng: 85.6,  category: "Dams & Hydropower",            significance: "Dam site on Damodar River, Jharkhand. Part of Damodar Valley Corporation. Provides hydroelectric power and flood control in the coal belt region of eastern India." },
  { year: 2013, number: 5,  name: "Byalalu",               lat: 13.1,  lng: 77.4,  category: "Nuclear & Space",              significance: "Village near Bengaluru, Karnataka. Houses ISRO's Deep Space Network antenna. Strategically important for India's space communication and satellite tracking infrastructure." },
  { year: 2013, number: 6,  name: "Neyyar",                lat: 8.5,   lng: 77.1,  category: "Wildlife & Biosphere",         significance: "Reservoir and wildlife sanctuary in Kerala. Located in Western Ghats biodiversity hotspot. Supports lion-tailed macaque and elephant populations; important for irrigation." },
  { year: 2013, number: 7,  name: "Uttarlai",              lat: 25.9,  lng: 71.3,  category: "Defence & Strategic",          significance: "Air Force station in Barmer district, Rajasthan. Strategically located near Indo-Pakistan border. Important defence installation in the Thar Desert region." },
  { year: 2013, number: 8,  name: "Sri Vijayapuram",       lat: 11.7,  lng: 92.7,  category: "Islands & Union Territories",  significance: "Formerly Port Blair, Andaman and Nicobar Islands. Administrative capital of the union territory. Strategically located near Malacca Strait; significant for India's maritime security." },
  { year: 2013, number: 9,  name: "Dharwas",               lat: 15.5,  lng: 74.9,  category: "Minerals & Industry",          significance: "Town in Karnataka, part of Dharwad district. Located on Deccan plateau. Known for cotton cultivation, educational institutions, and proximity to iron ore mining areas." },
  { year: 2013, number: 10, name: "Gitabitan",             lat: 22.6,  lng: 88.4,  category: "Cultural & Heritage",          significance: "Rabindranath Tagore's cultural institute in Kolkata. Named after his song collection. Represents Bengal's rich literary and cultural heritage in the Gangetic delta region." },
  // ── 2014 ──
  { year: 2014, number: 1,  name: "Banihal Pass",          lat: 33.4,  lng: 75.2,  category: "Mountains, Passes & Plateaus", significance: "Mountain pass in Pir Panjal range, J&K. Connects Jammu with Kashmir Valley. The Banihal tunnel beneath it provides all-weather connectivity critical for national integration." },
  { year: 2014, number: 2,  name: "Nokrek",                lat: 25.5,  lng: 90.3,  category: "Wildlife & Biosphere",         significance: "Biosphere Reserve in Meghalaya. A UNESCO-recognised reserve in the Garo Hills. Centre of origin of citrus fruits; rich in biodiversity including red pandas and hoolock gibbons." },
  { year: 2014, number: 3,  name: "Farakka",               lat: 24.8,  lng: 87.9,  category: "Dams & Hydropower",            significance: "Barrage on the Ganga in West Bengal. Diverts water to Hooghly to maintain Kolkata port. Subject of India-Bangladesh water-sharing treaty; significant for irrigation and navigation." },
  { year: 2014, number: 4,  name: "Dachigam",              lat: 34.2,  lng: 74.9,  category: "Wildlife & Biosphere",         significance: "National Park near Srinagar, J&K. Last stronghold of the Hangul (Kashmir stag). Located in high-altitude meadows; important for wildlife conservation in the Himalayan region." },
  { year: 2014, number: 5,  name: "Tarapur",               lat: 19.8,  lng: 72.7,  category: "Nuclear & Space",              significance: "India's first nuclear power plant, Maharashtra. Located on west coast near Mumbai. Major source of nuclear energy; highlights India's civilian atomic energy programme." },
  { year: 2014, number: 6,  name: "Wular Lake",            lat: 34.4,  lng: 74.6,  category: "Rivers & Water Bodies",        significance: "Largest freshwater lake in India, J&K. Fed by Jhelum River. Under Ramsar Convention; important for fisheries, migratory birds, and water security of Kashmir Valley." },
  { year: 2014, number: 7,  name: "Nathpa Jhakri",         lat: 31.6,  lng: 77.8,  category: "Dams & Hydropower",            significance: "Hydroelectric project on Sutlej River, Himachal Pradesh. One of India's largest run-of-river power stations. Supplies power to northern grid states; important for energy security." },
  { year: 2014, number: 8,  name: "Khardung La",           lat: 34.3,  lng: 77.6,  category: "Defence & Strategic",          significance: "High-altitude mountain pass in Ladakh. Connects Leh to Siachen Glacier region. One of world's highest motorable roads; strategically important for military logistics." },
  { year: 2014, number: 9,  name: "Paradip",               lat: 20.3,  lng: 86.6,  category: "Ports & Coastal",              significance: "Major port on Odisha coast at Mahanadi mouth. India's leading crude oil handling port. Handles iron ore export and fertiliser imports; important for eastern India's trade." },
  { year: 2014, number: 10, name: "Kovalam",               lat: 8.4,   lng: 76.9,  category: "Ports & Coastal",              significance: "Beach resort in Kerala near Thiruvananthapuram. International tourist destination on the Malabar Coast. Contributes significantly to Kerala's tourism economy and foreign exchange earnings." },
  // ── 2015 ──
  { year: 2015, number: 1,  name: "Lonar Lake",            lat: 19.98, lng: 76.51, category: "Rivers & Water Bodies",        significance: "Saline soda lake in Maharashtra formed by meteorite impact. A Ramsar site and geological heritage monument. Unique alkaline ecosystem supporting rare microorganisms and migratory birds." },
  { year: 2015, number: 2,  name: "Bhabha Atomic Research Centre", lat: 19.02, lng: 72.92, category: "Nuclear & Space",      significance: "Premier nuclear research institution at Trombay, Mumbai. Develops nuclear reactors, radioisotopes and defence technologies. Central to India's three-stage nuclear power programme." },
  { year: 2015, number: 3,  name: "Dudhwa",                lat: 28.5,  lng: 80.6,  category: "Wildlife & Biosphere",         significance: "National Park and Tiger Reserve in Uttar Pradesh's Terai region. Supports Bengal tigers, barasingha and swamp deer. Ecologically important wetland-grassland mosaic biome." },
  { year: 2015, number: 4,  name: "Chabahar",              lat: 25.3,  lng: 60.6,  category: "International & Border",       significance: "Iranian deep-sea port on Gulf of Oman. India is developing it as a strategic gateway to Afghanistan and Central Asia. Bypasses Pakistan; key for India's connectivity and trade diplomacy." },
  { year: 2015, number: 5,  name: "Mouling",               lat: 28.8,  lng: 95.2,  category: "Wildlife & Biosphere",         significance: "National Park in Arunachal Pradesh in the eastern Himalayas. One of India's least disturbed ecosystems. Rich in biodiversity including snow leopard, clouded leopard and rare orchids." },
  { year: 2015, number: 6,  name: "Bhadra",                lat: 13.7,  lng: 75.7,  category: "Wildlife & Biosphere",         significance: "Wildlife Sanctuary and Tiger Reserve in Karnataka's Western Ghats. Important catchment area for Bhadra River. Supports large populations of elephants and gaur in the biodiversity hotspot." },
  { year: 2015, number: 7,  name: "Dzukou Valley",         lat: 25.5,  lng: 94.1,  category: "Mountains, Passes & Plateaus", significance: "High-altitude valley on Nagaland-Manipur border. Renowned for seasonal Dzukou lily blooms. Trekking destination of ecological significance in the biodiversity-rich eastern Himalayas." },
  { year: 2015, number: 8,  name: "Dibang Valley",         lat: 28.5,  lng: 96.2,  category: "Rivers & Water Bodies",        significance: "Remote river valley in Arunachal Pradesh near China border. Proposed Dibang multipurpose hydroelectric dam site. Rich in ethnic Idu Mishmi culture and biodiversity." },
  { year: 2015, number: 9,  name: "Jawai",                 lat: 25.2,  lng: 73.2,  category: "Rivers & Water Bodies",        significance: "Dam reservoir in Rajasthan's Pali district. Important water source for western Rajasthan. Hosts largest leopard population in the Aravalli range and supports migratory flamingos." },
  { year: 2015, number: 10, name: "Tawang",                lat: 27.6,  lng: 91.9,  category: "Defence & Strategic",          significance: "Town in Arunachal Pradesh bordering China and Bhutan. Strategic military importance; site of 1962 war battles. Houses India's largest Buddhist monastery; claimed by China." },
  // ── 2016 ──
  { year: 2016, number: 1,  name: "Galathea Bay",          lat: 7.0,   lng: 93.9,  category: "Islands & Union Territories",  significance: "Deep-water bay in Great Nicobar Island. Proposed transshipment port and greenfield city. Strategically located near international shipping lanes between Indian and Pacific Oceans." },
  { year: 2016, number: 2,  name: "Panna",                 lat: 24.7,  lng: 80.2,  category: "Minerals & Industry",          significance: "Tiger Reserve in Madhya Pradesh on Vindhyan plateau. Diamonds found in Panna mines — only diamond-producing region in India. Ken River flows through; Ken-Betwa link project site." },
  { year: 2016, number: 3,  name: "Doyang",                lat: 26.1,  lng: 94.1,  category: "Dams & Hydropower",            significance: "Reservoir in Nagaland on Doyang River. Hosts spectacular Amur falcon roosting — world's largest raptor congregation. Ecological significance for migratory bird conservation." },
  { year: 2016, number: 4,  name: "Gandikota",             lat: 14.8,  lng: 78.3,  category: "Cultural & Heritage",          significance: "Fort on Penna River in Andhra Pradesh. Located in a dramatic gorge called Grand Canyon of India. Historical fort of Kamma chiefs; tourist destination with unique geological landscape." },
  { year: 2016, number: 5,  name: "Makalu",                lat: 27.9,  lng: 87.1,  category: "International & Border",       significance: "Fifth highest mountain in the world on Nepal-China border. Part of Mahalangur Himalayan range. Makalu Barun National Park nearby is biodiversity-rich; significant for mountaineering." },
  { year: 2016, number: 6,  name: "Patkai Hills",          lat: 26.5,  lng: 96.0,  category: "Mountains, Passes & Plateaus", significance: "Hill range forming India-Myanmar border. Separates Brahmaputra valley from Myanmar. Important for Stilwell Road; rich in petroleum (Digboi), coal and timber resources." },
  { year: 2016, number: 7,  name: "Nanda Devi",            lat: 30.4,  lng: 79.9,  category: "Mountains, Passes & Plateaus", significance: "Second highest peak in India in Uttarakhand. UNESCO World Heritage Biosphere Reserve. The Nanda Devi Sanctuary is ecologically significant with rare alpine flora and fauna." },
  { year: 2016, number: 8,  name: "Sriharikota",           lat: 13.7,  lng: 80.2,  category: "Nuclear & Space",              significance: "Island in Andhra Pradesh housing ISRO's Satish Dhawan Space Centre. India's only spaceport. Location chosen for proximity to equator and sea for booster rocket recovery." },
  { year: 2016, number: 9,  name: "Koyna",                 lat: 17.4,  lng: 73.8,  category: "Dams & Hydropower",            significance: "Hydroelectric dam in Maharashtra's Western Ghats. Largest power project in Maharashtra. Site of devastating 1967 earthquake demonstrating reservoir-induced seismicity." },
  { year: 2016, number: 10, name: "Rann of Kutch",         lat: 23.7,  lng: 70.0,  category: "Rivers & Water Bodies",        significance: "Seasonal salt marsh in Gujarat on Pakistan border. World's largest salt desert. Hosts Wild Ass Sanctuary and flamingo breeding; unique tidal flat ecosystem." },
  // ── 2017 ──
  { year: 2017, number: 1,  name: "Pamban Island",         lat: 9.3,   lng: 79.2,  category: "Islands & Union Territories",  significance: "Island off Tamil Nadu coast connecting Rameswaram to mainland. Pamban Bridge, first sea bridge in India. Strategically located near Palk Strait; important for road-rail connectivity." },
  { year: 2017, number: 2,  name: "Nubra Valley",          lat: 34.7,  lng: 77.5,  category: "Defence & Strategic",          significance: "Cold desert valley in Ladakh at confluence of Nubra and Shyok rivers. Known for Bactrian camels. Strategic location near Siachen and Karakoram Pass; popular tourism destination." },
  { year: 2017, number: 3,  name: "Ranganathittu",         lat: 12.4,  lng: 76.7,  category: "Wildlife & Biosphere",         significance: "Bird sanctuary on Cauvery River, Karnataka. Largest bird sanctuary in Karnataka; hosts painted storks, herons and open-billed storks. Ramsar Wetland of International Importance." },
  { year: 2017, number: 4,  name: "Dholera",               lat: 22.2,  lng: 72.2,  category: "Minerals & Industry",          significance: "Greenfield smart city project in Gujarat. Part of Delhi-Mumbai Industrial Corridor. Proposed Special Investment Region with integrated infrastructure and industrial zones." },
  { year: 2017, number: 5,  name: "Rohtang Pass",          lat: 32.4,  lng: 77.2,  category: "Mountains, Passes & Plateaus", significance: "High mountain pass in Himachal Pradesh on Pir Panjal Range. Connects Kullu Valley with Lahaul and Spiti. Atal Tunnel built beneath it for all-weather connectivity." },
  { year: 2017, number: 6,  name: "Kolleru Lake",          lat: 16.6,  lng: 81.1,  category: "Rivers & Water Bodies",        significance: "Freshwater lake in Andhra Pradesh between Krishna and Godavari deltas. Ramsar Wetland site. Important for migratory birds; supports aquaculture and local fishing communities." },
  { year: 2017, number: 7,  name: "Bhopal Gas Plant Site", lat: 23.3,  lng: 77.4,  category: "Minerals & Industry",          significance: "Site of 1984 Union Carbide disaster in Madhya Pradesh. Worst industrial accident in history. Raised global awareness of chemical safety and corporate accountability in developing nations." },
  { year: 2017, number: 8,  name: "Sangai",                lat: 24.5,  lng: 93.8,  category: "Wildlife & Biosphere",         significance: "Brow-antlered deer (state animal of Manipur) found in Keibul Lamjao National Park. World's only floating national park on Loktak Lake. Critically endangered species endemic to Manipur." },
  { year: 2017, number: 9,  name: "Talcher",               lat: 20.9,  lng: 85.2,  category: "Minerals & Industry",          significance: "Coal mining town in Odisha. Part of Mahanadi coalfields — one of India's richest coal reserves. Houses Talcher Super Thermal Power Station; important for Odisha's industrial economy." },
  { year: 2017, number: 10, name: "Chilika Lake",          lat: 19.7,  lng: 85.3,  category: "Rivers & Water Bodies",        significance: "Asia's largest coastal lagoon in Odisha. First Indian Ramsar site. Hosts Irrawaddy dolphins, flamingos and migratory birds. Important for fisheries and ecotourism." },
  // ── 2018 ──
  { year: 2018, number: 1,  name: "Vijayawada",            lat: 16.5,  lng: 80.6,  category: "Cultural & Heritage",          significance: "City on Krishna River in Andhra Pradesh. Commercial capital of AP. Houses Prakasam Barrage; important for agriculture, trade and as a transport junction of south India." },
  { year: 2018, number: 2,  name: "Orang",                 lat: 26.5,  lng: 92.1,  category: "Wildlife & Biosphere",         significance: "National Park and Tiger Reserve in Assam on Brahmaputra's north bank. Called 'Mini Kaziranga'. Supports one-horned rhinoceros, tigers and Gangetic river dolphins." },
  { year: 2018, number: 3,  name: "Zojila Pass",           lat: 34.3,  lng: 75.5,  category: "Mountains, Passes & Plateaus", significance: "Strategic mountain pass in J&K on NH-1. Connects Srinagar to Leh; only link during winter. Zojila tunnel project will provide all-weather connectivity to Ladakh." },
  { year: 2018, number: 4,  name: "Barren Island",         lat: 12.3,  lng: 93.9,  category: "Islands & Union Territories",  significance: "India's only active volcano in Andaman Sea. Uninhabited island in Andaman archipelago. Important for geological research; volcanic activity studied for tectonic understanding of the region." },
  { year: 2018, number: 5,  name: "Loktak Lake",           lat: 24.5,  lng: 93.8,  category: "Rivers & Water Bodies",        significance: "Largest freshwater lake in northeast India in Manipur. Famous for floating phumdis (biomass). Ramsar site; contains Keibul Lamjao — world's only floating national park." },
  { year: 2018, number: 6,  name: "Bhitarkanika",         lat: 20.7,  lng: 86.9,  category: "Wildlife & Biosphere",         significance: "Mangrove forest and wildlife sanctuary in Odisha. Ramsar Wetland. Largest saltwater crocodile population in India; important for Olive Ridley sea turtle conservation." },
  { year: 2018, number: 7,  name: "Thoothukudi",          lat: 8.8,   lng: 78.1,  category: "Ports & Coastal",              significance: "Port city in Tamil Nadu (formerly Tuticorin). Major sea port for container traffic and salt production. Hosts thermal power plant; gateway for Sri Lanka trade." },
  { year: 2018, number: 8,  name: "Ramagundam",           lat: 18.8,  lng: 79.5,  category: "Minerals & Industry",          significance: "Thermal power station in Telangana on Godavari River. One of India's largest thermal plants. Part of NTPC network; important for Andhra Pradesh and Telangana power supply." },
  { year: 2018, number: 9,  name: "Nathula Pass",         lat: 27.4,  lng: 88.8,  category: "International & Border",       significance: "Mountain pass on India-China border in Sikkim. Reopened in 2006 for bilateral trade. Important for Sino-Indian relations; used by pilgrims en route to Mansarovar." },
  { year: 2018, number: 10, name: "Mudumalai",            lat: 11.6,  lng: 76.6,  category: "Wildlife & Biosphere",         significance: "Tiger Reserve and National Park in Tamil Nadu at tri-junction of Tamil Nadu, Karnataka and Kerala. Part of Nilgiri Biosphere Reserve. Elephant corridor of great ecological significance." },
  // ── 2019 ──
  { year: 2019, number: 1,  name: "Nangal Dam",           lat: 31.5,  lng: 76.4,  category: "Dams & Hydropower",            significance: "Dam on Sutlej River in Punjab. Part of Bhakra-Nangal project — India's largest multipurpose river project. Critical for irrigation of Punjab, Haryana and Rajasthan farmlands." },
  { year: 2019, number: 2,  name: "Simlipal",             lat: 21.8,  lng: 86.4,  category: "Wildlife & Biosphere",         significance: "Tiger Reserve and Biosphere Reserve in Odisha. Part of UNESCO MAB network. Hosts Bengal tigers, elephants, gaur; rich in Sal forests and seasonal streams of Odisha plateau." },
  { year: 2019, number: 3,  name: "Gandak River",         lat: 26.2,  lng: 84.5,  category: "Rivers & Water Bodies",        significance: "Tributary of Ganga rising in Nepal (Narayani). Forms part of India-Nepal border. Gandak Project provides irrigation and power; significant for Bihar's agricultural economy." },
  { year: 2019, number: 4,  name: "Walong",               lat: 28.1,  lng: 97.0,  category: "Defence & Strategic",          significance: "Remote town in Arunachal Pradesh near China border. Site of 1962 Sino-Indian War battle. Important military outpost; easternmost point of Indian Army operations during the conflict." },
  { year: 2019, number: 5,  name: "Chikmagalur",          lat: 13.3,  lng: 75.8,  category: "Mountains, Passes & Plateaus", significance: "Hill station in Karnataka's Western Ghats. Birthplace of coffee in India (Baba Budan Hills). Important for coffee cultivation, biodiversity and tourism in the Sahyadri range." },
  { year: 2019, number: 6,  name: "Bhoj Wetland",         lat: 23.2,  lng: 77.3,  category: "Rivers & Water Bodies",        significance: "Twin lakes near Bhopal — Upper Lake (Bada Talab) and Lower Lake. Ramsar Wetland site. Supports migratory birds; important for Bhopal's drinking water supply and ecology." },
  { year: 2019, number: 7,  name: "Kancheepuram",         lat: 12.8,  lng: 79.7,  category: "Cultural & Heritage",          significance: "Historic temple city in Tamil Nadu. Known as 'City of Thousand Temples'. Famous for Kanjivaram silk sarees; major pilgrimage centre of South India on Palar River." },
  { year: 2019, number: 8,  name: "Vembanad Lake",        lat: 9.5,   lng: 76.4,  category: "Rivers & Water Bodies",        significance: "Longest lake in India in Kerala. Ramsar Wetland. Part of backwater network; important for houseboats tourism, fishing and Kuttanad's below-sea-level paddy cultivation." },
  { year: 2019, number: 9,  name: "Raipur",               lat: 21.2,  lng: 81.6,  category: "Minerals & Industry",          significance: "Capital of Chhattisgarh. Centre of India's iron and steel industry in mineral-rich Chota Nagpur plateau extension. Smart City initiative; rapidly developing industrial hub." },
  { year: 2019, number: 10, name: "Tista River",          lat: 27.0,  lng: 88.5,  category: "Rivers & Water Bodies",        significance: "River in Sikkim and West Bengal; tributary of Brahmaputra. Subject of India-Bangladesh water-sharing dispute. Important for hydropower in Sikkim; Teesta Barrage at Jalpaiguri." },
  // ── 2020 ──
  { year: 2020, number: 1,  name: "Dhola-Sadiya Bridge",  lat: 27.8,  lng: 95.4,  category: "Defence & Strategic",          significance: "Longest river bridge in India over Lohit River, Assam. Connects Assam to Arunachal Pradesh. Strategic importance for military movement near China border; inaugurated 2017." },
  { year: 2020, number: 2,  name: "Majuli Island",        lat: 27.0,  lng: 94.2,  category: "Rivers & Water Bodies",        significance: "World's largest river island in Brahmaputra, Assam. UNESCO tentative list site. Centre of Vaishnavite culture (satras); facing severe erosion threatening its existence." },
  { year: 2020, number: 3,  name: "Aravalli Range",       lat: 25.0,  lng: 73.5,  category: "Mountains, Passes & Plateaus", significance: "World's oldest fold mountains in Rajasthan. Natural barrier against Thar Desert's eastward expansion. Rich in non-ferrous minerals; Delhi Ridge is its northernmost extension." },
  { year: 2020, number: 4,  name: "Silent Valley",        lat: 11.1,  lng: 76.5,  category: "Wildlife & Biosphere",         significance: "National Park in Kerala's Nilgiri Hills. Last undisturbed tropical evergreen forest in India. Saved from hydro project in 1980s; rich in lion-tailed macaques and endemic species." },
  { year: 2020, number: 5,  name: "Bhitarkanika",        lat: 20.7,  lng: 86.9,  category: "Wildlife & Biosphere",         significance: "Mangrove ecosystem in Odisha delta region. Ramsar Wetland; second largest mangrove forest in India. Hosts saltwater crocodile and migratory birds; critical coastal ecosystem." },
  { year: 2020, number: 6,  name: "Lakshadweep",         lat: 10.5,  lng: 72.6,  category: "Islands & Union Territories",  significance: "Coral archipelago in Arabian Sea; India's smallest union territory. EEZ of 400,000 sq km crucial for maritime security. Coral reefs and lagoons support unique marine biodiversity." },
  { year: 2020, number: 7,  name: "Sardar Sarovar Dam",  lat: 21.8,  lng: 73.7,  category: "Dams & Hydropower",            significance: "Dam on Narmada River in Gujarat. Largest water resource project in India by volume. Beneficiary states: Gujarat, Madhya Pradesh, Maharashtra, Rajasthan; long-running controversy over displacement." },
  { year: 2020, number: 8,  name: "Borra Caves",         lat: 18.3,  lng: 83.1,  category: "Mountains, Passes & Plateaus", significance: "Limestone caves in Araku Valley, Andhra Pradesh's Eastern Ghats. Largest caves in India; stalactite and stalagmite formations. Tourist destination in tribal Visakhapatnam district." },
  { year: 2020, number: 9,  name: "Mahi River",          lat: 22.8,  lng: 73.2,  category: "Rivers & Water Bodies",        significance: "West-flowing river in Rajasthan and Gujarat. Originates in Vindhyas; drains into Gulf of Khambhat. Kadana and Mahi Bajaj Sagar dams on it; important for Gujarat's irrigation." },
  { year: 2020, number: 10, name: "Pangong Lake",        lat: 33.7,  lng: 78.9,  category: "International & Border",       significance: "High-altitude lake on India-China border in Ladakh. 60% lies in China. Site of 2020 India-China standoff. Migratory birds breed here; unique saline water body at 4,350m altitude." },
  // ── 2021 ──
  { year: 2021, number: 1,  name: "Nathu La Pass",       lat: 27.4,  lng: 88.8,  category: "International & Border",       significance: "Mountain pass in Sikkim on India-China border. Part of ancient Silk Road. Reopened for trade in 2006; used by Kailash Mansarovar Yatra pilgrims. Strategic military importance." },
  { year: 2021, number: 2,  name: "Khecheopalri Lake",   lat: 27.4,  lng: 88.2,  category: "Rivers & Water Bodies",        significance: "Sacred lake in Sikkim near Yuksam. 'Wish-fulfilling lake' in Buddhist tradition. Fed by glacial streams; self-cleaning property as birds remove fallen leaves. Ecotourism site." },
  { year: 2021, number: 3,  name: "Kanger Valley",       lat: 19.0,  lng: 81.9,  category: "Wildlife & Biosphere",         significance: "National Park in Bastar, Chhattisgarh. Contains Kotumsar Cave — one of longest caves in India. Rich in tribal culture; biodiversity hotspot with hill myna and bastar hill mynahs." },
  { year: 2021, number: 4,  name: "Cauvery River",       lat: 11.9,  lng: 78.2,  category: "Rivers & Water Bodies",        significance: "River in Karnataka and Tamil Nadu. Lifeline of south India's agriculture. Cauvery water dispute between Karnataka and Tamil Nadu is one of India's longest interstate water conflicts." },
  { year: 2021, number: 5,  name: "Guru Shikhar",        lat: 24.7,  lng: 72.7,  category: "Mountains, Passes & Plateaus", significance: "Highest peak of Aravalli Range in Rajasthan at 1722m. Located in Mount Abu. Houses astronomical observatory; pilgrimage site with Dattatreya temple at summit." },
  { year: 2021, number: 6,  name: "Morbi",               lat: 22.8,  lng: 70.8,  category: "Minerals & Industry",          significance: "City in Gujarat on Machhu River. Ceramic and tile manufacturing capital of India. Site of 1979 Machhu dam disaster. Known for clock manufacturing and decorative tiles industry." },
  { year: 2021, number: 7,  name: "Dehing Patkai",       lat: 27.3,  lng: 95.8,  category: "Wildlife & Biosphere",         significance: "National Park in Assam — India's last remaining lowland rainforest. Elephant corridor connecting Arunachal Pradesh. Rich in hornbills, gibbons and clouded leopards." },
  { year: 2021, number: 8,  name: "Paradip Port",        lat: 20.3,  lng: 86.6,  category: "Ports & Coastal",              significance: "Major port in Odisha handling iron ore exports and crude oil imports. Developed as a deep-water port. Connects hinterland of Jharkhand and Odisha to maritime trade routes." },
  { year: 2021, number: 9,  name: "Garo Hills",          lat: 25.5,  lng: 90.3,  category: "Mountains, Passes & Plateaus", significance: "Hill range in Meghalaya separating Brahmaputra and Surma-Meghna basins. Home to Garo tribe. Nokrek Biosphere Reserve located here; rich in biodiversity and root bridges." },
  { year: 2021, number: 10, name: "Pong Dam Lake",       lat: 32.0,  lng: 76.1,  category: "Dams & Hydropower",            significance: "Reservoir on Beas River in Himachal Pradesh. Ramsar Wetland site. Important for irrigation of Punjab and Haryana; migratory bird habitat especially Bar-headed goose." },
  // ── 2022 ──
  { year: 2022, number: 1,  name: "Lepakshi",            lat: 13.8,  lng: 77.6,  category: "Cultural & Heritage",          significance: "Temple complex in Andhra Pradesh. Houses India's largest Nandi bull sculpture and hanging pillar. Vijayanagara-era frescoes and monuments; significant for art history and archaeology." },
  { year: 2022, number: 2,  name: "Hogenakkal Falls",    lat: 12.1,  lng: 77.8,  category: "Rivers & Water Bodies",        significance: "Waterfall on Cauvery River at Tamil Nadu-Karnataka border. Known as 'Smoking Rocks'. Popular tourist destination; site of proposed Hogenakkal drinking water project for Tamil Nadu." },
  { year: 2022, number: 3,  name: "Moreh",               lat: 24.2,  lng: 94.3,  category: "International & Border",       significance: "Border town in Manipur on India-Myanmar border. Key trade post on India-Myanmar-Thailand Trilateral Highway. Important for Act East Policy and connectivity with Southeast Asia." },
  { year: 2022, number: 4,  name: "Dampa Tiger Reserve", lat: 23.5,  lng: 92.5,  category: "Wildlife & Biosphere",         significance: "Largest wildlife sanctuary in Mizoram. Westernmost tiger reserve in India's northeast. Rich in biodiversity; supports hoolock gibbons, clouded leopards and rare orchids." },
  { year: 2022, number: 5,  name: "Bhavnagar",           lat: 21.8,  lng: 72.2,  category: "Ports & Coastal",              significance: "Port city in Gujarat on Gulf of Khambhat. Known for ship-breaking industry at Alang — world's largest ship recycling yard. Tidal port; important for diamond trade and textiles." },
  { year: 2022, number: 6,  name: "Purna River",         lat: 20.8,  lng: 77.0,  category: "Rivers & Water Bodies",        significance: "Tributary of Tapi River in Maharashtra and Gujarat. Important for irrigation in Vidarbha. Flows through tribal areas; Lower Purna project supports agricultural development." },
  { year: 2022, number: 7,  name: "Joshimath",           lat: 30.6,  lng: 79.6,  category: "Cultural & Heritage",          significance: "Town in Uttarakhand; gateway to Badrinath. Adi Shankaracharya's winter seat. Facing land subsidence crisis due to overdevelopment; importance for Char Dham Yatra pilgrims." },
  { year: 2022, number: 8,  name: "Deomali",             lat: 18.4,  lng: 83.0,  category: "Mountains, Passes & Plateaus", significance: "Highest peak of Odisha at 1672m in Koraput district's Eastern Ghats. Located in biodiversity-rich tribal region. Source area for several streams; important for forest conservation." },
  { year: 2022, number: 9,  name: "Kalpakkam",           lat: 12.6,  lng: 80.2,  category: "Nuclear & Space",              significance: "Nuclear power complex in Tamil Nadu near Chennai. Houses India's first Fast Breeder Reactor (Prototype FBR). Part of India's three-stage nuclear power programme for thorium utilisation." },
  { year: 2022, number: 10, name: "Kochi",               lat: 9.9,   lng: 76.3,  category: "Ports & Coastal",              significance: "Major port city in Kerala. 'Queen of the Arabian Sea'; hub for international container traffic. India's first fully solar-powered airport; important for Kerala's tourism and trade." },
  // ── 2023 ──
  { year: 2023, number: 1,  name: "Agatti Island",       lat: 10.8,  lng: 72.2,  category: "Islands & Union Territories",  significance: "One of the islands in Lakshadweep with an airport. Serves as entry point to the coral archipelago. Ecologically sensitive coral ecosystem; important for India's maritime EEZ in Arabian Sea." },
  { year: 2023, number: 2,  name: "Khavda",              lat: 23.8,  lng: 69.7,  category: "Minerals & Industry",          significance: "Village in Kutch, Gujarat. Site of Adani's massive renewable energy park — world's largest. Located in Rann of Kutch region; India's push for solar and wind energy in a desert landscape." },
  { year: 2023, number: 3,  name: "Barak River",         lat: 24.9,  lng: 92.8,  category: "Rivers & Water Bodies",        significance: "Major river in Manipur and Assam flowing into Bangladesh. Forms Surma and Kushiyara rivers. Tipaimukh dam controversy due to impact on Bangladesh. Important for northeast India's water economy." },
  { year: 2023, number: 4,  name: "Phawngpui",           lat: 22.6,  lng: 93.0,  category: "Mountains, Passes & Plateaus", significance: "Highest peak of Mizoram at 2157m; also called Blue Mountain. National Park at its base. Culturally significant for Mizo people; rich in Himalayan black bears and rare orchids." },
  { year: 2023, number: 5,  name: "Lingaraj Temple",     lat: 20.2,  lng: 85.8,  category: "Cultural & Heritage",          significance: "11th century Shaivite temple in Bhubaneswar, Odisha. Finest example of Kalinga architecture. Dedicated to Harihara (fusion of Shiva and Vishnu); one of India's most important pilgrimage sites." },
  { year: 2023, number: 6,  name: "Devarapalli",         lat: 17.5,  lng: 82.1,  category: "Minerals & Industry",          significance: "Village in Andhra Pradesh. Associated with bauxite mining in Eastern Ghats. Part of Visakhapatnam-Chennai industrial corridor; tribal region facing displacement due to mining projects." },
  { year: 2023, number: 7,  name: "Kaiga",               lat: 14.9,  lng: 74.5,  category: "Nuclear & Space",              significance: "Nuclear Power Station in Karnataka on Kali River. Holds world record for longest continuous operation of pressurised heavy water reactor. Important for southern grid power supply." },
  { year: 2023, number: 8,  name: "Umiam Lake",          lat: 25.7,  lng: 91.9,  category: "Rivers & Water Bodies",        significance: "Reservoir near Shillong, Meghalaya. Created by Umiam hydroelectric project. Popular tourism destination; important for Meghalaya's power generation and Shillong's water supply." },
  { year: 2023, number: 9,  name: "Sandakphu",           lat: 27.1,  lng: 88.0,  category: "Mountains, Passes & Plateaus", significance: "Highest point of West Bengal at 3636m on Nepal border. Only place to see four of world's five highest peaks together. Trekking destination in Singalila National Park." },
  { year: 2023, number: 10, name: "Vadinar Port",        lat: 22.5,  lng: 69.4,  category: "Ports & Coastal",              significance: "Deep-water crude oil terminal in Gujarat near Jamnagar. Handles largest oil tankers; connected to Jamnagar refinery complex — world's largest refinery. Key for India's petroleum imports." },
  // ── 2024 ──
  { year: 2024, number: 1,  name: "Simhachalam Temple",  lat: 17.8,  lng: 83.3,  category: "Cultural & Heritage",          significance: "11th century Vaishnavite temple near Visakhapatnam, Andhra Pradesh. Dedicated to Narasimha (Varaha Lakshmi Narasimha). Fine example of Kalinga and Chalukyan architectural fusion." },
  { year: 2024, number: 2,  name: "Pong Dam",            lat: 32.0,  lng: 76.1,  category: "Dams & Hydropower",            significance: "Earthen dam on Beas River in Himachal Pradesh. Creates Maharana Pratap Sagar — a Ramsar Wetland. Supplies water and power to Punjab, Haryana and Rajasthan under Beas-Sutlej project." },
  { year: 2024, number: 3,  name: "Senchal Lake",        lat: 27.1,  lng: 88.3,  category: "Rivers & Water Bodies",        significance: "Lake near Darjeeling at 2400m altitude. Main water source for Darjeeling town. Wildlife sanctuary around it protects biodiversity of Eastern Himalayan foothills." },
  { year: 2024, number: 4,  name: "Jakhu Peak",          lat: 31.1,  lng: 77.2,  category: "Mountains, Passes & Plateaus", significance: "Highest peak near Shimla, Himachal Pradesh at 2455m. Houses Hanuman temple (Jakhu Temple). Forested summit important for ecology and tourism in the Shivalik range." },
  { year: 2024, number: 5,  name: "Sukhna Lake",         lat: 30.7,  lng: 76.8,  category: "Rivers & Water Bodies",        significance: "Reservoir at Chandigarh foothills of Shivaliks. Maintained by Chandigarh administration; popular recreational lake. Rainwater-fed reservoir facing siltation from deforestation in catchment." },
  { year: 2024, number: 6,  name: "Bongaigaon",         lat: 26.5,  lng: 90.6,  category: "Minerals & Industry",          significance: "Industrial town in Assam. Houses Numaligarh and Bongaigaon Refineries — important petroleum refineries of northeast India. Railway junction serving as regional trade centre." },
  { year: 2024, number: 7,  name: "Gadadhar River",      lat: 26.0,  lng: 90.0,  category: "Rivers & Water Bodies",        significance: "River in Assam-Meghalaya border area. Tributary of Brahmaputra drainage basin. Important for seasonal floods and local irrigation in the Brahmaputra floodplain agricultural economy." },
  { year: 2024, number: 8,  name: "Rampa",               lat: 17.4,  lng: 81.7,  category: "Cultural & Heritage",          significance: "Region in Andhra Pradesh associated with the 1922 Rampa Rebellion led by Alluri Sitarama Raju. Tribal forested area in Eastern Ghats bordering Telangana." },
  { year: 2024, number: 9,  name: "Phongngoi",           lat: 24.5,  lng: 93.5,  category: "Wildlife & Biosphere",         significance: "Village in Manipur associated with Loktak Lake ecosystem. Located in the phumdis region. Important for the traditional fishing practices of Meitei community around Keibul Lamjao area." },
  { year: 2024, number: 10, name: "Dhanushkodi",         lat: 9.2,   lng: 79.4,  category: "Ports & Coastal",              significance: "Abandoned town at southeastern tip of Pamban Island, Tamil Nadu. Closest point to Sri Lanka (31 km). Destroyed in 1964 cyclone; near Rama Setu (Adam's Bridge) underwater formation." },
  // ── 2025 ──
  { year: 2025, number: 1,  name: "Rushikulya River",    lat: 19.4,  lng: 84.8,  category: "Rivers & Water Bodies",        significance: "River in Odisha draining eastern ghats into Bay of Bengal. Major Olive Ridley sea turtle mass nesting site. Ecologically critical estuary; important for local fishermen communities." },
  { year: 2025, number: 2,  name: "Datar Hill",          lat: 22.3,  lng: 70.4,  category: "Mountains, Passes & Plateaus", significance: "Isolated hill in Kathiawar peninsula, Gujarat. Pilgrimage site; surrounding region known for groundnut cultivation and fisheries. Geological significance in Deccan trap landscape." },
  { year: 2025, number: 3,  name: "Kikruma",             lat: 25.9,  lng: 94.3,  category: "Cultural & Heritage",          significance: "Village in Nagaland hill district. Remote settlement in biodiversity-rich eastern Himalayas. Represents traditional Naga culture; significance for forest conservation and tribal land rights." },
  { year: 2025, number: 4,  name: "Choritand Tillaya",   lat: 24.0,  lng: 85.6,  category: "Dams & Hydropower",            significance: "DVC dam site in Jharkhand on Damodar River. Provides hydropower and flood moderation. Located in mineral-rich Chota Nagpur plateau; important for eastern India's industrial corridor." },
  { year: 2025, number: 5,  name: "Byalalu",             lat: 13.1,  lng: 77.4,  category: "Nuclear & Space",              significance: "ISRO's Indian Deep Space Network (IDSN) facility near Bengaluru. Tracks deep space missions including Chandrayaan and Mangalyaan. Strategically important for India's space programme." },
  { year: 2025, number: 6,  name: "Neyyar",              lat: 8.5,   lng: 77.1,  category: "Wildlife & Biosphere",         significance: "Reservoir and wildlife sanctuary in Thiruvananthapuram district, Kerala. Western Ghats biodiversity hotspot. Supports lion-tailed macaque; important irrigation source for southern Kerala." },
  { year: 2025, number: 7,  name: "Uttarlai",            lat: 25.9,  lng: 71.3,  category: "Defence & Strategic",          significance: "Air Force base in Barmer, Rajasthan near Pakistan border. Strategic defence installation in Thar Desert. Important for aerial surveillance and defence of India's western frontier." },
  { year: 2025, number: 8,  name: "Sri Vijayapuram",     lat: 11.7,  lng: 92.7,  category: "Islands & Union Territories",  significance: "New name for Port Blair, capital of Andaman and Nicobar Islands. Commands sea lanes near Malacca Strait. Strategic maritime importance; India's military base in Bay of Bengal." },
  { year: 2025, number: 9,  name: "Dharwas",             lat: 15.5,  lng: 74.9,  category: "Minerals & Industry",          significance: "Town in Dharwad district on Karnataka plateau. Known for cotton textile industry and educational institutions. Proximity to iron ore and manganese mining areas in north Karnataka." },
  { year: 2025, number: 10, name: "Gitabitan",           lat: 22.6,  lng: 88.4,  category: "Cultural & Heritage",          significance: "Rabindranath Tagore's residence and cultural institution in Kolkata. Repository of his manuscripts and artefacts. Represents Bengal Renaissance heritage in the Gangetic delta cultural landscape." },
];

export const geoMapYears = [...new Set(geoMapData.map(e => e.year))].sort((a, b) => b - a);
