// Note content for Geography Optional
// Format: slug -> HTML string

export const geographyNoteContent: Record<string, string> = {
  'geomorphology-fundamentals': `
<h2>Geomorphology: Scope and Significance</h2>

<p>Geomorphology is the scientific study of landforms and the processes responsible for their creation, development, and eventual destruction. A landform is understood as an outcome of three interacting variables: structure, process, and time. Structure refers to the mineral composition, type, and arrangement of rocks, including whether they are jointed or compact. Process refers to the dominant geomorphic agent operating on the landform, such as glaciers, rivers, or wind. Time determines the stage of development, broadly classified as youthful, mature, or old age. Because endogenetic forces that raise the land surface and exogenetic forces that wear it down operate simultaneously, the height and character of any landform at a given moment reflects the net result of both sets of forces working together over geological time.</p>

<h2>Endogenetic and Exogenetic Forces</h2>

<p>Endogenetic forces originate from within the earth and are termed constructive forces because they increase the relief of the land. They are further divided into diastrophic forces, which operate very slowly and include the processes of folding and faulting, and catastrophic forces, which are sudden and include earthquakes and volcanic eruptions. Within diastrophic forces, epeirogenetic forces are responsible for continent building through broad vertical movements of emergence and submergence, while orogenetic forces produce mountains through folding and faulting.</p>

<p>Exogenetic forces originate at or near the earth's surface and are termed destructive forces because they continuously lower the height of landforms. These forces of denudation include weathering, mass movement such as landslides, and erosion by rivers, glaciers, wind, and waves. Together, weathering and erosion gradually reduce elevated landforms toward base level, producing a variety of characteristic landforms along the way. Applied geomorphology draws on this understanding for practical purposes including geohydrology, economic geology, and environmental management.</p>

<h2>Origin and Evolution of the Earth's Crust</h2>

<p>The earth formed approximately 4.5 billion years ago. In its earliest state it was dominated by hydrogen, helium, carbon dioxide, and nitrogen, with no free oxygen present. The geological time scale divides earth history into eons, which are subdivided into eras, which are further divided into periods and epochs. The Pre-Cambrian era saw the formation of oceans, the origin of the oldest fold mountains including the Aravallis, and the appearance of the earliest life in the form of anaerobic bacteria. Blue-green algae appeared around 2,500 million years ago, initiating photosynthesis and beginning the slow oxygenation of the atmosphere.</p>

<p>The Paleozoic era included the Cambrian period characterised by marine invertebrates, the Devonian period known as the age of fishes, and the Carboniferous period during which vast quantities of vegetation were buried and compressed to form most of the world's coal. Indian coal is younger, belonging to the Gondwana period. Coal is classified by age and quality from older anthracite through bituminous and lignite to the youngest peat. About 98 percent of India's coal is of Gondwana bituminous variety, found in the valleys of rivers such as the Damodar, Mahanadi, Godavari, and Subernarekha on the Chhotanagpur plateau.</p>

<p>The Mesozoic era is divided into the Triassic, Jurassic, and Cretaceous periods. The Cretaceous period was marked by large-scale volcanic activity that led to the extinction of dinosaurs through a combination of global cooling and, according to some accounts, meteor impact. The massive outpourings of basaltic lava during this period formed volcanic plateaus such as the Deccan Lava Plateau of India, the Siberian Plateau of Russia, and the Columbia Snake Plateau of the United States. The Cenozoic era includes the Tertiary period during which young fold mountains such as the Himalayas were formed, and the Quaternary period which includes the Pleistocene ice ages and the Holocene epoch leading to modern human evolution. The Anthropocene is defined as the last approximately two thousand years during which modern humans have substantially modified the atmosphere and climate through deforestation, agriculture, land use change, and the burning of fossil fuels.</p>

<h2>Interior of the Earth</h2>

<p>The earth's interior is divided into three concentric layers: the crust, the mantle, and the core. Direct study of the interior is limited by extreme pressure and temperature, with the deepest mines reaching only about 3.2 kilometres. Indirect evidence comes from the study of volcanoes, which originate from the asthenosphere at depths of around 200 kilometres, and from meteors, whose analysis suggests that the earth's interior is composed of increasingly denser materials. The study of seismic waves is the most reliable source of information about the earth's layered structure.</p>

<p>The crust is the outermost layer and is divided into the continental crust and the oceanic crust. The continental crust is composed of lighter materials dominated by silica and aluminium, giving it the chemical shorthand SIAL, and has an average thickness of around 35 kilometres, with considerably greater thickness beneath mountain ranges. The oceanic crust is denser, composed of silica and magnesium and iron, giving it the shorthand SIMA and SIFE, and has an average thickness of only about 5 kilometres, forming the floor of the ocean basins. The boundary between the crust and the mantle is called the Moho discontinuity.</p>

<p>The mantle extends below the crust and is divided into the upper and lower mantle. The uppermost layer combining the crust and the top of the upper mantle is known as the lithosphere, which exists in solid form. Below the lithosphere and extending to a depth of about 200 kilometres is the asthenosphere, which is in a semi-plastic or jelly-like state and serves as the source of magma according to the plate tectonic theory. Lithospheric plates slide on this plastic asthenosphere. The lower mantle is in solid form due to the dominance of pressure over temperature at greater depths, as evidenced by the high velocity of both P-waves and S-waves passing through it.</p>

<p>The core is the innermost layer, composed of the densest materials, primarily nickel and iron. It is divided into the outer core and the inner core. The outer core is in liquid form because temperature increases outpace the pressure increase at those depths. The liquid outer core, combined with the rotation of the earth, generates charged particles that give the earth its geomagnetic properties. The inner core is in solid form due to the extreme pressures at the centre of the earth, a conclusion supported by the fact that P-waves achieve their highest velocities here. The boundary between the mantle and the outer core is called the Gutenberg discontinuity.</p>

<h2>Seismic Waves and the Study of the Earth</h2>

<p>Seismic waves are waves of energy released during earthquakes. They are divided into body waves, which travel through the interior of the earth, and surface waves, which travel along the earth's surface and cause the greatest damage. Body waves are of two types. Primary waves or P-waves are similar to sound waves and can travel through solids, liquids, and gases. They cause rocks to move parallel to the direction of wave propagation through compression and rarefaction, and they are the fastest body waves. Secondary waves or S-waves travel at approximately half the speed of P-waves and cause particles to move perpendicular to the direction of wave propagation. S-waves can pass only through solid material.</p>

<p>The behaviour of seismic waves as they pass through the earth's interior provides the clearest evidence for the layered structure of the earth. Waves change direction and velocity when they move from one medium to another of different density, a phenomenon known as refraction. The sudden changes in wave behaviour at the crust-mantle boundary and the mantle-core boundary define the Moho and Gutenberg discontinuities respectively. The fact that S-waves do not pass through the outer core conclusively proves that the outer core is in a liquid state. The shadow zone of S-waves, the region on the opposite side of the earth from an earthquake where S-waves cannot be detected, is larger than the shadow zone of P-waves for the same reason.</p>

<h2>Continental Drift Theory</h2>

<p>Alfred Wegener proposed the Continental Drift Theory in 1912. He argued that before the Carboniferous period all the continents were joined into a single supercontinent called Pangea, surrounded by a single super ocean called Panhalassa. During the Carboniferous period Pangea broke into two parts: the northern mass known as Laurasia or Angaraland, and the southern mass known as Gondwanaland. As drifting continued, Laurasia broke into North America and Eurasia while Gondwanaland broke into South America, Africa, Madagascar, Peninsular India, Australia, and Antarctica. The westward drifting of the Americas opened the Atlantic Ocean. The northward drifting of India and Africa reduced the Tethys Sea, whose remnant is the present Mediterranean Sea, and opened the Indian Ocean. According to Wegener, the folding of continental margins during drift created fold mountains such as the Rockies and the Andes.</p>

<p>Wegener proposed that two forces drove the drift: tidal forces from the gravitational pull of the sun and moon driving westward movement, and gravitational buoyancy forces of the earth driving northward movement. The theory is supported by several lines of evidence. The jigsaw fit of continental coastlines, particularly the matching profiles of Africa and South America, was the most visible evidence. Rocks of the same age and type are found on either side of the Atlantic, and the Appalachians of North America share characteristics with mountains of Ireland and Scandinavia, suggesting they were once joined. Gold-bearing rocks occur in both western Africa and eastern South America. Similar plant fossils of the Glossopteris flora are found in Brazil, Africa, Peninsular India, and Australia. Evidence of glaciation in all these regions in the distant past cannot be explained by their present positions. The behaviour of lemmings in Scandinavia, which run westward and fall into the sea, was cited as evidence of a westward continental memory.</p>

<p>Despite its insights, the theory faced several criticisms. Wegener could not adequately explain the forces responsible for the drift, since tidal forces are too weak to move entire continents. He also failed to explain the trigger mechanism for the initial breaking of Pangea and could not account for the detailed sequence of separation. Arthur Holmes subsequently proposed the Convection Current Theory, arguing that heat-driven convection currents in the mantle could both cause the break-up and drive the movement of continents, providing a mechanism that Wegener's theory lacked.</p>

<h2>Sea Floor Spreading</h2>

<p>Harry Hess proposed the Sea Floor Spreading Theory, which became a crucial link between Wegener's Continental Drift Theory and the later Plate Tectonic Theory. Hess argued that the ocean floor behaves like a conveyor belt, being continuously created along mid-oceanic ridges through the upwelling of magma, and continuously destroyed at ocean trenches. Rising convective currents in the mantle break apart the oceanic crust at divergent boundaries, and as magma cools and solidifies it creates new ridge material. The oldest oceanic crust is found nearest the trenches, while the youngest is found at the ridges.</p>

<p>Evidence for sea floor spreading includes the existence of mid-oceanic ridges as the longest continuous mountain chain on earth at approximately 78,000 kilometres. Rocks at equal distances from mid-oceanic ridges have the same age, with younger rocks nearest the ridge and older rocks on either side. Greater ocean temperatures are recorded at the tops of mid-oceanic ridges due to ongoing volcanic activity. The continental crust is approximately 4.2 billion years old while the oceanic crust is only a few million years old, which would be inexplicable if the ocean floor had not been continuously renewed. The study of palaeomagnetism, which examines the frozen magnetic properties of older rocks, shows symmetrical magnetic stripes on either side of mid-oceanic ridges, recording repeated reversals of the earth's magnetic field as new ocean floor was formed.</p>

<h2>Plate Tectonic Theory</h2>

<p>The Plate Tectonic Theory synthesises the insights of continental drift and sea floor spreading into a comprehensive framework. The earth's lithosphere is divided into several large and small solid plates that ride on the semi-plastic asthenosphere. These plates are driven by convection currents in the mantle. The major plates are the North American, South American, Pacific, African, Eurasian, Indo-Australian, and Antarctic plates. The Pacific plate is the only major plate that is entirely oceanic. The Eurasian plate is largely continental. Important minor plates include the Nasca, Cocos, Juan de Fuca, Arabian, Philippine, and Burma plates. The interaction of the Burma and Indian plates was responsible for the 2004 Indian Ocean Tsunami.</p>

<p>Plate boundaries are of three types. Convergent or destructive boundaries occur where two plates move toward each other and are associated with fold mountains, ocean trenches, earthquakes, and volcanic eruptions. Divergent or constructive boundaries occur where plates move apart and are associated with mid-oceanic ridges, fissure volcanoes, and rift valleys. Transform or conservative boundaries occur where plates slide past each other and are associated with powerful earthquakes and faults such as the San Andreas fault system and the Great East African Rift Valley.</p>

<p>Continent-ocean convergence is the most common type of plate collision, occurring where a denser oceanic plate subducts beneath a lighter continental plate. The subducting plate descends into the mantle, melts, and the resulting pressure forces magma upward through volcanic eruptions. The sediments caught between the plates are folded upward to form fold mountains, often in the form of long parallel chains known as Cordillera systems. The subduction zone, known as the Benioff zone, forms the deepest trenches on earth. Examples include the Rockies formed by the collision of the Pacific and Juan de Fuca plates with the North American plate, and the Andes formed by the Nasca and South American plates. The Alps were formed by the convergence of the Eurasian and African plates.</p>

<p>Continent-continent convergence occurs where both plates are of similar density and subduction does not take place. Instead, the plate of slightly greater density or velocity slides beneath the other in a process called obduction, causing a doubling of the earth's crust, which explains the absence of volcanoes in these regions. The Himalayas are the classic example, formed by the collision of the Indian and Eurasian plates. The Indian plate separated from Gondwanaland in the Mesozoic era and drifted northward, with its western portion passing over the Reunion Hotspot and generating the Deccan Lava Plateau. The floors of the Tethys geosyncline were subducted to form the Trans-Himalayan ranges north of the main Himalayas. The collision took place in three phases, producing the three parallel ranges of the Himalayas. The Shivaliks, the youngest range, formed around 2 to 20 million years ago. The Himalayas continue to rise at a rate of 5 to 10 centimetres per year as the Indian plate continues to move northward beneath the Eurasian plate.</p>

<p>Ocean-ocean convergence occurs where both plates are oceanic. The denser or faster-moving plate subducts and the sediments of both plates are folded into submarine mountains. As lava builds up, these mountains project above the ocean surface forming island arcs or archipelagos. The Caribbean Island Arc was formed by the subduction of the North American plate beneath the Caribbean plate, with the Puerto Rico Trench marking the subduction zone. The Japanese Island Arc formed from the interaction of the Eurasian, Pacific, and Philippine plates. The Philippine archipelago was created by the subduction of the Pacific plate beneath the Philippine plate, forming the Mariana Trench, which is the deepest point on earth. The Indonesian Island Arc sits at the trijunction of the Indo-Australian, Pacific, and Asian plates, making it tectonically among the most unstable regions on earth. The Java or Sunda Trench, where the Pacific plate subducts beneath the Indian plate, is the deepest point in the Indian Ocean.</p>

<h2>Folding and Faulting</h2>

<p>Folding occurs when compressive forces from within the earth cause rock layers to buckle and warp rather than break. It produces anticlines, which are upward arches or crests, and synclines, which are downward troughs. A structure where a large anticline carries numerous smaller anticlines and synclines within it is called an anticlinorium, and the corresponding syncline-dominated structure is a synclinorium. Fold types range from symmetrical folds where both limbs are inclined equally, to asymmetrical folds where the limbs are inclined at different angles, to monoclinal folds where one limb is steep and the other gentle. Isoclinal folds have both limbs running nearly parallel to each other due to intense compression. Recumbent folds develop in complex mountain building zones such as the Himalayas, where both limbs become parallel to the ground surface. When the central point of a recumbent fold breaks under further compression, it becomes an overthrust fold, and when the broken limbs are displaced several kilometres apart, the displaced portion is called a nappe.</p>

<p>Faulting is caused by tensional or compressive forces that fracture rocks along lines or zones of weakness called joints. Normal faults are caused by tensional forces pulling rocks apart, resulting in elongation of the crust and producing horst and graben structures. A horst is an uplifted block that forms a block mountain, while a graben is a downthrown block that forms a rift valley. Reverse faults are caused by compressive forces and result in crustal shortening. The Vindhyas and Satpuras of India are examples of block mountains formed by reverse faulting. Step faults occur when displacement takes place in the same vertical direction in successive steps, as seen on the eastern side of the Western Ghats, which are also known as Deccan Traps because the word traps in Swedish means staircase. Lateral faults produce horizontal movement either to the right, called dextral movement, or to the left, called sinistral movement, and are associated with long narrow rift valleys.</p>

<p>The Great Rift Valley is the world's longest rift valley, extending from Syria through the Dead Sea, the Red Sea, Lake Tanganyika, and Lake Nyasa. Lake Baikal in Russia, the world's deepest lake and the largest freshwater lake by volume, occupies a rift valley. The Rhine Rift Valley in Europe lies between the Vosges Mountains of France and the Black Forest of Germany. In India, the Narmada and Tapi rivers flow through rift valleys between the block mountains of the Vindhyas and Satpuras, originating at Amarkantak Plateau and Multai respectively. The rivers Son and Damodar flow through rift valleys in their upper courses.</p>

<h2>Geomorphic Cycles and Landscape Development</h2>

<p>Landscape development is understood as a progressive sequence of change over geological time. The concept of a geomorphic cycle describes how an uplifted landmass is progressively reduced by the agents of erosion. In the youthful stage, rivers cut deeply into the landscape producing V-shaped valleys and steep gradients. In the mature stage, lateral erosion widens valleys, slopes become more gentle, and divides between river basins are reduced. In the old age stage, the landscape is worn down to a nearly flat surface close to sea level known as a peneplain. Rejuvenation, caused by tectonic uplift or a fall in base level, restarts the cycle and introduces features such as incised meanders and river terraces.</p>

<h2>Isostasy</h2>

<p>Isostasy refers to the condition of gravitational equilibrium between the earth's crust and mantle. The concept holds that the lithosphere floats on the denser asthenosphere in a state of balance, and that any change in loading or unloading of the crust triggers a compensatory vertical adjustment. Where the crust is thickened by mountain building, its roots extend deeper into the mantle, much as a floating iceberg has most of its mass below the water surface. When erosion removes material from a mountain range, the reduced load causes the crust to rise isostatically. Conversely, when sediment is deposited in a basin, the added weight causes the crust to subside. The melting of ice sheets at the end of an ice age removes a superincumbent load from the crust, triggering isostatic rebound that is still measurable in formerly glaciated regions such as Scandinavia and Canada. Isostasy is also relevant to understanding how geomagnetic equilibrium is maintained and why the Himalayas experience a doubling of the earth's crust that precludes volcanic activity.</p>
`,

  'rocks-minerals-volcanoes': `
<h2>Rocks and Minerals</h2>

<p>Rocks are aggregations of minerals. Approximately 98 percent of the earth's crust is composed of eight elements: oxygen, silicon, aluminium, iron, calcium, sodium, potassium, and magnesium. The most abundant mineral in the earth's crust is oxygen, while the most abundant element in the entire earth is iron. Rocks are broadly classified as hard or soft depending on their resistance to erosion and weathering. Igneous and metamorphic rocks are generally harder and more resistant, while sedimentary rocks are generally softer and more susceptible to erosion.</p>

<h2>Igneous Rocks</h2>

<p>Igneous rocks are the parent or primary rocks of the earth, being the first to form through the cooling and solidification of magma and lava. They are crystalline in nature, with the size of crystals determined by the rate of cooling. Rapid cooling produces small or no crystals, as seen in extrusive basalt that cools quickly at the surface. Slow cooling deep within the earth allows large, well-formed crystals to develop, as seen in intrusive granite.</p>

<p>On the basis of depth of formation, igneous rocks are classified as extrusive, formed at the surface through volcanic eruptions, and intrusive, formed below the surface through the cooling of magma underground. Intrusive rocks are further divided into hypoabyssal rocks formed at relatively shallow depths and plutonic rocks formed at great depth. On the basis of chemical composition, igneous rocks are classified as acidic or basic. Acidic igneous rocks such as granite are rich in silica and aluminium, lighter in colour, more viscous, and associated with violent eruptions and elevated landforms. Basic igneous rocks such as basalt are rich in iron and magnesium, darker in colour, more fluid, and associated with fissure eruptions and extensive plateaus and plains. Igneous rocks do not contain fossils because the high temperatures involved in their formation destroy all organic material. They occur in compact, massive forms and are resistant to weathering.</p>

<h2>Sedimentary Rocks</h2>

<p>Sedimentary rocks form through the process of lithification, in which sediments derived from the breakdown of pre-existing rocks are transported, deposited, compacted, and cemented over time. They are stratified or layered, with each layer known as a bedding plane. Although sedimentary rocks cover the largest proportion of the earth's surface area, they account for only about 5 percent of the total mass of the earth's crust. They are economically significant because they contain fossil fuels, mineral ores, and serve as aquifers for groundwater storage. Because they are permeable, surface water percolates through them into underlying aquifers, making sedimentary rock regions among the richest in groundwater resources.</p>

<p>Physically formed or clastic sedimentary rocks result from mechanical disintegration of existing rocks, with examples including sandstone, clay, shale, and loess. Sandstone is both porous and permeable, while clay is porous but impermeable. Loess is a very fine sedimentary deposit rich in lime that is extremely susceptible to erosion. Wind deposits large amounts of loess in surrounding regions, and river systems in loess-dominated areas are known for shifting their courses and producing badland topography. The Yellow River of China, known as Hwangho, carries enormous quantities of loess eroded from the Gobi Desert, making it the muddiest major river in the world, notorious for flooding and course changes, and is called the Sorrow of China.</p>

<p>Chemically formed sedimentary rocks result from deposition of minerals carried in solution. Solution deposits include rock salt and halite. Carbonation produces limestone and gypsum when carbonic acid formed from atmospheric carbon dioxide and water reacts with calcium-rich rocks. Oxidation produces iron-rich reddish-brown weathering crusts, a common process in tropical and subtropical India. Organically formed sedimentary rocks derive from the decomposition of biological material. Coal forms from buried vegetation compressed over geological time. Limestone and chalk form from the accumulated skeletal material of marine organisms rich in calcium carbonate, including coral reefs.</p>

<h2>Metamorphic Rocks</h2>

<p>Metamorphic rocks form through the transformation of pre-existing rocks under conditions of intense heat and pressure without the rocks dissolving. The transformation alters their mineral composition and crystal structure without disintegration. A characteristic feature of metamorphic rocks is foliation, the parallel arrangement of crystals in bands. Common metamorphic rocks and their parent rocks include quartzite from sandstone, marble from limestone, slate from shale, and schist and gneiss from granite. Metamorphic rocks are generally harder and more resistant than the rocks from which they were formed.</p>

<h2>The Rock Cycle</h2>

<p>The rock cycle describes the continuous transformation of rocks from one type to another over geological time. Magma from the earth's interior cools to form igneous rocks. Weathering and erosion break down igneous rocks into sediments that are transported and deposited, then lithified into sedimentary rocks. Both igneous and sedimentary rocks can be subjected to heat and pressure, transforming them into metamorphic rocks. Metamorphic rocks can be melted back into magma and the cycle begins again. The rock cycle is not linear or strictly sequential; rocks can transform between any types depending on the processes to which they are subjected.</p>

<h2>Earthquakes</h2>

<p>An earthquake is the sudden shaking of the ground caused by the release of energy accumulated along geological faults or at plate boundaries. The focus or hypocentre is the point within the earth where energy is released. The epicentre is the point on the earth's surface directly above the focus and is always the first surface point to experience the seismic waves. Earthquakes are measured by the Richter Scale, which measures the magnitude of energy released on a logarithmic scale, and the Mercalli Scale, which measures the intensity of shaking as felt at the surface.</p>

<p>Earthquakes are classified by depth into shallow-focus earthquakes occurring within 70 kilometres of the surface, intermediate-focus earthquakes between 70 and 300 kilometres, and deep-focus earthquakes between 300 and 700 kilometres. Shallow-focus earthquakes cause the greatest damage at the surface. Most earthquakes occur at plate boundaries where tectonic stresses are concentrated. The Circum-Pacific Belt or Pacific Ring of Fire accounts for the majority of global seismic activity. The Mid-Continental Belt, extending through the Mediterranean, Caucasus, Himalayas, and into Southeast Asia, is the second major seismic zone. Intraplate earthquakes also occur far from plate boundaries along ancient fault lines.</p>

<p>The distribution of earthquakes follows the distribution of plate boundaries. Convergent boundaries produce the most powerful and damaging earthquakes, especially at subduction zones. Transform boundaries such as the San Andreas fault system produce very powerful shallow earthquakes due to the lateral grinding of plates. Divergent boundaries produce relatively weaker earthquakes. Earthquakes associated with continent-continent collision zones such as the Himalayas are powerful but are not accompanied by tsunamis since the collision does not displace large volumes of ocean water.</p>

<h2>Tsunamis</h2>

<p>A tsunami is a series of ocean waves generated by a sudden large-scale displacement of ocean water, most commonly caused by submarine earthquakes, but also by submarine landslides, volcanic eruptions, and meteor impacts. In the open ocean, tsunami waves have very long wavelengths and low heights and travel at speeds of up to 800 kilometres per hour, making them difficult to detect. As they enter shallow coastal waters, they slow down and increase dramatically in height, releasing enormous destructive energy onshore. Because submarine earthquakes at convergent plate boundaries produce the most violent vertical displacement of the ocean floor, these boundaries are the most tsunamigenic. The eastern coast of India is particularly vulnerable to tsunamis because it faces the Java or Sunda Trench where the Pacific plate subducts beneath the Indian plate, as demonstrated by the 2004 Indian Ocean Tsunami caused by the interaction of the Indian and Burmese plates. Early warning systems using seismograph networks and ocean buoys are the primary means of tsunami hazard mitigation.</p>

<h2>Volcanism</h2>

<p>Volcanism encompasses all processes related to the movement of molten material within and through the earth's crust, including both the underground formation of intrusive landforms and the surface expression through volcanic eruptions and the creation of extrusive landforms. A volcano is specifically a vent or opening through which molten rock, gases, and fragmented material are expelled. The material erupted consists of water vapour and gases such as sulphur oxides, carbon dioxide, carbon monoxide, nitrogen oxides, and methane, which account for roughly 60 percent of volcanic output. Magma and lava constitute the second component, with acidic magma being silica-rich, viscous, lighter in colour, and associated with violent central eruptions, while basic magma is iron-rich, fluid, darker, and hotter, associated with quiet fissure eruptions that build extensive plateaus. Pyroclastic material or tephra, the third component, includes volcanic ash, dust, cinders, and larger rock fragments that can cause atmospheric pollution and short-term global cooling by reducing incoming solar radiation.</p>

<h2>Intrusive Volcanic Landforms</h2>

<p>When magma cools and solidifies underground without reaching the surface, it forms intrusive or plutonic landforms that are only exposed after overlying rocks have been removed by erosion. A batholith is the largest intrusive igneous body, generally composed of granite, found at the greatest depths and sometimes forming the core of mountain ranges. A lopolith is a saucer-shaped mass of igneous rock with a concave upper surface. A laccolith is an intrusive mound connected to the surface by a feeder pipe, creating a dome-like uplift of overlying rocks. A phacolith is a lens-shaped igneous body found in pairs at the crest of anticlines or the base of synclines, also connected by a pipe. A sill is a sheet of intrusive igneous rock injected parallel to the bedding planes of sedimentary rocks. A dyke is an intrusive igneous body that cuts vertically or at an angle across the bedding planes of surrounding rocks.</p>

<h2>Extrusive Volcanic Landforms</h2>

<p>Volcanic mountains form through the accumulation of erupted material. Ash and cinder cones are small, weak structures formed from loose pyroclastic material and rarely attain significant heights. Composite cones or stratovolcanoes are the tallest and most imposing volcanic mountains, built from alternating layers of lava and pyroclastic material. The solidified lava acts as cement between the ash layers, giving these cones great structural strength and resistance to erosion. Major composite cones include Mount Aconcagua and Cotopaxi in the Andes, Mount Rainier, Shasta, and Hood in the Rockies, Mount Mayon in the Philippines, Mount Fujiyama in Japan, and Mount Kilimanjaro, the highest peak in Africa. India's only active volcanoes, Barren Island and Narcondam, are in the Andaman and Nicobar Islands. Shield cones or basic lava cones form from basaltic magma, which flows easily and spreads widely before solidifying, producing broad, low-profile structures such as Mauna Loa and Mauna Kea in the Hawaiian Islands. Parasitic cones form when secondary branches develop off the main feeder pipe of a volcano, producing numerous smaller subsidiary cones on the flanks of the main mountain.</p>

<p>A crater is the vent or opening at the top of a volcano through which eruption occurs. A caldera is a much larger depression formed either by the explosion of the volcanic cone or by its collapse into an emptied magma chamber. When water accumulates in a crater or caldera, it forms a crater lake. Volcanic plateaus and plains form from extensive outpourings of basaltic lava through fissure eruptions. After weathering, basaltic lava produces black soil that is highly fertile, moisture-retaining, and well suited to cash crops such as cotton. Major volcanic plateaus include the Columbia Snake Plateau of the United States, the Parana Plateau of South America, the Drakensberg Plateau of South Africa, the Siberian Plateau of Russia, the Deccan Lava Plateau of India, and the Kimberley Plateau of Australia.</p>

<p>Hot springs and geysers form when groundwater comes into contact with underlying magma or hot rocks, is heated, expands, and rises to the surface. In geysers, the heated water erupts periodically and with great force. Geysers are found only in Iceland, New Zealand, and Yellowstone National Park in the United States. When the heat is so intense that water evaporates entirely before reaching the surface, the resulting superheated steam is called a fumarole. Regions of hot springs and geysers are important for medical tourism, since sulphur-rich waters are used for treating skin conditions, and for geothermal energy generation. Iceland leads the world in geothermal energy production. In India, Manikaran in Himachal Pradesh is a notable geothermal site.</p>

<h2>World Distribution of Volcanoes</h2>

<p>The global distribution of volcanoes is closely related to the distribution of plate boundaries. Four major volcanic zones are recognised. The Circum-Pacific Belt or Pacific Ring of Fire contains approximately 60 percent of the world's active volcanoes and represents primarily convergent plate boundaries where the Pacific plate subducts beneath surrounding plates including the Indo-Australian, Eurasian, North and South American, and Antarctic plates. It extends from Antarctica through New Zealand, the Philippines, Japan, and along both coasts of the Americas. The Mid-Continental Belt, also a convergent boundary zone, contains about 20 percent of the world's volcanoes and includes the volcanic centres of the Mediterranean region such as Mount Stromboli, Mount Etna, and Mount Vesuvius in Italy, and Mount Pelee in the Caribbean. The Himalayas are notably absent from this belt despite lying within the mid-continental zone, because continent-continent collision prevents the subduction necessary for volcanism. The Mid-Oceanic Belt contains about 15 percent of the world's volcanoes and represents divergent plate boundaries, producing fissure-type eruptions along mid-oceanic ridges such as those of Iceland. Hotspot volcanoes account for approximately 5 percent of global volcanic activity and occur within plate interiors far from boundaries, in regions of anomalously thin crust or high mantle temperatures. Examples include the Hawaiian Islands in the Pacific and the Reunion Islands in the Indian Ocean.</p>

<h2>Mechanism of Volcanic Eruption and Climatic Impact</h2>

<p>Volcanic eruptions are driven by heat generated primarily by radioactive mineral decay within the mantle, which produces convection currents that carry magma upward. At convergent boundaries, the subducting plate melts as it descends and the resulting magma is forced upward through the overlying plate under intense pressure, producing violent central eruptions. At divergent boundaries, the separation of plates creates fissures through which fluid basaltic magma rises quietly and spreads laterally, building mid-oceanic ridges and volcanic plateaus. The intensity of an eruption depends on the composition of the magma, with silica-rich acidic magma producing more explosive eruptions than fluid basic magma.</p>

<p>Volcanic eruptions have significant short-term and long-term climatic effects. In the short term, the injection of sulphur dioxide and ash into the stratosphere reflects incoming solar radiation, producing global cooling. The 1991 eruption of Mount Pinatubo in the Philippines caused measurable global temperature decrease in the following years. In the long term, the release of carbon dioxide contributes to greenhouse warming, making volcanoes contributors to both cooling and warming depending on the time scale of analysis. Over geological time scales, volcanic activity has been linked to episodes of mass extinction and subsequent evolutionary diversification of life forms. There is also evidence suggesting that the melting of glaciers and ice caps reduces the superincumbent pressure on the crust, potentially increasing the rate of volcanic eruptions in formerly glaciated regions, though this relationship remains an area of active research.</p>
`,

  'landforms-fluvial-arid-glacial': `
<h2>Agents of Erosion and the Concept of Geomorphic Cycles</h2>

<p>Landforms produced by erosion and deposition reflect the interaction of structure, process, and time. The dominant external agents of erosion are running water, glaciers, wind, and waves, each producing a characteristic suite of landforms. Running water is the most universal agent: it operates not only in humid fluvial environments but also contributes to landform development in glacial and desert settings. The landforms produced by any agent pass through a sequence of stages broadly described as youthful, mature, and old age, corresponding to progressively lower gradients, reduced erosional energy, and increasing dominance of deposition. Rejuvenation — triggered by tectonic uplift or a fall in sea level — reintroduces youthful characteristics into an old landscape, producing distinctive landforms that record the disrupted cycle.</p>

<h2>Karst Topography</h2>

<p>Karst topography develops in regions underlain by limestone, chalk, or other soluble carbonate rocks. The name derives from the Karst region of Yugoslavia bordering the Adriatic Sea, which is the type locality for this landscape. Limestone is an extremely weak rock when exposed to water carrying dissolved carbon dioxide, which forms weak carbonic acid capable of dissolving calcium carbonate. The defining characteristic of karst regions is the near-total absence of surface drainage: rivers disappear underground through joints and bedding planes enlarged by chemical solution, flow through cave systems, and reappear as springs where they meet impermeable country rock. Karst topography is most intensely developed in humid tropical and subtropical climates where rainfall is abundant and temperatures are high enough to accelerate chemical weathering.</p>

<p>Surface features of karst begin with sinkholes or dolines, which are roughly circular depressions formed where surface water concentrates and dissolves the limestone beneath, widening joints into funnels. A dolina is a larger and more developed depression. When several dolinas merge through continued solution, the composite depression is called a uvala. The largest elongated karst depressions, often associated with structural features such as faults, are called poljes and may be tens of kilometres in extent. Limestone that is exposed at the surface is characterised by a pavement of rectangular blocks called clints, separated by solution-enlarged joint gaps called grikes. The combined surface of clints and grikes constitutes limestone pavement.</p>

<p>Underground, the dissolution of limestone by percolating water creates an extensive system of caves, passages, and chambers. Water dripping from cave ceilings loses carbon dioxide and deposits calcium carbonate on the roof, building downward-growing spires called stalactites. Where the calcium carbonate-laden water drips to the cave floor, it builds upward-growing columns called stalagmites. When a stalactite and a stalagmite meet and fuse, they form a limestone pillar. Stalactites tend to be thin and pointed while stalagmites are typically thicker and more rounded. Notable karst regions include the original Karst of Yugoslavia, the Batu Caves of Malaysia, and the Nokrek Biosphere Reserve in the Garo Hills of Meghalaya, which is also famous as the habitat of the hoolock gibbon, the only ape found in India.</p>

<h2>Fluvial Topography: Mechanisms of River Erosion</h2>

<p>Running water erodes through four distinct mechanisms that operate simultaneously. Solution or corrosion is the chemical dissolution of soluble minerals directly into river water, particularly important in limestone regions. Abrasion or corrasion is the mechanical grinding of the river bed and banks by the sediment load carried by the water, and is divided into lateral abrasion, which widens valleys, and vertical abrasion, which deepens them. Hydraulic action is the sheer force of moving water that loosens and detaches rock particles from the channel, particularly effective along joints and cracks. Attrition is the mutual wearing down of sediment particles as they collide and rub against each other during transport, progressively reducing their size and rounding their edges.</p>

<h2>Youthful Stage: Landforms of Active Downcutting</h2>

<p>In the youthful stage the river flows on steep slopes with high velocity, giving it a large carrying capacity sufficient to transport coarse bedload material including boulders. Vertical erosion is dominant. Eddy currents within the river create circular motion in pebbles and boulders that drill into the bedrock, forming deep cylindrical depressions called potholes. Continued vertical erosion produces narrow, deep V-shaped valleys called gorges. An extended gorge developed in arid and semi-arid regions where resistant rock is exposed to incision by a river is called a canyon. The Grand Canyon of the United States, carved by the Colorado River as it crosses the Sonoran Desert of Arizona, is the classic example, while the Kali Gandaki gorge in the Himalayas, approximately 7,000 metres deep, is considered the deepest gorge in the world.</p>

<p>Waterfalls form where a river crosses a band of resistant rock overlying weaker rock, or at a fault scarp. Differential erosion removes the softer rock faster, creating a vertical drop. Smaller waterfalls are called rapids; larger ones are called cataracts. The five major cataracts on the River Nile historically impeded navigation on the upper Nile. At the base of waterfalls, the hydraulic impact of the falling water creates a deep depression called a plunge pool, which is a tourist attraction and marks the point of maximum erosive energy at that site. The highest waterfall in India by height is Jog Falls on the Sharavati River in Karnataka, while the largest by volume is Dhuandhar Falls on the Narmada at Jabalpur.</p>

<p>River capture or river piracy occurs when a more energetic river erodes headward into the watershed of a neighbouring drainage basin, breaching the divide and diverting the headwaters of the captured river into its own channel. The point at which capture occurs is called the elbow of capture, and the gap left in the former watershed after capture is called a windgap or wind gap, which can serve as a mountain pass for roads and railways. The beheaded river downstream of the capture point is called a misfit, flowing in a valley too large for its reduced discharge. In old age, river capture can also occur through the intersection of meanders, as the narrow neck of land between two meander loops is eroded through and the river straightens its course.</p>

<h2>Mature Stage: Landforms of Lateral Erosion and Deposition</h2>

<p>In the mature stage the gradient decreases, velocity falls, and the river shifts from dominant vertical cutting to lateral or sideways erosion. The narrow V-shaped valley of the youthful stage widens into a broader, shallower valley. At the foot of mountains the river, suddenly losing velocity as it crosses from steep to gentle slopes, drops its coarsest sediment in the form of an alluvial fan: a cone-shaped depositional landform composed of poorly sorted gravels, sands, and boulders spreading outward from the mountain front. In the Himalayan foothills of India, the alluvial fan zone is divided into the Bhabhar belt, where rivers lose themselves in the highly porous coarse gravels and flow largely underground with only trees with deep root systems surviving, and the Terai belt immediately south, where the underground water re-emerges as springs creating a marshy, waterlogged zone of dense forest, high biodiversity, and fertile soil. The Terai belt once extended continuously along the Himalayan foothills and hosts important national parks including Jim Corbett in Uttarakhand, Dudhwa in Uttar Pradesh, Kaziranga in Assam, and Manas in Assam.</p>

<p>Interlocking spurs are the projecting ridges of high ground that alternate on either side of a valley in the mature stage, giving the valley a zigzag appearance when viewed from above or below. Meanders are sinuous bends developed in the longitudinal profile of a river as it flows in increasingly winding loops across a low-gradient surface. Though meanders can occur at any stage, they are most fully developed in the mature and old age stages. Within a meander, the outer bank experiences erosion and forms a steep, concave river cliff while the inner bank experiences deposition and forms a gentle, convex slip-off slope. The asymmetry of deposition and erosion within each bend continuously reinforces and amplifies the sinuosity of the channel.</p>

<h2>Old Age Stage: Landforms of Dominant Deposition</h2>

<p>In the old age stage the river flows across a nearly flat floodplain with very low velocity. Vertical erosion has essentially ceased and deposition is the dominant process. Ox-bow lakes form when the neck of a meander loop is cut through and the river adopts a straight course, leaving behind a curved, crescent-shaped abandoned channel filled with water. Kanwar Lake in Bihar is the largest ox-bow lake in India, formed by river capture. Wular Lake and Dal Lake in Kashmir occupy ox-bow-like depressions formed by local topographic factors rather than meander cut-off.</p>

<p>The floodplain is an extensive, nearly level depositional surface flanking the river, built up over time by the periodic deposition of alluvium during floods. Natural levees are ridges of coarser sediment deposited immediately adjacent to the channel when floodwaters spread over the floodplain and rapidly lose velocity. They naturally raise the river bed above the surrounding plain in many rivers, including the Ganga and the Brahmaputra, increasing flood hazard. Artificial embankments are typically constructed on top of natural levees to contain flood events. In India the floodplain is divided into bangar, composed of older alluvium deposited during earlier flood events, and khadar, made of newer, finer alluvium deposited by more recent flooding and being the more fertile of the two.</p>

<p>A delta is a wholly depositional landform built at the mouth of a river where it enters the sea or a large water body, as the sudden drop in velocity causes the river to deposit its sediment load. The river channel is divided into multiple distributaries as sediment chokes and blocks the main channel. Three major types of delta are recognised. An arcuate or fan-shaped delta forms when river water and seawater are of similar density, causing the river to begin depositing immediately at its mouth and fan outward symmetrically. The Nile delta, the Ganga-Brahmaputra delta, the Indus delta, the Godavari delta, the Mekong delta, and the Rhine delta are arcuate deltas. A bird-foot or finger delta forms when river water is less dense than seawater, allowing the river to flow into the sea as a fast-moving underflow before beginning to deposit, with the resulting distributary system resembling the spread toes of a bird. The Mississippi delta is the classic example. An estuary forms where the mouth of a river is drowned by a rise in sea level or coastal submergence, producing a funnel-shaped tidal inlet rather than a delta. The Narmada, the Tapi, and the Amazon form estuaries rather than deltas.</p>

<p>Conditions favouring delta formation include high sediment supply, which is greatest in rivers draining steep mountain ranges such as the Himalayas, a long river course that allows the accumulation of sediment, a shallow and sheltered coastline that prevents wave action from dispersing deposited material, geological stability of the coastal zone without recent submergence, sediment of intermediate grain size that is neither too fine to be swept away by tides nor too coarse to be carried to the coast, and the absence of large riparian lakes that would act as sediment traps. East-flowing rivers of India form large deltas because they are longer, drain the soft alluvium of the Indo-Gangetic plain, and their coasts are sheltered and shallow. West-flowing peninsular rivers are short, swift, drain hard rock, and their coasts face high-energy monsoon waves, leading them to form estuaries rather than deltas.</p>

<h2>River Rejuvenation</h2>

<p>River rejuvenation occurs when a river's base level falls due to tectonic uplift of the land, a eustatic fall in sea level, or a reduction in the volume of ice or water reservoirs. Rejuvenation reinvigorates the river's erosive capacity, producing a new set of youthful landforms superimposed on the old-age landscape. Incised or entrenched meanders form when a rejuvenated river cuts vertically downward into its existing meander pattern, preserving the sinuous plan form of the meander in a deeply incised valley. River terraces are flat benches cut into the valley sides as the river erodes downward through its own former floodplain, leaving elevated remnants of the old valley floor on either side of the new, lower channel. Uplifted peneplains are former nearly flat erosional surfaces that have been tectonically raised above the current base level and now stand as elevated plateaus. The presence of multiple terraces at different heights records multiple episodes of rejuvenation.</p>

<h2>Arid and Desert Landforms</h2>

<p>Deserts are regions of extremely low precipitation, typically receiving less than 250 millimetres annually. Hot deserts develop in the subtropical high-pressure belts between roughly 20 and 35 degrees latitude where descending air is compressed, warmed, and dried, reinforced by the influence of cold offshore ocean currents that prevent moisture from reaching the coast and trade winds that blow from the hot interior toward the coasts. Cold deserts develop in rain shadow zones on the leeward side of major mountain ranges where descending air has lost most of its moisture. Wind is the most active agent of erosion in deserts because the absence of vegetation and moisture leaves the surface exposed to the full force of the wind.</p>

<p>Wind erodes through three mechanisms. Deflation is the lifting and removal of loose fine particles by the wind, leaving behind a surface of coarser material called desert pavement or reg and creating shallow depressions called deflation hollows. Where deflation exposes groundwater at the surface, oases form. The Qattara Depression at minus 133 metres in Egypt is the deepest deflation hollow on earth. Abrasion or sandblasting is the mechanical erosion of rock surfaces by wind-driven sand particles, which act as natural sandpaper and are most effective close to the ground where sand is heaviest. Attrition is the mutual wearing down of sand particles against each other during transport, rounding them and reducing their size.</p>

<p>Erosional landforms in deserts include deflation hollows, mushroom rocks, yardangs, zuegens, mesas, and ventifacts. Mushroom rocks form because wind-driven sand is most concentrated close to the ground, eroding the base of isolated rocks faster than their tops, producing a narrow-waisted, top-heavy mushroom profile. Yardangs develop where alternating bands of hard and soft rock are oriented vertically along the prevailing wind direction, with the softer rock eroded into furrows and the harder rock standing as ridges. The furrows between yardangs serve as natural corridors or highways across the desert. Zuegens form where horizontal bands of hard and soft rock are exposed to wind and differential erosion, producing an irregular tabular relief. Mesas are flat-topped, steep-sided erosional remnants capped by a resistant rock layer, typically basaltic, that protects the weaker rocks beneath from erosion. As mesas are progressively reduced they become smaller flat-topped remnants called buttes. Mesas and buttes in the Deccan plateau region of India are separated by canyons. Ventifacts are individual rock fragments shaped and polished by wind abrasion into flat, angular faces; a rock with three wind-polished faces is specifically called a dreikanter.</p>

<p>Desert depositional landforms are dominated by sand dunes, which are mounds and ridges of wind-blown sand in characteristic shapes determined by wind direction and speed. Seifs or longitudinal dunes are dunes that lie parallel to the prevailing wind direction, formed when high-velocity winds pick up sand and deposit it on the flanks, producing long, knife-edged ridges named after the Arabic word for sword. The sand-free corridor between adjacent seifs is called a gassi. Barchans or barchan dunes are crescent-shaped dunes that form transverse to the wind direction around a localised obstruction. Their windward side is convex and gently sloping while the lee side is concave, steep, and characterised by two projecting horns. Barchans are live or mobile dunes that migrate downwind, contributing to desertification as they encroach on neighbouring land. Both seifs and barchans are found in western Rajasthan. Star dunes form where winds blow from multiple directions, producing a central peak with radiating arms.</p>

<h2>Glacial Landforms</h2>

<p>Glaciers are bodies of ice that form where snowfall over many years exceeds melting, and that move under their own weight by plastic deformation and basal sliding. They are powerful erosional agents, capable of excavating deep valleys, rounding and polishing bedrock, and transporting enormous quantities of rock debris. Glacial erosion operates through abrasion, where rock fragments embedded in the base of the glacier scrape and grind the underlying bedrock, and plucking or quarrying, where the glacier freezes to bedrock and wrenches away blocks along joints. The combined effect produces a landscape of great topographic diversity.</p>

<p>Erosional landforms produced by mountain or alpine glaciers begin at the head of the glacier where snow accumulates in a bowl-shaped hollow called a cirque or corrie, formed by rotational erosion of the back wall and floor. The floor of a cirque is often occupied by a small lake called a tarn after the glacier retreats. Where two or more cirques erode into a ridge from opposite sides, the intervening wall is sharpened into a narrow, knife-edged ridge called an arête. Where three or more cirques cut into a mountain from all sides, the central summit is reduced to a steep, pyramidal peak called a horn, of which the Matterhorn in the Alps is the archetypal example. Glacial troughs are the U-shaped valleys carved by valley glaciers moving downslope, characterised by steep, nearly vertical sides and a flat floor resulting from the glacier's tendency to widen as well as deepen the valley. When the glacier retreats, smaller tributary valleys are left hanging high on the walls of the main trough, called hanging valleys, often with waterfalls descending to the main valley floor. Where glacial troughs are flooded by the sea following the melting of the ice, they form deep, narrow coastal inlets called fjords, found along the coasts of Norway, Chile, New Zealand, and British Columbia.</p>

<p>Depositional landforms result from the dumping of the unsorted mixture of rock fragments, clay, sand, and boulders called till or boulder clay that the glacier carries. Ground moraine is a layer of till deposited beneath the glacier as it moves. Terminal or end moraines are ridges of till dumped at the snout of a glacier at the maximum extent of its advance, forming low, curved ridges across the landscape. Lateral moraines are ridges of debris accumulating along the sides of a valley glacier from rockfall off the valley walls. When two valley glaciers merge, their inner lateral moraines combine to form a medial moraine running down the centre of the combined glacier. Drumlins are streamlined, egg-shaped mounds of till, always with their blunt end facing the direction from which the glacier came and their tapered end pointing in the direction of ice movement; they typically occur in swarms across formerly glaciated lowlands. Erratics are isolated boulders of a rock type foreign to the local bedrock, transported by glaciers from their source area and deposited far from their origin when the ice melted, serving as evidence of former glacier extent and direction. Eskers are long, sinuous ridges of sorted fluvio-glacial sand and gravel deposited by meltwater streams flowing in tunnels within or beneath the glacier, preserved after the ice melts as winding ridges crossing the landscape. Kettles are depressions formed where blocks of stagnant ice were buried by outwash sediment and then melted, leaving behind a hollow that may be filled with water to form a kettle lake.</p>

<h2>Coastal Landforms</h2>

<p>Coastal landforms result from the interaction of wave energy, tidal action, and the geological structure of the coastline. Waves are generated by wind friction on the ocean surface and release their energy at the coast. The zone of breaking waves is where most erosion and deposition occur. Wave erosion operates through hydraulic action, where the sheer force of waves compresses air in cracks and explosively dislodges rock; abrasion, where wave-carried rock fragments grind the cliff face; attrition, where rock fragments wear each other down; and solution, particularly effective on calcareous rocks.</p>

<p>Erosional coastal landforms develop where waves attack a rock cliff. The base of the cliff is undercut by hydraulic action and abrasion, forming a wave-cut notch, until the overhanging cliff face collapses. Repeated undercutting and collapse retreats the cliff face landward, leaving behind a gently sloping bedrock platform called a wave-cut platform or shore platform extending seaward from the base of the cliff. Where alternate bands of hard and soft rock approach the coast at right angles, differential erosion produces sea caves in the soft rock flanked by headlands of hard rock. When a cave is cut through a headland it forms a natural arch. Further erosion causes the roof of the arch to collapse, leaving a detached pillar of rock called a stack. Stacks are eventually reduced to wave-washed stumps. Geos are narrow, steep-sided inlets cut along vertical joints by wave action.</p>

<p>Depositional coastal landforms include beaches, spits, bars, and tombolos. Beaches are accumulations of sand or pebbles in the nearshore zone, deposited by waves and longshore drift, the process by which sediment is transported along the coast by waves approaching at an oblique angle. A spit is an elongated ridge of sand or gravel projecting from the coast into the sea or across the mouth of a bay, built by longshore drift and typically with a curved or hooked end where waves refract around its tip. A bar is a ridge of sediment connecting a spit to the opposite shore or lying submerged offshore. A tombolo is a bar of sediment connecting the mainland to an offshore island. A lagoon is the sheltered water body enclosed between a barrier spit or bar and the mainland coast. Emergent coastlines, where the land has risen relative to the sea, expose former wave-cut platforms as raised beaches above the current shoreline. Submergent coastlines, where the land has sunk or the sea has risen, drown former valleys to create rias and former glacial troughs to form fjords. The eastern coast of India is an emerged coastline that has been built up by long-term sediment deposition, while the western coast is a submerged coastline where river valleys have been drowned by the sea, explaining why western rivers form estuaries rather than deltas and why the western coast lacks extensive continental shelf compared to the east.</p>
`,

};
