'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { auth } from '@/lib/firebase';
import { onAuthStateChanged, User } from 'firebase/auth';

const FEATURES = [
  { icon: '✍️', label: 'Evaluate Answer', href: '/evaluate', desc: 'Upload your answer sheet — get AI feedback on structure, content & marks.', color: 'var(--accent)', badge: null },
  { icon: '🤖', label: 'AI Chat', href: '/chat', desc: 'Ask anything about your optional. Syllabus-aware, exam-ready answers.', color: '#a78bfa', badge: null },
  { icon: '📖', label: 'Notes', href: '/notes', desc: 'Exhaustive syllabus notes structured by paper and section.', color: '#34d399', badge: 'Free' },
  { icon: '🗂️', label: 'PYQs', href: '/pyqs', desc: '1500+ previous year questions with year, marks and paper filters.', color: '#f59e0b', badge: 'Free' },
  { icon: '🏆', label: 'Topper Copies', href: '/toppers', desc: 'Real topper answer sheets — see what a 300+ score looks like.', color: '#f87171', badge: 'Premium' },
];

const TIPS_BY_OPTIONAL: Record<string, string[]> = {
  history: [
    'Start every answer with a crisp one-line thesis — examiners scan for it instantly.',
    'Learn 3–4 historiographical debates cold: nationalist vs. Marxist vs. subaltern readings of 1857.',
    'Always attribute: "As Romila Thapar argues…" beats generic claims.',
    'The Harappan Civilisation question appears almost every cycle — have a 250-word model ready.',
    'For 10-mark answers, aim for exactly 3 substantive body paragraphs.',
    'Know the difference between deindustrialisation thesis (Naoroji) and revisionist critiques (Roy).',
    'Connect ancient polity to modern governance analogies — examiners love cross-period insight.',
    'Bhakti and Sufi movements: don\'t just list saints, explain the social reform dimension.',
    'The "drain of wealth" debate: memorise the key figures — ₹200 crore, ₹34 crore (Digby vs. Naoroji).',
    'Mauryan administration has 20-mark potential every year. Nail the amatya, mantri, spy networks.',
    'Gupta ≠ "Golden Age" — present the critique: regional variation, women\'s status, untouchability.',
    'For medieval history, always bring in the perspective of common people, not just sultans.',
    'Land revenue systems: Todarmal\'s Ain-i-Dahsala, Permanent Settlement, Ryotwari — tabulate them.',
    'Practice writing timelines: a quick chronology at the start saves marks in long essays.',
    'Subaltern studies (Ranajit Guha) is an almost-guaranteed question in Paper II.',
    'Architecture questions need dates + dynasties + distinctive features, not just descriptions.',
    'Colonial social reforms: don\'t forget the Indian reformers\' role (Roy, Vidyasagar, Phule).',
    'Avoid "it is well known that…" — examiners deduct for vague assertions.',
    'Numismatic evidence is underrated. Mention it in ancient India questions for extra marks.',
    'Revolt of 1857: always give a multi-causal analysis, not just the cartridge story.',
    'Sangam literature as a source — unique, scores well, barely anyone uses it.',
    'Chola naval expeditions: dates, targets, and significance in one tight paragraph.',
    'Jain and Buddhist influence on Indian thought is a recurring theme — prepare a matrix.',
    'The early medieval period (750–1200 CE) is often under-prepared. Fill that gap.',
    'Map-based questions in Prelims overlap heavily with Paper I of Mains. One prep, dual use.',
    'For 20-mark answers, your conclusion must synthesize and not just repeat intro.',
    'Delhi Sultanate succession politics: each sultan\'s key admin reform is a safe answer anchor.',
    'Economic history questions reward data — know the colonial trade stats cold.',
    'Vijayanagara sources are limited — when writing about it, acknowledge the limitation.',
    'The Mughal mansab system: dagh, chehra, zat vs. sawar. Spell them right.',
    'Akbar\'s Din-i-Ilahi: downplay its religious significance, emphasise political consolidation.',
    'Women in history: Razia Sultana, Nur Jahan, Ahilyabai Holkar — examiners want gender lens.',
    'Modern India starts from 1757 in Paper II — calibrate your periodisation accordingly.',
    'Sati abolition (1829): know the debates on both sides, not just Bentinck.',
    'Write at least one practice answer every single day — no exam tests knowledge, all test writing speed.',
    'British constitutional reforms: 1861 → 1892 → 1909 → 1919 → 1935 — know each increment.',
    'For IR history questions, connect to contemporary geopolitics — it impresses.',
    'The Partition historiography section is emotionally charged. Write analytically, not emotionally.',
    'Nationalist movement: avoid hagiography. A balanced critique of Gandhi marks you as a serious candidate.',
    'Never write "India has a rich cultural heritage" in your intro — it signals unpreparedness.',
    'Feroz Shah Tughlaq\'s reforms: welfare state-like elements, an unusual angle that scores.',
    'Know your temple types: Nagara, Dravida, Vesara — with examples for each.',
    'Indus Valley weights and measures system: surprisingly frequent, very few prepare it.',
    'Mahajanapadas → Magadha rise: explain WHY Magadha, not just that it did.',
    'Buddhism spread outside India — this is Paper I material and often ignored.',
    'Shivaji\'s administration borrows from Mughals more than textbooks admit. Say so.',
    'The "communalism as colonial construct" debate (Bipan Chandra) is essay gold.',
    'Lord Hastings vs. Cornwallis — compare their Company policies in 50 words flat.',
    'Social legislation timeline 1828–1947: compile a one-pager, revise daily last month.',
    'Writing fast matters. In mocks, deliberately write 20% faster than comfortable.',
    'Ashoka\'s dhamma: administrative policy, not personal religion. Distinction = marks.',
    'Harsha\'s empire: show how it compares to Gupta decline — decentralisation theme.',
    'Pallavas vs. Chalukyas vs. Rashtrakutas: the south India triangle, know the intersections.',
    'The Orientalist vs. Anglicist controversy in education shapes later nationalism. Connect them.',
    'Economic nationalism (Tilak, Gokhale, Pal): distinct positions, not a monolith.',
    'Peasant movements 1857–1947: Indigo, Deccan Riots, Champaran, Bardoli — each has unique features.',
    'Maps: know the extent of each empire, not just capitals.',
    'Historiography questions reward names + works: Basham, Kosambi, Habib, Irfan, Thapar, Guha.',
    'Keep a "historians and their theses" one-pager for quick last-day revision.',
    'Avoid bullet points in narrative answers — they signal low analytical depth.',
    'Gandhian economics (swadeshi, trusteeship) can be tied to current debates — risky but rewarding.',
    'The Mughal decline: don\'t over-rely on Aurangzeb. Know Satish Chandra\'s structural argument.',
    'Tribal movements (Santhals, Mundas, Bhils): show economic + cultural dimensions, not just political.',
    'Stone Age periodisation in Paper I: Palaeolithic → Mesolithic → Neolithic → Chalcolithic.',
    'Buddhist councils (1st to 4th): location, king, outcome. 4 bullet points, lifetime marks.',
    'The Ryotwari and Zamindari areas of colonial India: know the MAP, not just definitions.',
    'Three-tier feudal argument for early medieval India (R.S. Sharma) — know and critique it.',
    'Vernacular press and nationalist opinion: don\'t forget the Vernacular Press Act (1878).',
    'Non-Cooperation Movement: explain why Gandhi withdrew it. Examiners test the nuance.',
    'Round Table Conferences: their failure is as important as what was discussed.',
    'Independence vs. Partition: treat them as separate events with separate historiographies.',
    'Provincial elections 1937: what Congress\'s landslide revealed about Muslim League\'s weakness.',
    'Post-independence integration of princely states: Hyderabad, Junagadh, Kashmir — each different.',
    'Indian Constitution\'s historical influences: don\'t limit to America/UK, include pre-colonial assemblies.',
    'Indus Valley religion: Mother Goddess, Pashupati seal, ritual bathing — evidence-based, no speculation.',
    'Trade routes (Silk Road, Indian Ocean) connect Paper I economies to Paper II colonial trade.',
    'Kalidasa: not just literature, but evidence of Gupta cultural patronage system.',
    'Arab and Turkish invasions: don\'t conflate them. Different motivations, different outcomes.',
    'Medieval town economy vs. village economy: a surprisingly under-answered contrast question.',
    'Wellesley\'s Subsidiary Alliance: show why it was more effective than military conquest.',
    'Vernacular literature as historical source: a method question that catches most unprepared.',
    'Chronology accuracy matters: being off by 50 years in a 10-mark answer costs real marks.',
    'The colonial revenue burden thesis: know both the drain argument and its critiques.',
    'Calcutta to Delhi capital shift (1911): administrative, political, symbolic — multi-angle.',
    'Simon Commission: why Indians rejected it, what it triggered, consequence chain.',
    'Cabinet Mission Plan: an answer that distinguishes average from serious candidates.',
    'Revisit your weakest Paper I topic every Sunday — ancient India neglect is the most common mistake.',
    'Know your footnotes: if you can cite a specific chapter of a work, mention it.',
    'Print capitalism (Benedict Anderson) applied to Indian nationalism = theory + content combo.',
    'For 15-mark answers, a brief "What will I argue?" sentence after intro works well.',
    'Use transition words between paragraphs: "Moreover", "In contrast", "Crucially" — signal analytical flow.',
    'Social reform movements must tie to caste — every UPSC history paper rewards caste lens.',
    'Harappan script: undeciphered but not unimportant. Use it to show interpretive limits in history.',
    'The 1940s decade (1940–47) in Indian history: prepare a year-by-year timeline.',
    'Integrate economics into political history: conquest followed trade, not the other way around.',
    'Mock test debrief > mock test performance. Analyse every missed mark, not just the score.',
    'Compare your answers with topper copies side-by-side — the gap is always structural, rarely knowledge.',
    'Vedic literature as source: Rigveda → economic, Atharvaveda → social, Upanishads → philosophical.',
    'Warren Hastings to Dalhousie: prepare a governor-general comparison table with key policies.',
    'Indian National Congress factions (1907 Surat Split): Moderates vs. Extremists — methods, goals, leaders.',
  ],

  sociology: [
    'Always define key terms in the first line — sociological vocabulary is half the battle.',
    'Thinkers and their concepts: Weber (verstehen), Durkheim (anomie), Marx (alienation) — trio to know cold.',
    'Indian sociology is Paper II — don\'t treat it as less important than Paper I Western theory.',
    'Structural-functional vs. conflict perspective: examiners reward explicit comparison.',
    'Caste and class intersection: Ambedkar vs. Marx is a high-value question every year.',
    'Tribe vs. caste vs. peasant distinction: sharp conceptual clarity wins marks.',
    'Globalisation and Indian society: give local, grounded examples — not just abstract theory.',
    'M.N. Srinivas: Sanskritisation, Westernisation, Dominant Caste — three concepts, many marks.',
    'Family and kinship in India: North-South difference is a recurring question.',
    'Secularisation thesis and India: why it doesn\'t apply straightforwardly here.',
    'Religion as a social institution: don\'t reduce it to belief — show function.',
    'Social stratification: know all four bases (class, caste, gender, race) and their interaction.',
    'Feminist sociology: liberal, Marxist, radical — distinguish all three clearly.',
    'Industrialisation and urbanisation: twin processes, but sociologically distinct.',
    'Agrarian class structure in India: Beteille, Thorner, Panikkar — know at least one well.',
    'Social movements: new vs. old — explain with Indian examples (Chipko, Narmada).',
    'Modernisation theory vs. dependency theory in context of Indian development.',
    'Youth, media, and social change: a contemporary question that rewards current affairs knowledge.',
    'Village studies tradition in Indian sociology: Dube, Srinivas, Beteille.',
    'Write answers that move from concept → theory → Indian example → critique.',
    'Dalits and social exclusion: data + theory + policy = complete answer.',
    'Marriage in India: types, regional variation, changing patterns in urban India.',
    'Healthcare and sociology: role of gender, caste, class in access to healthcare.',
    'Education as a social institution: hidden curriculum, reproduction of inequality.',
    'Communalism in India: sociological (not political) reading — Brass, Engineer.',
    'Environment and society: political ecology is an emerging area — prepare it.',
    'Sociological methods: positivism vs. interpretivism, quantitative vs. qualitative.',
    'Indian middle class: a social formation question that appears regularly.',
    'Weaker sections: SC, ST, OBC — policy context + sociological analysis.',
    'Poverty: absolute vs. relative, measurement debates, structural causes.',
    'Use diagrams (family structures, stratification hierarchies) where they add clarity.',
    'Population and society: demographic transition theory + Indian demographic data.',
    'Sociology of science and technology: Merton\'s CUDOS norms, technoscience.',
    'Civil society vs. state: Gramsci\'s hegemony is relevant here.',
    'Identity politics in post-liberalisation India: caste, religion, language all reasserted.',
    'Social control: formal vs. informal, norm internalization.',
    'Crowd, public, mass — distinguish carefully in social psychology questions.',
    'Disability and society: social model vs. medical model.',
    'Aging population: sociological consequences for family, state, care work.',
    'Migration and its social consequences: internal, international, gendered dimensions.',
    'Understand Pierre Bourdieu: habitus, field, capital — tested more in recent years.',
    'Giddens and structuration theory: agency-structure debate resolved differently.',
    'Ethnicity and nationalism: primordialism vs. constructivism.',
    'Violence against women: sociological categories (dowry, honour, institutional).',
    'NGOs and development: role, critique, dependency.',
    'Urban sociology: spatial segregation, slums, informal sector.',
    'Social institutions are interrelated — show linkages (family→education→economy).',
    'Know the NEP 2020, NFHS data — current policy context elevates answers.',
    'Practice 250-word timed answers — most fail on brevity, not knowledge.',
    'Mock test question: "Is caste dead?" — practice this in 20 and 250 words both.',
    'Sociological imagination (C. Wright Mills): connect personal troubles to public issues.',
    'Bureaucracy from a sociological lens: Weber, Michels\'s iron law of oligarchy.',
    'Parsons\'s pattern variables: universalism vs. particularism in Indian context.',
    'Reference group theory: relative deprivation explains social unrest better than absolute poverty.',
    'Social network analysis: strong vs. weak ties (Granovetter) — labour market implications.',
    'Collective behaviour: crowd, mass, public — Neil Smelser\'s value-added theory.',
    'Anomie vs. alienation: Durkheim\'s normlessness vs. Marx\'s estrangement — don\'t conflate.',
    'Power elite (C.W. Mills): convergence of military, corporate, political power.',
    'Meritocracy debate: does education actually open mobility in India?',
    'Life chances (Weber): class shapes access to goods, services, opportunities.',
    'Digital divide in India: gender, urban-rural, income dimensions.',
    'Sociology of consumption: Veblen\'s conspicuous consumption in Indian middle class.',
    'Social capital (Putnam): bridging vs. bonding — community resilience implications.',
    'Adivasi land rights: intersection of tribal sociology and constitutional law.',
    'Agricultural labour in India: class formation, migration, MGNREGS impact.',
    'Patron-client relations in rural India: jajmani system successor forms.',
    'Panchayati Raj and social change: women\'s reservation actual vs. formal power.',
    'Suicide (Durkheim): four types — apply egoistic/anomic to contemporary India.',
    'Work and the informal sector: 90% of Indian workforce — sociological implications.',
    'Religion and social solidarity: Durkheim\'s collective effervescence in Indian festivals.',
    'Pollution and purity concept (Dumont): Homo Hierarchicus — critique included.',
    'Social stratification in post-liberalisation India: new inequalities emerging.',
    'Cultural capital (Bourdieu): education system reproduces class inequality.',
    'Intersectionality: caste+gender+class — Dalit feminist perspective.',
    'Commodification of culture: commercialisation of tribal arts, folk traditions.',
    'Crime and deviance: labelling theory (Becker) applied to criminal justice in India.',
    'Secularism in practice: temple-entry movements, cow protection laws — sociological reading.',
    'Vegetarianism and identity in India: ritual, cultural, and class dimensions.',
    'Sociology of knowledge: whose knowledge counts in school curricula?',
    'Civil religion (Bellah): patriotism as quasi-religious practice.',
    'Globalisation and hybridisation of culture: glocalism in Indian TV, fashion, food.',
    'Transgender rights in India: NALSA judgment and its sociological significance.',
    'Menstruation taboo in India: purity-pollution, contested by young urban women.',
    'Domestic labour and care economy: invisible work, predominantly female.',
    'Patriarchy: classical and neoclassical theories — Sylvia Walby\'s six structures.',
    'Caste and democracy: Rajni Kothari\'s "politicisation of caste" thesis.',
    'Social movements and cyberactivism: #MeToo, #DalitLivesMatter in India.',
    'Disability and care: sociological analysis of institutions vs. community care.',
    'Childhood as a social construct: cross-cultural variation, child labour in India.',
    'Honour killing: caste endogamy enforcement — sociology of violence.',
    'Healthcare disparities: caste, class, gender determine access and outcomes.',
    'Oral history as sociological method: subaltern voices, limitations.',
    'Political sociology: how power shapes and is shaped by social structures.',
    'Sociology of sport: embodiment, nationalism, commercialisation in IPL era.',
    'Mental health and society: stigma, medicalisation, cultural idioms of distress.',
    'Environmental sociology: risk society (Beck) — industrial hazards, Bhopal legacy.',
    'Surveillance and social control: Panopticon (Foucault) in digital age.',
    'Sociological theories of development: modernisation, dependency, world-systems.',
    'Always end sociology answers by connecting theory to Indian empirical reality.',
    'Social exclusion framework (Amartya Sen): capability deprivation beyond income poverty.',
  ],

  anthropology: [
    'Anthropology has four fields — biological, cultural, archaeological, linguistic. Know each.',
    'Physical anthropology: ABO blood groups, somatoscopy, dermatoglyphics — factual, marks-safe.',
    'Race as a biological concept is rejected — know the scientific consensus and its history.',
    'Evolution: Darwin vs. Lamarck — teleological fallacy of Lamarckism must be noted.',
    'Palaeoanthropology: hominid fossil sequence — Australopithecus → Homo erectus → sapiens.',
    'Indian tribal communities: Scheduled Tribes classification, constitutional provisions.',
    'Ethnography vs. ethnology: method vs. comparative study — sharp distinction needed.',
    'Malinowski\'s functionalism: every cultural element has a function, but know the critique.',
    'Morgan\'s evolutionism is discredited — say so explicitly when citing it.',
    'Boas and cultural relativism: each culture must be understood on its own terms.',
    'Kinship systems: lineage, clan, moiety, phratry — don\'t conflate.',
    'Marriage types: monogamy, polygyny, polyandry (fraternal) — with Indian tribal examples.',
    'Bride price vs. dowry: economic and social significance, direction of payment.',
    'Totemism: Durkheim and Freud have different readings — present both.',
    'Witchcraft and magic: Evans-Pritchard\'s Azande study is the reference point.',
    'Rites of passage (Van Gennep): separation → liminality → incorporation. Tribal examples.',
    'Applied anthropology: tribal development, health, forensic anthropology — practical angle.',
    'Tribal education policy in India: 5th and 6th Schedules, TRTRI system.',
    'Scheduled Tribes and forest rights: FRA 2006 is a landmark — know it cold.',
    'Genetic anthropology: mitochondrial DNA and out-of-Africa hypothesis.',
    'Cultural ecology (Steward): adaptation to environment shapes culture.',
    'Symbolic anthropology: Geertz\'s "thick description" — interpretation, not just observation.',
    'Structural anthropology (Lévi-Strauss): binary oppositions, myth analysis.',
    'Displacement and tribal communities: dam projects, mining — Narmada, POSCO case.',
    'Nutrition anthropology: food taboos, malnutrition in tribal belts.',
    'Urban anthropology: tribe to city migration, identity change.',
    'Medical anthropology: illness vs. disease, ethno-medicine, traditional healers.',
    'Forensic anthropology: age, sex, stature estimation — numerical ranges matter.',
    'Blood typing: ABO, Rh, MN — genetics + population distribution.',
    'Somatometry vs. somatoscopy: quantitative vs. qualitative physical assessment.',
    'Anthropometry: cephalic index, nasal index — what they show and their limits.',
    'Women in tribal societies: status variation by tribe — matrilineal examples (Khasi, Garo).',
    'Acculturation vs. assimilation vs. integration: definitional precision scores.',
    'Ethnocentrism vs. cultural relativism: the tension at the heart of anthropology.',
    'Child-rearing practices: cultural variation in attachment, weaning, initiation.',
    'Language and culture: Sapir-Whorf hypothesis, linguistic relativity.',
    'Cognitive anthropology: folk taxonomies, ethnoscience.',
    'Political systems in tribal societies: bands, tribes, chiefdoms, states (Service).',
    'Economic anthropology: gift economy (Mauss), reciprocity types (Sahlins).',
    'Social change theories: evolutionary, diffusionist, functionalist — critique all.',
    'Jajmani system in India: caste-based economic exchange, its decline.',
    'Sacred vs. profane (Durkheim): the foundational distinction in religion anthropology.',
    'Tribal resistance movements: Birsa Munda, Santhal Hul — political anthropology.',
    'Denotified tribes in India: colonial legacy, criminal tribes act.',
    'Gender and anthropology: Margaret Mead\'s contribution and controversy.',
    'Pastoralism: nomadic herding societies, ecology, contemporary pressures.',
    'Hunting-gathering societies: band organisation, sharing norms, modern survivors.',
    'Globalisation and indigenous peoples: cultural homogenisation, rights movements.',
    'UNESCO and cultural heritage: intangible cultural heritage protection.',
    'Writing style tip: define every technical term on first use — examiners may not be specialists.',
    'Hardy-Weinberg equilibrium: conditions and deviations — gene frequency in populations.',
    'Genetic drift vs. natural selection: distinguish carefully in population genetics questions.',
    'Microsatellite DNA in forensics: variable number tandem repeats (VNTR) principle.',
    'Primate behaviour: grooming, dominance hierarchy, cooperation — sociobiology implications.',
    'Neanderthal-Homo sapiens interbreeding: ancient DNA evidence — recent findings.',
    'Multiregional vs. Out-of-Africa hypothesis: current evidence strongly favours OoA.',
    'Ritual pollution and tribal communities: compare to caste system — similarities and differences.',
    'Ghost marriage, levirate, sororate: unusual marriage forms with social logic.',
    'Fictive kinship: godparenthood, blood brotherhood — kinship beyond biology.',
    'Ethnobotany: tribal plant knowledge — applied anthropology for conservation.',
    'Cargo cults (Melanesia): revitalisation movements — theory of cultural contact.',
    'Shamanism: cross-cultural phenomenon — healing, divination, spirit communication.',
    'Syncretism in Indian tribal religion: mixing of tribal and Hindu beliefs.',
    'Chiefdom societies: redistributive economy, ranked hierarchy, warfare.',
    'Segmentary lineage system (Evans-Pritchard, Nuer): how kinship organises politics.',
    'Anthropology of childhood: enculturation, socialisation — cross-cultural patterns.',
    'Body as cultural text: tattooing, scarification, body modification — meaning across cultures.',
    'Material culture: objects as social facts — archaeology meets anthropology.',
    'Globalisation and cultural extinction: UNESCO endangered cultures list.',
    'Fourth World peoples: indigenous rights, UNDRIP 2007 — Indian implications.',
    'Cross-cousin marriage preference in South India: kinship algebra explained.',
    'Joking relationships and avoidance relationships: social distance management.',
    'Age-grade societies (East Africa): structured peer groups — Indian parallels.',
    'Violence and culture: ritual vs. interpersonal violence — anthropological distinctions.',
    'Power and body: Foucauldian anthropology — surveillance, discipline, biopolitics.',
    'Language acquisition: universal grammar (Chomsky) vs. cultural relativity debate.',
    'Visual anthropology: film as ethnographic method, photo-documentation.',
    'Multi-sited ethnography (Marcus): follow the object, metaphor, conflict, biography.',
    'Reflexivity in fieldwork: the observer\'s role in shaping what is observed.',
    'Ethical issues in anthropology: informed consent, community benefit, representation.',
    'Decolonising anthropology: critique of colonial-era ethnographies.',
    'Human ecology: cultural adaptation to different environments — comparative.',
    'Post-colonial anthropology: writing culture debate (Clifford and Marcus 1986).',
    'Biocultural approach: gene-culture co-evolution — lactase persistence example.',
    'Potlatch ceremony (Northwest Coast): competitive gift-giving as status display.',
    'Sacred space and pilgrimage anthropology: Char Dham, Kumbh — crowd behaviour.',
    'Indian diaspora: cultural retention vs. adaptation — transnational identity.',
    'Applied forensic anthropology in India: natural disaster victim identification.',
    'Nutritional anthropology: hidden hunger, micronutrient deficiency in tribal India.',
    'Kula ring (Malinowski): ceremonial exchange building alliances — reciprocity type.',
    'Childhood initiation rites: puberty ceremonies signal social vs. biological maturity.',
    'Displacement and tribal communities: dam projects, mining — Narmada, POSCO case.',
    'Women in tribal societies: matrilineal examples like Khasi and Garo.',
    'Anthropometry: cephalic index, nasal index — what they measure and their limits.',
    'Somatometry vs. somatoscopy: quantitative vs. qualitative physical assessment.',
    'Blood typing: ABO, Rh, MN — genetics and population distribution.',
    'Language and culture: Sapir-Whorf hypothesis, linguistic relativity debate.',
    'Write concise definitions first — in anthropology, precision beats elaboration.',
    'Ethnomusicology: music as cultural expression — tribal music in UPSC context.',
    'Legal anthropology: customary law, tribal courts, interface with state law in India.',
  ],

  geography: [
    'Geography optional rewards diagrams — always draw a labelled sketch for geomorphology answers.',
    'Geomorphic processes: endogenic vs. exogenic — clearly differentiate with examples.',
    'Plate tectonics: the unifying theory of physical geography. Connect to every landform question.',
    'Drainage patterns: dendritic, trellis, radial, centripetal — with Indian river examples.',
    'Monsoon mechanism: Hadley cell, ITCZ, El Niño — link climatology to India-specific rainfall.',
    'Soil types in India: Alluvial, Black, Red, Laterite — crop affinity for each.',
    'Demographic transition model: India is between Stage 2–3. Know where each state is.',
    'Migration theory: push-pull factors, Ravenstein\'s laws, contemporary Indian patterns.',
    'Human Development Index: components, India\'s rank, regional variation.',
    'Agricultural geography: Green Revolution, its regional unevenness, second Green Revolution debate.',
    'Industrial location theories: Weber, Losch, Perroux — match to Indian examples.',
    'Urbanisation in India: census definition, million-plus cities, counter-urbanisation.',
    'Regional planning: growth poles, backward regions, special category states.',
    'GIS and remote sensing: increasingly tested. Know what each can and can\'t do.',
    'Coastal geography: erosion, deposition, coastal landforms — Sundarbans, Western Ghats.',
    'Glacial landforms: cirque, arête, drumlin, esker — names + formation process.',
    'Karst topography: limestone dissolution features, Indian examples (Meghalaya caves).',
    'Arid landforms: barchans, seif dunes, yardangs — hot desert geography.',
    'Biogeography: biomes, Wallace\'s line, island biogeography — MacArthur-Wilson.',
    'Climate change geography: IPCC reports, sea-level rise impacts on Indian coast.',
    'River systems: rejuvenation, knick point, graded profile — advanced physical geography.',
    'Earthquake zones in India: map them, explain causes, Himalayan seismicity.',
    'Tropical cyclones: genesis, Bay of Bengal vs. Arabian Sea frequency difference.',
    'Ocean currents: warm vs. cold, their effect on adjacent landmass climate.',
    'Fishing zones: EEZ, continental shelf, Indian fisheries geography.',
    'Energy geography: coal belt, oilfields, renewable energy potential by region.',
    'Transport geography: NH network, golden quadrilateral, dedicated freight corridor.',
    'Spatial interaction: Ullman\'s bases — complementarity, transferability, intervening opportunity.',
    'Central Place Theory (Christaller): hexagonal market areas, rank-size rule.',
    'Core-periphery model: Wallerstein applied to India\'s regional inequality.',
    'Water resource geography: interstate river disputes (Cauvery, Krishna) — judicial commissions.',
    'Mineral resources: ferrous vs. non-ferrous, spatial distribution in India.',
    'Tribal geography: concentration in central India, North-East — forest dependency.',
    'Natural hazard geography: floods, droughts, avalanches — vulnerability mapping.',
    'Carrying capacity: ecological concept applied to tourism and urban planning.',
    'Sustainable development: Brundtland Commission, ecological footprint.',
    'Special Economic Zones: geography of exports, coastal location logic.',
    'Language geography: dialect continuum, linguistic states reorganisation 1956.',
    'Religious geography of India: pilgrimage routes, temple town systems.',
    'Gender geography: female literacy, sex ratio maps reveal regional patterns.',
    'Wetlands and Ramsar sites in India: ecosystem services approach.',
    'Eastern vs. Western Ghats: compare age, direction, biodiversity, rainfall shadow.',
    'Desert reclamation: Rajasthan Canal, IGNP — geography of irrigation expansion.',
    'Census data use: always cite Census 2011 (or 2021 if available) for demographic answers.',
    'Urban hierarchy: primate city, rank-size rule violations in India.',
    'Resource geography: renewable vs. non-renewable, concept of resource conservation.',
    'Physiography of India: 6 physiographic divisions — detail, examples, economic relevance.',
    'North-East India: unique geography, biodiversity hotspot, political sensitivity.',
    'Sea level rise: which Indian coasts are most vulnerable and why.',
    'Practice map-based answers: unlabelled sketch + correct location = bonus marks.',
    'Geospatial technology: GPS, GIS, remote sensing — interdependence and applications.',
    'Biogeochemical cycles: carbon, nitrogen, hydrological — human disruption of each.',
    'Permafrost thawing: feedback loops, methane release, impact on Himalayan slopes.',
    'Urban heat island effect: causes, mitigation, Indian metro examples.',
    'Desertification: causes, UNCCD, Rajasthan case study.',
    'Groundwater depletion: over-extraction, subsidence, recharge rates — Punjab crisis.',
    'Coastal erosion: longshore drift, wave refraction — Mumbai coast, Kerala.',
    'Tectonic geomorphology: fault scarps, rift valleys, horst-graben — East African Rift.',
    'Periglacial processes: freeze-thaw, solifluction, stone polygons.',
    'Loess deposits: wind-blown silt, significance for agriculture — China and India.',
    'Meanders and oxbow lakes: fluvial geomorphology at intermediate level.',
    'Braided vs. meandering rivers: discharge variability, load-carrying capacity.',
    'Alluvial fans and deltas: compare location, process, economic use.',
    'Aeolian processes: deflation, abrasion, deposition — desert and coastal.',
    'Rock types and landform control: granite, limestone, basalt — different weathering.',
    'Mass wasting: falls, slides, flows, creep — Himalayan landslide vulnerability.',
    'Speleology: cave formation, stalactites, stalagmites — karst processes.',
    'Insolation and heat budget: albedo, greenhouse effect — quantitative understanding.',
    'Jet streams: polar and sub-tropical, their influence on Indian weather.',
    'Western disturbances: origin, path, winter precipitation in north India.',
    'Thunderstorm genesis: convective instability, CAPE — Nor\'westers of Bengal.',
    'Fog types: radiation, advection, steam — seasonal occurrence in India.',
    'Inversion of temperature: anticyclones, valley fog — air quality implications.',
    'Soil profile: horizons O-A-B-C — how parent material, climate, vegetation shape it.',
    'Salinisation of soils: waterlogging + irrigation — canal-irrigated areas of India.',
    'Mangroves: ecology, economic value, carbon sequestration — Sundarbans threat.',
    'Coral bleaching: thermal stress, ocean acidification — Lakshadweep and Andamans.',
    'Sacred groves (Dev Vans): traditional conservation, biodiversity hotspot in farmland.',
    'Economic geography of SEZs: location logic, labour implications, success metrics.',
    'Cold chain geography: agriculture-market connectivity — perishables and farm income.',
    'Port geography: hinterland, foreland, dry ports — JNPT, Mundra, Paradip.',
    'Pipeline geography: gas vs. oil vs. water — linear infrastructure planning.',
    'Tourism geography: ecotourism, carrying capacity — Himalayan over-tourism crisis.',
    'Cultural landscape: Sauer\'s definition — how culture transforms nature over time.',
    'Political geography: boundaries, buffer states, enclaves — Cooch Behar example.',
    'Heartland-Rimland theory: Mackinder and Spykman — apply to Eurasian geopolitics.',
    'Electoral geography: constituency delimitation, gerrymandering possibility in India.',
    'Micro-watersheds: unit for integrated land-water management — watershed programs.',
    'Smart cities: India\'s 100 smart cities mission — critical geographic appraisal.',
    'Night-time satellite imagery: economic activity proxy — India\'s dark and bright zones.',
    'Land use/land cover change: deforestation quantification — forest cover report.',
    'Aquifer mapping: confined vs. unconfined, recharge zones, water table depth.',
    'Cyclone track prediction: RSMC Delhi\'s role, Bay of Bengal vs. Arabian Sea tracks.',
    'Geography of health: disease ecology, epidemiological transition — India\'s burden.',
    'Urban hierarchy: primate city, rank-size rule violations in India.',
    'Language geography of India: script boundaries ≠ dialect boundaries.',
    'Refugee geography: camp locations, urban displacement, legal frameworks.',
    'Geostatistics: spatial autocorrelation, interpolation — for advanced aspirants.',
    'Use sketch maps and diagrams in every physical geography answer — they earn marks.',
    'Shanty towns and informal settlements: spatial expansion of cities in developing world.',
  ],

  'political-science': [
    'Political theory questions reward thinkers + concepts + application — use all three.',
    'State, sovereignty, nation — three distinct concepts. Conflating them loses marks.',
    'Social contract tradition: Hobbes (Leviathan), Locke (consent), Rousseau (general will).',
    'Liberalism: classical vs. welfare vs. neo-liberal — show the evolution.',
    'Marxism: base-superstructure, class struggle, state as instrument of ruling class.',
    'Gram \'s hegemony: why consent, not just coercion, sustains power.',
    'Federalism in India: cooperative, competitive, asymmetric — with constitutional articles.',
    'Parliamentary vs. Presidential system: Westminster model and its Indian modifications.',
    'Judicial review and judicial activism in India: landmark cases matter.',
    'Fundamental Rights: Article-wise, limitations, evolution via amendment.',
    'Directive Principles: non-justiciable but enforceable — explain the paradox.',
    'Coalition politics in India: ideological vs. opportunistic — post-1989 analysis.',
    'Election Commission of India: independence, powers, recent controversies.',
    'Civil society and democracy: Tocqueville through to NGO politics in India.',
    'Nationalism: liberal, civic, ethnic, religious variants — Indian expression.',
    'Secularism: Western (separation) vs. Indian (equidistance) — critical comparison.',
    'Gender and politics: women\'s reservation, political participation data.',
    'Public policy process: agenda-setting, formulation, implementation, evaluation.',
    'Bureaucracy: Weberian ideal type, India\'s IAS system, administrative reform.',
    'International Relations theory: Realism, Liberalism, Constructivism — briefly distinguish.',
    'India\'s foreign policy: non-alignment to strategic autonomy — continuity and change.',
    'United Nations: reform debates, P5 veto, India\'s UNSC bid.',
    'Human rights: UDHR, treaty bodies, India\'s record on civil liberties.',
    'Globalisation and the state: does sovereignty erode? Give both sides.',
    'Regionalism in India: linguistic, economic, sub-national movements.',
    'Media and democracy: fourth estate ideal vs. corporate media reality.',
    'Corruption and governance: systemic causes, anti-corruption institutions.',
    'Local self-government: 73rd and 74th Amendments, their implementation gap.',
    'Social movements: from class-based to identity-based — new social movements.',
    'Terrorism and counter-terrorism: legal framework, civil liberties tension.',
    'Environmental politics: climate change negotiation, India\'s position.',
    'Right to Information Act: empowerment and limitations.',
    'Welfare state: Beveridge model, its decline, Indian social protection debate.',
    'Constitutional morality vs. popular morality (B.R. Ambedkar) — a deep answer theme.',
    'Comparative politics: use Indian examples to illustrate comparative concepts.',
    'Authoritarian resurgence globally: democratic backsliding, India debate.',
    'Electoral reforms: FPTP vs. PR, EVM controversies, model code.',
    'Judiciary independence: appointments, collegium, NJAC controversy.',
    'Emergency (1975–77): constitutional provisions, political consequences.',
    'Political economy of development: growth vs. distribution debate in India.',
    'Minority rights: constitutional provisions, multiculturalism debate.',
    'Nuclear policy: No First Use, India-Pakistan-China triangle.',
    'Soft power: cultural diplomacy, Indian Ocean strategy.',
    'Cyber governance: digital sovereignty, surveillance state.',
    'Decentralisation: theory vs. practice gap in Indian Panchayati Raj.',
    'Partition and state-building: two-nation theory and its contradictions.',
    'Security Council reform: L69, G4 — India\'s multilateral diplomacy.',
    'Constitutionalism: rule of law, separation of powers, checks and balances.',
    'Write from a political science perspective — avoid journalism, engage theory.',
    'Cold War legacy: non-alignment as a concept, its relevance or irrelevance in a multipolar world.',
    'Majoritarian democracy vs. constitutional democracy: tensions in Indian context.',
    'Deliberative democracy (Habermas): public sphere, communicative rationality.',
    'Democratic theory: aggregative vs. deliberative vs. participatory — compare.',
    'State capture: when private interests colonise regulatory agencies.',
    'Subaltern counter-publics (Fraser): marginalised groups\' parallel discursive arenas.',
    'Electoral authoritarianism: competitive but unfair elections — hybrid regimes.',
    'Federalism and ethnicity: managing diversity — Belgium, Canada, India compared.',
    'Consociationalism (Lijphart): power-sharing in divided societies.',
    'Judicial activism and democratic deficit: counter-majoritarian dilemma.',
    'Party system institutionalisation: India\'s party system compared to Latin America.',
    'Electoral volatility: measuring stability of voter preferences over time.',
    'Presidentialism vs. parliamentarism: outcomes for democracy quality.',
    'Campaign finance reform: limits, disclosure, state funding models.',
    'Exit, voice, loyalty (Hirschman): citizen responses to institutional decline.',
    'Neo-liberalism and governance: reduced state, PPP, BOOT models — critique.',
    'State failure: criteria, examples, governance vacuum — India\'s insurgency zones.',
    'Security dilemma: IR concept with South Asian application — arms race dynamics.',
    'Unipolar moment to multipolarity: American decline debate — implications for India.',
    'BRICS, SCO, QUAD: competing regionalism — India\'s multi-alignment strategy.',
    'Track II diplomacy: back-channel negotiations — India-Pakistan examples.',
    'Responsibility to Protect (R2P): humanitarian intervention and sovereignty debate.',
    'Democratic peace theory: democracies don\'t fight each other — Indian Ocean test.',
    'Constructivism in IR: ideas and identity matter — India\'s civilisational role narrative.',
    'Development and democracy: Asia\'s authoritarian growth model and its critique.',
    'Environmental governance: Paris Agreement architecture, INDCs, loss and damage.',
    'Technology and surveillance: state power expansion, digital authoritarianism.',
    'Disinformation and elections: political manipulation of information ecosystems.',
    'Minority nationalism: Sikh, Kashmir, Naga — competing self-determination claims.',
    'Right-wing populism globally: features, causes, comparison with India.',
    'Post-colonial state: Fanon, Chatterjee, Mamdani — different framings.',
    'Agrarian politics: land reforms, farmer protests — political economy lens.',
    'Naxal movement: political sociology of left-wing extremism in India.',
    'Affirmative action: philosophical justification, implementation, backlash.',
    'Caste-based political mobilisation: OBC assertion post-Mandal Commission.',
    'Communal violence: riot, pogrom — political construction (Paul Brass).',
    'Water conflict: Cauvery, Krishna — interstate disputes as political science.',
    'Climate security: link between resource scarcity and conflict — India\'s region.',
    'Nuclear doctrine: NFU, credible minimum deterrence — India\'s strategic posture.',
    'Space policy: outer space as domain of geopolitics, ISRO as strategic asset.',
    'Soft power measurement: Monocle ranking, Brand India — assessment.',
    'Democracy and social media: political campaigns, disinformation, regulation.',
    'Separation of powers in India: overlaps, tensions — coalition executive and Parliament.',
    'Political culture: Almond and Verba\'s civic culture applied to India.',
    'State autonomy vs. class instrument: two theories of the state compared.',
    'De-radicalisation programs: evidence from India\'s counter-insurgency experience.',
    'Deliberation vs. aggregation in democracy: referenda, town halls, citizen assemblies.',
    'Always ground IR theory in India-specific examples — examiners reward contextualisation.',
    'Populism theory (Laclau, Mouffe): people vs. elite framing — India\'s electoral politics.',
    'Administrative state vs. democratic state: tension between expertise and accountability.',
    'Resource curse thesis: oil-rich states and democratic deficit — applied to global south.',
  ],

  'public-administration': [
    'Every answer should name a theorist — Frederick Taylor, Henri Fayol, Simon, Drucker.',
    'Classical vs. neo-classical vs. modern schools: timeline and key thinkers for each.',
    'POSDCORB (Luther Gulick): still tested, still relevant. Know each element.',
    'Max Weber\'s bureaucracy: characteristics, dysfunctions, and Indian applicability.',
    'New Public Management (NPM): 3 E\'s — Economy, Efficiency, Effectiveness.',
    'Governance vs. Government: participatory, multi-actor, network governance.',
    'E-Governance: G2C, G2B, G2G — Indian examples (DigiLocker, UMANG, CoWIN).',
    'Public Policy models: rational, incremental (Lindblom), mixed-scanning (Etzioni).',
    'Policy implementation: top-down vs. bottom-up approaches, street-level bureaucrats.',
    'Administrative discretion: necessary but dangerous — checks and accountability.',
    'Organisation theory: line, line-staff, functional, matrix — compare applicability.',
    'Leadership styles: autocratic, democratic, laissez-faire — situational leadership.',
    'Motivation theories: Maslow, Herzberg, McGregor X and Y — apply to public servants.',
    'Span of control: tall vs. flat hierarchy — tradeoffs, Indian administrative context.',
    'Delegation and decentralisation: distinct concepts, often confused — define both early.',
    'CAG of India: constitutional status, functions, limitations.',
    'RTI Act 2005: section-wise knowledge for landmark answers.',
    'Lokpal and Lokayukta: jurisdiction, independence, comparison with other ombudsman models.',
    'Administrative Tribunals: Articles 323A & 323B, types, jurisdiction.',
    'Civil services reform: 2nd ARC recommendations — 6th report (local governance) important.',
    'Public financial management: budget cycle, FRBM Act, fiscal federalism.',
    'Accountability: political, legal, administrative, financial, social — know all.',
    'Good governance indicators: World Bank\'s six — rule of law, voice, control of corruption.',
    'Cooperative federalism: concurrent list, inter-state council, Finance Commission.',
    'NITI Aayog vs. Planning Commission: continuity and departure.',
    'Citizens\' Charter: concept, Indian experience, Sevottam framework.',
    'Performance management: KPIs in public administration, limitations of metrics.',
    'Disaster management: NDMA, SDMAs, ICS (Incident Command System).',
    'Social audit: Mazdoor Kisan Shakti Sangathan, MGNREGS application.',
    'Corruption: petty vs. grand, causes (poor pay, discretion, weak institutions).',
    'Transparency and accountability: difference, complementarity.',
    'Human resource management in public sector: recruitment, training, promotion, conduct.',
    'Ethics in public administration: Nolan Principles, code of conduct.',
    'Gender-responsive governance: GRB (Gender Responsive Budgeting).',
    'IT in administration: data governance, AI in public services, digital inclusion.',
    'Urban local bodies: mayor-in-council vs. commissioner system.',
    'Rural development administration: Block Development Office, DRDA, role of NGOs.',
    'Welfare administration: direct benefit transfer, targeting vs. universal coverage.',
    'Public enterprises: rationale, forms, disinvestment policy.',
    'Regulatory administration: TRAI, SEBI, IRDA — regulatory capture risk.',
    'Comparative public administration: US, UK, France, Sweden models for contrast.',
    'Simon\'s bounded rationality: limits of the rational-comprehensive model.',
    'Comparative federalism: India vs. USA vs. Australia — degree of centralisation.',
    'Parliamentary committees: PAC, Estimates Committee — oversight function.',
    'Centre-State administrative relations: Article 256, 257, 263.',
    'Policy evaluation: ex-ante vs. ex-post, logic model.',
    'Public interest litigation: administrative accountability through courts.',
    'Whistleblower protection: Whistle Blowers Protection Act 2014.',
    'Administrative culture: values, norms, how they shape outcomes in Indian bureaucracy.',
    'Exam tip: structure answers as Definition → Theory → Indian Example → Critique/Reform.',
    'New Public Governance (NPG): networks, co-production, moving beyond NPM.',
    'Principal-agent problem in public administration: information asymmetry and accountability.',
    'Street-level bureaucrats (Lipsky): how front-line workers shape policy in practice.',
    'Administrative law: rule of law, natural justice, judicial review of admin action.',
    'Quasi-judicial bodies: NHRC, CIC, CEC — powers and independence.',
    'Budget cycle in India: Union Budget, Demands for Grants, Appropriation Bill.',
    'Output vs. outcome budgeting: measuring performance in government schemes.',
    'Outcome-based monitoring: logic model, theory of change in development programs.',
    'Revenue vs. capital expenditure: distinction and implications for fiscal health.',
    'Fiscal federalism: Finance Commission, grants-in-aid, devolution formula.',
    'Centre-State financial relations: tax assignment, transfers, conditional grants.',
    'Administrative reorganisation: 1st ARC (1966) vs. 2nd ARC (2005–2009) — compare scope.',
    'Knowledge management in government: how state agencies learn and adapt.',
    'Reinventing Government (Osborne and Gaebler): customer-driven, results-oriented government.',
    'Public choice theory (Buchanan): bureaucrats maximise budgets, not public welfare.',
    'Niskanen model: budget-maximising bureaucracy — critique of public sector growth.',
    'Managerialism in public sector: importing private management into government.',
    'Regulatory impact assessment: cost-benefit analysis before issuing new regulations.',
    'Ombudsman institution: Sweden origin, India\'s Lokayukta variation, effectiveness.',
    'Internal audit vs. external audit: complementary but distinct functions.',
    'Concurrent Audit: real-time financial oversight in large schemes like MGNREGS.',
    'Administrative ethics: conflict of interest, gifts, revolving door problem.',
    'Servant leadership: Robert Greenleaf\'s model applied to public administration.',
    'Crisis management: NDMA framework, Incident Response System — India\'s evolution.',
    'Welfare administration: conditional cash transfers, JAM trinity — DBT outcomes.',
    'Health administration: NHM, Ayushman Bharat — federated implementation challenges.',
    'Education administration: SSA, NEP 2020 — central-state-local coordination.',
    'Labour administration: labour codes consolidation, EPFO, ESIC.',
    'Agricultural administration: MSP mechanism, FCI, PDS reforms.',
    'Forest administration: MoEFCC, Joint Forest Management, Forest Rights Act implementation.',
    'Police administration: dual control problem, state vs. central, Prakash Singh case.',
    'Prison administration: 3 Ds — delay, denial, deprivation — reform imperatives.',
    'Public administration in coalition era: political executive instability and bureaucratic continuity.',
    'Comparative administration: developed vs. developing country systems — Riggs prismatic model.',
    'Prismatic society (Riggs): partially modernised administration — India fits this model.',
    'Sala model (Riggs): bureaucracy in developing societies — heterogeneity, formalism, overlapping.',
    'Post-Weberian public administration: post-NPM, collaborative governance.',
    'Digital governance challenges: data privacy, interoperability, exclusion risk.',
    'Aadhaar and welfare delivery: inclusion, exclusion errors, privacy concerns.',
    'Single window clearance: ease of doing business reform — administrative simplification.',
    'Minimum Government Maximum Governance: slogan to policy — critical appraisal.',
    'Transparency vs. confidentiality in government: where RTI meets Official Secrets Act.',
    'Performance Appraisal Report (PAR): APAR system, bell curve, integrity column.',
    'Lateral entry into IAS: pros, cons, implementation experience.',
    'Government-NGO interface: complementarity vs. competition, regulation.',
    'Mission Karmayogi: civil services capacity building reform — design and critique.',
    'Administrative geography: district as the unit of governance — collector\'s role.',
    'Span of management in digital age: information systems reduce need for layers.',
    'Public satisfaction surveys: citizen feedback mechanisms in India\'s service delivery.',
    'Administrative silos: coordination failure between departments — whole-of-government approach.',
  ],
};

const DEFAULT_TIPS = [
  'Write one answer every day — consistency beats last-minute cramming.',
  'Analyse topper copies to understand what examiners actually reward.',
  'Focus on structure: Introduction → Body (3 paras) → Conclusion.',
  'PYQs repeat — knowing patterns is half the battle.',
  'Use AI Chat to clarify concepts before writing practice answers.',
];

export default function Dashboard() {
  const router = useRouter();
  const [user, setUser] = useState<User | null>(null);
  const [optional, setOptional] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [tip, setTip] = useState('');

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (firebaseUser) => {
      if (!firebaseUser) { router.push('/login'); return; }
      setUser(firebaseUser);
      try {
        const token = await firebaseUser.getIdToken();
        const res = await fetch('/api/user-profile', { headers: { 'x-user-token': token } });
        if (res.ok) {
          const data = await res.json();
          if (!data.optional) { router.push('/onboarding'); return; }
          setOptional(data.optional);
          const pool = TIPS_BY_OPTIONAL[data.optional] ?? DEFAULT_TIPS;
          setTip(pool[Math.floor(Math.random() * pool.length)]);
        }
      } catch {}
      setLoading(false);
    });
    return () => unsubscribe();
  }, [router]);

  if (loading) return (
    <div style={{ minHeight: '80vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <div style={{ width: 32, height: 32, borderRadius: '50%', border: '2px solid var(--border2)', borderTopColor: 'var(--accent)', animation: 'spin 0.7s linear infinite' }} />
      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
    </div>
  );

  const firstName = user?.displayName?.split(' ')[0] || user?.email?.split('@')[0] || 'there';
  const optLabel = optional ? optional.charAt(0).toUpperCase() + optional.slice(1).replace('-', ' ') : '';
  const hour = new Date().getHours();
  const greeting = hour < 12 ? 'Good morning' : hour < 17 ? 'Good afternoon' : 'Good evening';

  return (
    <div style={{ maxWidth: 1000, margin: '0 auto', padding: '2.5rem 1.5rem 5rem' }}>

      <style>{`
        @keyframes spin{to{transform:rotate(360deg)}}
        @keyframes fadeUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
        .feat-card{transition:border-color 0.15s,transform 0.15s,background 0.15s;}
        .feat-card:hover{border-color:var(--border3)!important;transform:translateY(-2px);background:var(--bg3)!important;}
        @media(max-width:640px){.feat-grid{grid-template-columns:1fr!important;}}
      `}</style>

      {/* ── Hero greeting ── */}
      <div style={{ marginBottom: '2.5rem', animation: 'fadeUp 0.4s ease' }}>
        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 6,
          background: 'rgba(67,97,238,0.08)', border: '1px solid rgba(67,97,238,0.18)',
          color: 'var(--accent)', fontSize: '0.7rem', fontFamily: 'var(--font-ui)',
          padding: '3px 12px', borderRadius: 20, marginBottom: '1rem',
          letterSpacing: '0.08em', textTransform: 'uppercase',
        }}>
          <span style={{ width: 5, height: 5, borderRadius: '50%', background: 'var(--accent)', display: 'inline-block' }} />
          {optLabel} Optional
        </div>

        <h1 style={{
          fontFamily: 'var(--font-display)',
          fontSize: 'clamp(1.8rem, 4vw, 2.6rem)',
          fontWeight: 700, color: 'var(--text)',
          letterSpacing: '-0.025em', lineHeight: 1.15,
          marginBottom: '0.5rem',
        }}>
          {greeting}, {firstName}.
        </h1>
        <p style={{ color: 'var(--text3)', fontSize: '0.95rem', fontFamily: 'var(--font-ui)' }}>
          {user?.email}
        </p>
      </div>

      {/* ── Tip banner ── */}
      <div style={{
        background: 'rgba(67,97,238,0.05)',
        border: '1px solid rgba(67,97,238,0.15)',
        borderRadius: 12, padding: '0.9rem 1.25rem',
        marginBottom: '2rem',
        display: 'flex', alignItems: 'flex-start', gap: 12,
        animation: 'fadeUp 0.45s ease',
      }}>
        <span style={{ fontSize: '1.1rem', flexShrink: 0, marginTop: 1 }}>💡</span>
        <p style={{ color: 'var(--text2)', fontSize: '0.875rem', fontFamily: 'var(--font-ui)', lineHeight: 1.55, margin: 0 }}>
          <span style={{ color: 'var(--accent)', fontWeight: 600 }}>Tip: </span>{tip}
        </p>
      </div>

      {/* ── Feature grid ── */}
      <div style={{ marginBottom: '0.75rem' }}>
        <h2 style={{
          fontFamily: 'var(--font-ui)', fontSize: '0.7rem',
          textTransform: 'uppercase', letterSpacing: '0.1em',
          color: 'var(--text3)', marginBottom: '1rem',
        }}>Your Tools</h2>
      </div>

      <div className="feat-grid" style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: '1rem',
        marginBottom: '2.5rem',
        animation: 'fadeUp 0.5s ease',
      }}>
        {FEATURES.map((f) => (
          <Link key={f.href} href={f.href} style={{ textDecoration: 'none' }}>
            <div className="feat-card" style={{
              background: 'var(--bg2)',
              border: '1px solid var(--border)',
              borderRadius: 14,
              padding: '1.5rem',
              height: '100%',
              display: 'flex', flexDirection: 'column', gap: '0.75rem',
              cursor: 'pointer',
              position: 'relative',
            }}>
              {f.badge && (
                <span style={{
                  position: 'absolute', top: 12, right: 12,
                  fontSize: '0.6rem', fontFamily: 'var(--font-ui)',
                  fontWeight: 700, letterSpacing: '0.06em',
                  padding: '2px 7px', borderRadius: 10,
                  background: f.badge === 'Premium' ? 'rgba(232,184,109,0.12)' : 'rgba(74,222,128,0.1)',
                  color: f.badge === 'Premium' ? 'var(--gold)' : '#4ade80',
                  border: `1px solid ${f.badge === 'Premium' ? 'rgba(232,184,109,0.25)' : 'rgba(74,222,128,0.2)'}`,
                }}>
                  {f.badge}
                </span>
              )}
              <div style={{
                width: 44, height: 44, borderRadius: 12,
                background: `color-mix(in srgb, ${f.color} 12%, transparent)`,
                border: `1px solid color-mix(in srgb, ${f.color} 25%, transparent)`,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: '1.3rem', flexShrink: 0,
              }}>
                {f.icon}
              </div>
              <div>
                <div style={{
                  color: 'var(--text)', fontWeight: 600,
                  fontSize: '0.95rem', fontFamily: 'var(--font-ui)',
                  marginBottom: '0.3rem',
                }}>{f.label}</div>
                <div style={{
                  color: 'var(--text3)', fontSize: '0.8rem',
                  fontFamily: 'var(--font-ui)', lineHeight: 1.5,
                }}>{f.desc}</div>
              </div>
              <div style={{ marginTop: 'auto', color: f.color, fontSize: '0.78rem', fontFamily: 'var(--font-ui)', fontWeight: 500 }}>
                Open →
              </div>
            </div>
          </Link>
        ))}
      </div>

      {/* ── Quick actions ── */}
      <div style={{
        background: 'var(--bg2)', border: '1px solid var(--border)',
        borderRadius: 14, padding: '1.5rem',
        animation: 'fadeUp 0.55s ease',
      }}>
        <h2 style={{
          fontFamily: 'var(--font-ui)', fontSize: '0.7rem',
          textTransform: 'uppercase', letterSpacing: '0.1em',
          color: 'var(--text3)', marginBottom: '1.25rem',
        }}>Quick Actions</h2>
        <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap' }}>
          {[
            { label: '📝 Evaluate an answer', href: '/evaluate', primary: true },
            { label: '💬 Ask AI a question', href: '/chat', primary: false },
            { label: '🗂️ Browse PYQs', href: '/pyqs', primary: false },
            { label: '📖 Read notes', href: '/notes', primary: false },
          ].map((a) => (
            <Link key={a.href} href={a.href} style={{
              textDecoration: 'none',
              background: a.primary ? 'var(--accent)' : 'var(--bg3)',
              color: a.primary ? '#fff' : 'var(--text2)',
              border: `1px solid ${a.primary ? 'transparent' : 'var(--border2)'}`,
              padding: '0.55rem 1.1rem',
              borderRadius: 8,
              fontSize: '0.85rem',
              fontFamily: 'var(--font-ui)',
              fontWeight: 500,
              transition: 'opacity 0.15s',
            }}>
              {a.label}
            </Link>
          ))}
        </div>
      </div>

    </div>
  );
}
